### ISSUE TITLE
No way to manage comments!

### ISSUE THREAD

**Issue by MMaKenZi** [mageplaza/magento-2-blog#101]
I just know your blog extension. 
and checked it's abilities, as I so there is no way to manage comments in admin
and this is so strange

I think the most important thing for blogs, are comments and the comments are like blood in blog veins

so if the admin, couldn't manage them or see if new comment is submitted, how he should communicate with blog's users?

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by haitv282** [comment]
Hi there,

Thank you for your feedback.
We highly appreciate any ideas, suggestions and comments like yours and consider them in our next improvement to make our products better. Thank you very much!

**Comment by Mehran91z** [comment]
+1 for adding some simple comment management! I cant event remove spam comments!!

**Comment by LevapLondon** [comment]
same problem cant edit review or even delete comments - which is no good at all - documentation clearly states "Default Comment: Customers need to login their account to be able to comment, admins can manage those comments in the backend."
Really would someone kindly tell us or show us where
