### ISSUE TITLE
Fix missing Store_Ids Column

### ISSUE THREAD

**Issue by imsamthomas** [mageplaza/magento-2-blog#102]
Step 1: 

copy UpgradeData.php and UpgradeSchema.php file to the path : \app\code\Mageplaza\Blog\Setup
copy module.xml file to the path : \app\code\Mageplaza\Blog\etc

Step 2: 

Run command  to upgrade module

```
php bin/magento setup:upgrade
```

Patch:  
[Fix missing Store_Ids Column.zip](https://github.com/mageplaza/magento-2-blog/files/1456674/Fix.missing.Store_Ids.Column.zip)

**Comment by blizam** [comment]
Is this required to do on top of the latest version?

**Comment by imsamthomas** [comment]
Hi,

This is an old patch, you can ignore it!

**Comment by blizam** [comment]
tyty!
