### ISSUE TITLE
Is this module compatible with the version 2.2.1 of Magento?

### ISSUE THREAD

**Issue by AndreaRiva** [mageplaza/magento-2-blog#105]
Is this module compatible with the version 2.2.1 of Magento?

**Comment by haitv282** [comment]
Hi Andrea,
Yes, this extension is compatible with Magento 2.2.x.

**Comment by jafarp26** [comment]
hi 
i have installed this extension , i am getting below error
Fatal error: Uncaught Error: Call to undefined method Mageplaza\Blog\Helper\Data::getConfigValue() in helper file

**Comment by jafarp26** [comment]
Can you update the helper file with above Function getConfigValue().

**Comment by Tuvpt** [comment]
Hi
I'm Curtis from Mageplaza.
Regarding your reported issue, I can answer as below:

You should check the existence of function getConfigValue() in Mageplaza\Blog\Helper\Data.
If not, then you can add:
    /**
     * @param $field
     * @param null $storeId
     * @return mixed
     */
    public function getConfigValue($field, $storeId = null)
    {
        return $this->scopeConfig->getValue(
            $field,
            ScopeInterface::SCOPE_STORE,
            $storeId
        );
    }

If there are any further problems, feel free to contact us.
Thank you!
