### ISSUE TITLE
Notice: Undefined property: Mageplaza\Blog\Helper\Data::$postfactory

### ISSUE THREAD

**Issue by alloylab** [mageplaza/magento-2-blog#107]
### Preconditions
1. Magento: 2.2.1
2. PHP: 7.1.11

### Steps to reproduce

       \Magento\Sitemap\Model\Observer $Observer,
        \Magento\Framework\App\State $State,
        \Magento\Framework\Config\ScopeInterface $configScope
1. Generate sitemap via, $results = $this->Observer->scheduledGenerateSitemaps();
2. 
3. 

### Expected result
1. no error 

### Actual result

1. Notice: Undefined property: Mageplaza\Blog\Helper\Data::$postfactory in /var/www/app/code/Mageplaza/Blog/Model/Sitemap.php on line 61

**Comment by Tuvpt** [comment]
I'm Curtis  from Mageplaza.
Regarding your reported issue, I can answer as below:

You should check the existence of $postfactory in Mageplaza\Blog\Helper\Data.
If not, then you can add:
/* * @var \Mageplaza\Blog\Model\PostFactory */ 
public $postFactory;
and declare it in function __construct ().

If there are any further problems, feel free to contact us.
Thank you!

**Comment by alloylab** [comment]
This issue is with incorrect capital letters in Sitemap.php

[Exception]                                                                                                                                                   
  Notice: Undefined property: Mageplaza\Blog\Helper\Data::$postfactory in /Users/tjferre/Git/cw/store/src/app/code/Mageplaza/Blog/Model/Sitemap.php on line 61

[Exception]                                                                                                                                                       
  Notice: Undefined property: Mageplaza\Blog\Helper\Data::$categoryfactory in /Users/tjferre/Git/cw/store/src/app/code/Mageplaza/Blog/Model/Sitemap.php on line 94

[Exception]                                                                                                                                                   
  Notice: Undefined property: Mageplaza\Blog\Helper\Data::$tagfactory in /Users/tjferre/Git/cw/store/src/app/code/Mageplaza/Blog/Model/Sitemap.php on line 114

[Exception]                                                                                                                                                     
  Notice: Undefined property: Mageplaza\Blog\Helper\Data::$topicfactory in /Users/tjferre/Git/cw/store/src/app/code/Mageplaza/Blog/Model/Sitemap.php on line 134

Factory should be capitalized

**Comment by tm999283124** [comment]
How can a bug like this even exist? Did they not test the functionality whatsoever? Wow.

**Comment by Kenny1994** [comment]
Hi tm999283124,

Sorry for this inconvenient. I fixed this problem and push the fix to develop branch.
Please see this commit for more details: https://github.com/mageplaza/magento-2-blog/commit/33aa0eecdb52410cda01ac17822a34c82185f126
If there are any further questions, please feel free to contact us.
Thank you very much!

**Comment by alloylab** [comment]
@tm999283124 I stopped using all mageplaza modules after this incident... even one that I had paid for. I have two issues with this... 1. Their initial response to my issue was extremely poor ... 2. to your point how could this have been missed... it tells me no testing was done.

**Comment by imsamthomas** [comment]
@alloylab , if you want to get faster support service, please try to contact us at support@mageplaza.com
or https://www.mageplaza.com/contact.html
