### ISSUE TITLE
Magento 2 Blog: Migration from wordpress

### ISSUE THREAD

**Issue by joshspivey** [mageplaza/magento-2-blog#11]
Has anyone made a migration script to go from word press?

**Comment by imsamthomas** [comment]
We have this plan but we have not release in short future.

**Comment by tjsteinhaus** [comment]
Any idea when this will be released?

**Comment by imsamthomas** [comment]
We are planing this feature and update you EAT soon

**Comment by jamesryanbell** [comment]
Any update on this please

**Comment by imsamthomas** [comment]
We released the import feature, [read more](https://github.com/mageplaza/magento-2-blog/tree/develop).
