### ISSUE TITLE
admin Logon

### ISSUE THREAD

**Issue by jpkazzi** [mageplaza/magento-2-blog#111]
HI , 
After installing the module , I lost access to the backend 
I got this error 

There has been an error processing your request

Exception printing is disabled by default for security reasons.

Error log record number: 422702568028

I Checked online and i was told to change local.xml.sample to local.xml
it generated a new error Could not create an acl object: Role '5' not found

The website suggested to do the following 
Open magento/lib/Zend/Cache/Backend/File.php and look for:

protected $_options = array(
'cache_dir' => 'null',

Change it to:

protected $_options = array(
'cache_dir' => 'tmp/',

But file.php doesn't exist 
I'm using magento 2 

Thanks

**Comment by Tuvpt** [comment]
Hi,
For the technical issues, please submit your ticket to https://mageplaza.freshdesk.com 
	and provide the following information in the submit form:

	- Magento temporary login details (including Back-end URL)
	- Temporary SSH/ SFTP log in details (should be able to read/write pub/ var/ folders)

	Our support team will look into your particular case as soon as possible.
