### ISSUE TITLE
Breadcrumb error when a blog widget is loaded on layout

### ISSUE THREAD

**Issue by HRV52** [mageplaza/magento-2-blog#112]
If I create a widget with Mageplaza_Blog and add blog post on footer layout, my breadcrumb is always loaded with Blog name's inside. Even if i'm not in the blog section.

### Preconditions

1. Magento: 2.1.9
2. PHP: 7.0
3. MySQL: 5.0.12
4. Mageplaza_Blog: 2.4.3

### Steps to reproduce

1. Add a widget to layout with Mageplaza_Blog

### Expected result

1. Don't add Blog Name's on the breadcrumb on every page

### Actual result

1. Blog Name's on the breadcrumb on every page
![blog-breadcrum](https://user-images.githubusercontent.com/13470457/34830891-4bed9e26-f6b3-11e7-97dd-f5bbc2a74d74.jpg)

`Mageplaza\Blog\Block\Frontend.php`

```
protected function _prepareLayout()
    {
        if ($breadcrumbs = $this->getLayout()->getBlock('breadcrumbs')) {
            $breadcrumbs->addCrumb('home', [
                'label' => __('Home'),
                'title' => __('Go to Home Page'),
                'link'  => $this->_storeManager->getStore()->getBaseUrl()
            ])
                ->addCrumb($this->helperData->getRoute(), $this->getBreadcrumbsData());
        }

        $this->applySeoCode();

        return parent::_prepareLayout();
    }

```

**Comment by Tuvpt** [comment]
Hi,
I’m Curtis from Mageplaza.com.
I have already received your issue reports and I am sorry for that.
To solve this problem, please change function getBreadcrumbsData()  into  Mageplaza\Blog\Block\Frontend.php file with the following code:

    protected function getBreadcrumbsData()
    {
        $label = $this->helperData->getBlogName();
        $data = [];
        if (stristr($this->getRequest()->getFullActionName(),'mpblog')) {
            $data = [
                'label' => $label,
                'title' => $label,
                'link'  => $this->helperData->getBlogUrl()
            ];
        }
        return $data;
    }

**Comment by OvalMedia** [comment]
Will this be fixed in the repo?

**Comment by NgoDuVietHung97** [comment]
Hi @OvalMedia,

We had updated it in the repository.
Please download the latest version of Blog Extension to use them.
Thank you for your interest in our product.
Have a nice day!
