### ISSUE TITLE
User locale not picked up when saving post with UK formatted publish date

### ISSUE THREAD

**Issue by Alex-James17** [mageplaza/magento-2-blog#113]
With the store set to use a en_US locale and the logged in admin user set to use a en_GB locale, the date formats are incompatible for the post publish date. For example, editing a post in the admin panel and setting the publish date to the 22nd January 2018 using the calendar widget displays the date as 22/01/2018 (standard UK format). However, when the date is submitted to the controller:

Blog\Controller\Adminhtml\Post'Save.php 

the prepareData() method receives the date in "d/m/Y H:i" format (22/01/18 00:00), however this is incompatible with the store locale which is expecting the date in "m/d/Y H:i" format (01/22/18 00:00). The result is that the following error is thrown on post save:

1 exception(s):
Exception #0 (Exception): DateTime::__construct(): Failed to parse time string (22/01/2018 00:00) at position 0 (1): Unexpected character 
..... 
/Blog/Controller/Adminhtml/Post/Save.php(130): Magento\Framework\Stdlib\DateTime\Timezone->convertConfigTimeToUtc('22/01/2018 00:0...')

Adding custom code to flip the date to "m/d/Y H:i" ahead of the call to convertConfigTimeToUtc() enables the post to be saved correctly.

### Preconditions
1. Magento: 2.2.0-dev
2. PHP: 7.0.27
3. MySQL: 5.6
4. Magento-2-blog: 2.5.0

### Steps to reproduce
1. Install a version of the blog module > 2.4.2
2. Set the store locale to en_US
3. Create an admin user and set the user's locale to en_GB
4. Create a new blog post and using the calendar widget select a publish date of 22nd January 2018
5. Attempt to save the post

### Expected result
The post should save without error

### Actual result
The post does not save, the following error is thrown:

1 exception(s):
Exception #0 (Exception): DateTime::__construct(): Failed to parse time string (22/01/2018 00:00) at position 0 (1): Unexpected character

**Comment by Kenny1994** [comment]
Hi,
Thank for your report.I have faced this problem so many times before.
Temporarily, there are no Magento core functions can change the date time format based on the configuration in automatically.
Therefore, we must add the custom code if the customer wants to change to another locale.
