### ISSUE TITLE
Something went wrong while saving Post

### ISSUE THREAD

**Issue by barbarac82** [mageplaza/magento-2-blog#114]
After installation, the post not saving and the message is "Something went wrong while saving the Post."
During the installation I had problems with the table prefixes.
After the database changes I have done magento upgrade and the blog is displayed correctly, but I can not save a post.

### Preconditions

1. Magento: 2.1.9
2. PHP: 7.0.27
3. MySQL:  5.6.38
--

**Comment by Tuvpt** [comment]
Hi,
For the technical issues, please submit your ticket to https://mageplaza.freshdesk.com
and provide the following information in the submit form:

- Magento temporary login details (including Back-end URL)
- Temporary SSH/ SFTP log in details (should be able to read/write pub/ var/ folders)
Our support team will look into your particular case as soon as possible.
