### ISSUE TITLE
Error generating sitemaps

### ISSUE THREAD

**Issue by jeffmalterre** [mageplaza/magento-2-blog#115]
### Preconditions

1. Magento: 2.2.2
2. PHP: 7.0
3. MySQL: 5.7.21

### Steps to reproduce

1. Install Magento
2. Install Blog
3. Generate Sitemap

### Expected result

1. A sitemap should have been generated.

### Actual result

1. [Screenshot, logs]
[2018-01-30 20:43:59] main.CRITICAL: Exception message: Notice: Undefined property: Mageplaza\Blog\Helper\Data::$postfactory in vendor/mageplaza/magento-2-blog-extension/Model/Sitemap.php on line 61
Trace: #0 vendor/mageplaza/magento-2-blog-extension/Model/Sitemap.php(61): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined prope...', '/var/www/cfspha...', 61, Array)
#1 vendor/mageplaza/magento-2-blog-extension/Model/Sitemap.php(155): Mageplaza\Blog\Model\Sitemap->getBlogPostsSiteMapCollection()
#2 vendor/magento/module-sitemap/Model/Sitemap.php(392): Mageplaza\Blog\Model\Sitemap->_initSitemapItems()
#3 vendor/magento/module-sitemap/Controller/Adminhtml/Sitemap/Generate.php(26): Magento\Sitemap\Model\Sitemap->generateXml()
#4 vendor/magento/framework/App/Action/Action.php(107): Magento\Sitemap\Controller\Adminhtml\Sitemap\Generate->execute()
#5 vendor/magento/module-backend/App/AbstractAction.php(229): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#6 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#7 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor->___callParent('dispatch', Array)
#8 vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Sitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#9 vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#11 generated/code/Magento/Sitemap/Controller/Adminhtml/Sitemap/Generate/Interceptor.php(26): Magento\Sitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor->___callPlugins('dispatch', Array, NULL)
#12 vendor/magento/framework/App/FrontController.php(55): Magento\Sitemap\Controller\Adminhtml\Sitemap\Generate\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#13 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#14 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#15 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#16 generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#17 vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#18 vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#19 index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#20 {main} [] []

**Comment by Kenny1994** [comment]
Hi,
I have checked the problem and the reported issue has appeared on my local site.
Here is my fix, please download and replace the old one to resolve the problem: https://github.com/mageplaza/magento-2-blog/commit/33aa0eecdb52410cda01ac17822a34c82185f126
If there are any further problems, please feel free to contact us.
Thank you very much!
