### ISSUE TITLE
[Resolved] Blog version 2.6.0 compile error

### ISSUE THREAD

**Issue by Ig0r-M** [mageplaza/magento-2-blog#116]
Updating extensions from 2.5.0 to 2.6.0 to fix problems with sitemap following error popup when running command `php bin/magento setup:di:compile`

### Preconditions

1. Magento: 2.2.1

### Steps to reproduce

1. Update blog extension to 2.6.0
2. Run command `php bin/magento setup:di:compile`

### Expected result

1. Compile should run without any error

### Actual result

![image](https://user-images.githubusercontent.com/22006850/36212217-4a8f2d94-119b-11e8-8e24-862c34c352aa.png)

**Comment by Kenny1994** [comment]
Hi,
Thanks for reporting the bug. I'm Kenny from Mageplaza.
Regarding your reported issue, here is my quick fix on the develop branch, please see the commit for more details: https://github.com/mageplaza/magento-2-blog/commit/f4ad2eb0dee93999c07b879131c4bc9256301326
If there are any further problems, please feel free to contact us.
Thank you very much!

**Comment by ryantfowler** [comment]
@Kenny1994 I appreciate the fact that this is an open source project, and therefore free of charge. I was just curious why some blatant errors like this (and others such as case errors with class property names) are released? It would appear to me that there's a lack of testing prior to releasing code. Maybe your team has requirements to put more time and effort into maintaining paid extensions, which is understandable...but wouldn't be better to just wait and test the code before releasing it? All that this does is create a negative image of extension quality and cause people to question whether or not they should introduce Mageplaza code into their codebase and risk production issues. Again, I'm not attacking you or trying to be overly critical. I'm just offering up a suggestion. Thank you and Mageplaza for your hard work.

**Comment by ryantfowler** [comment]
@Kenny1994 I just tested out the suggested changes in your commit and di compilation is successful now. Is there any way that you could cut another release so that we can require a known-good version of this extension without requiring a custom extension to patch it (or edit the extension directly in the vendor directory)? Thanks

**Comment by Kenny1994** [comment]
Hi @ryantfowler 

We are sincerely sorry to our customer about this unworthy issue. We will improve and test the code carefully before released in the future to avoid any troubles during the experiencing process with our product. I hope that you are interested in our current product and other featured products. We will try our best to make it better.

One more time, I want to say thank you for reporting and giving me the valuable advice.

**Comment by Ig0r-M** [comment]
@Kenny1994 any ETA related to new release?

**Comment by Kenny1994** [comment]
@Ig0r-M The blog extension has been released version 2.6.0 already, this is the hotfix and it will be added to the main patch soon.

**Comment by sinamiandashti** [comment]
any ETA?
my compile is broken too

**Comment by Ig0r-M** [comment]
@Kenny1994 given the fact that current release is not in working state does it not require to have another one e.g. v2.6.1 which will include this small hotfix as you can't expect everyone using your extension to implement your hotfix by customising extension and then reverting back to composer version when you do another major release ?

**Comment by ryantfowler** [comment]
@Kenny1994 I've included a [PR#117](https://github.com/mageplaza/magento-2-blog/pull/117) which is a simplified patch to the problem. It only adds the required changes to allow di compilation to succeed.

**Comment by Kenny1994** [comment]
@ryantfowler thanks. I have merged your commit.

**Comment by ryantfowler** [comment]
@imsamthomas Thanks for the update ... good to know that the latest changes have made it to the master branch ... the only problem with using the command you've provided is that upon a new deployment at any given moment, someone could get a potentially unstable version of this project, versus having a known, good version to commit to their composer.json .

**Comment by ryantfowler** [comment]
@imsamthomas @Kenny1994 I wanted to point out that packagist.org seems to have a stale commit id for [dev-master](https://packagist.org/packages/mageplaza/magento-2-blog-extension#dev-master). The only way to get this extension as a composer package currently, with the necessary fixes would be to copy this repository, and self-host it with Satis/Packagist.com/similar solution... or reference this repository directly.

**Comment by imsamthomas** [comment]
Maybe composer cache issue.
Try this command line to pull latest version without caching.

```
composer require mageplaza/magento-2-blog-extension --prefer-source
````

**Comment by trinhpham** [comment]
Version 2.6.2 faces this issue again.
Tested on Magento CE 2.1.9
![image](https://user-images.githubusercontent.com/9128061/38159475-3d43b88e-34d3-11e8-9bc8-30cb3667be39.png)

**Comment by trinhpham** [comment]
@imsamthomas Please review and reopen this issue.
