### ISSUE TITLE
Insert  tags in HEAD (e.g. og:image)

### ISSUE THREAD

**Issue by cedricve** [mageplaza/magento-2-blog#119]
Hey Mageplaza team,

I was wondering if you support (or will support) the possibility to add meta tags in the head. So far I didn't found any documentation that allows us to do something like this. I only found the possibility to add metadata keywords and description.

This is crucial when sharing the blog post on social media like facebook.

Thanks

**Comment by Kenny1994** [comment]
Hi,
Yes, we will support any customer's request for our extension.
For the technical support, please submit your ticket to https://mageplaza.freshdesk.com and provide the following information in the submit form:

	- Magento temporary login details (including Back-end URL)
	- Temporary SSH/ SFTP log in details (should be able to read/write pub/ var/ folders)

Our support team will look into your particular case as soon as possible.
