### ISSUE TITLE
Notice: Undefined index: id

### ISSUE THREAD

**Issue by pascal08** [mageplaza/magento-2-blog#120]
### Preconditions
**Environment**
Magento: 2.1.10
PHP: 7.0
MySQL: 5.7

**Mageplaza modules**
mageplaza/magento-2-dutch-language-pack@dev-master,
mageplaza/magento-2-blog-extension@2.6.0
mageplaza/module-core@1.3.9

### Steps to reproduce
1. Install composer modules listed above 
2. Run ```php bin/magento setup:upgrade```
3. Open Admin >> Stores >> Configuration

### Expected result
1. Configuration page should be shown

### Actual result
1. Exception is thrown: ```Notice: Undefined index: id```

I've tried [this solution](https://github.com/mageplaza/module-core/issues/6) and [this solution](https://github.com/mageplaza/module-core/issues/3) but the problem persist.

**Comment by Kenny1994** [comment]
Hi,
Sorry for the late response, we are checking the issue on our local but there is no issue that you mentioned.
Please try to re-install both Blog, Core module and check again.
Maybe you are missing something while installing.
