### ISSUE TITLE
Sitemap Image Urls Incompatible With Google Requirements

### ISSUE THREAD

**Issue by ryantfowler** [mageplaza/magento-2-blog#122]
Currently, the sitemap which is generated produces image urls which are relative and not absolute, and therefore Google states that it is not able to find said images and the submitted sitemap has errors. This is also a problem if a M2 store is configured to use a different media path, such as a CDN, as the generated relative path will not correlate with the hostname associated with media distribution.

### Preconditions
1. Magento: 2.2.1, 2.2.2, 2.2.3
2. PHP: 7.0, 7.1
3. MySQL: 5.7

### Steps to reproduce
1. Locate a M2 installation that uses the latest version of this extension
2. Log into it's admin panel
3. Go to Marketing->Sitemap
4. Generate a sitemap
5. Right-click and open the sitemap in a new tab
6. Inspect the `<image:loc>` nodes which are produced
7. Notice that they are relative paths
8. Log into Google Webmaster Tools
9. Perform a test submission of this generated sitemap
10. Note the response from Google

### Expected result
1. Log into the admin panel, generate a sitemap, submit it to Google
2. Not be presented with any error messages due to the Mageplaza M2 Blog extension producing incorrectly formatted XML nodes

### Actual result
1. Errors

### Solution
1. PR: https://github.com/mageplaza/magento-2-blog/pull/121

**Comment by Kenny1994** [comment]
The commit has been merged

**Comment by lenvanessen** [comment]
Hi, let's reopen this one, this is not fully working as expected.

It always uses the url of the main store, instead of using the url of the store that the sitemap is generated for.

**Comment by ryantfowler** [comment]
@Kenny1994 I also noticed that the PR code was reverted due to incompatibility with v2.1.x? Could you possibly provide a list of versions that this extension is targeting support for? @lenvanessen I didn't even think to include store scope in the PR, that's a good idea. If I can get a clear response from @Kenny1994 , then I'll update my code and produce another PR. Thanks

**Comment by lenvanessen** [comment]
@ryantfowler any news/eta on this?

**Comment by ryantfowler** [comment]
@lenvanessen no, I haven't heard anything back from @Kenny1994 or anyone at Mageplaza to know which versions of M2 they are targeting support for, for this extension. I suppose I could just create a PR so that what is generated based on the current code is store scoped. I'll try to get to it soon.

**Comment by lenvanessen** [comment]
If its any help, this is wat I did as a hotfix:

Expand the media helper to allow setting the store
```
  /**
     * @param string $file
     * @return string
     */
    public function getMediaUrl($file, $storeId = null)
    {
        return $this->getBaseMediaUrl($storeId) . '/' . $this->_prepareFile($file);
    }

    /**
     * @return string
     */
    public function getBaseMediaUrl($storeId = null)
    {
        return rtrim($this->storeManager->getStore($storeId)->getBaseUrl(UrlInterface::URL_TYPE_MEDIA), '/');
    }
```

Pass in the store ID in the helper
```

    /**
     * @return array
     */
    public function getBlogPostsSiteMapCollection()
    {
        $postCollection = $this->blogDataHelper->postFactory->create()->getCollection();
        $postSiteMapCollection = [];
        if (!$this->router) {
            $this->router = 'blog';
        }

        foreach ($postCollection as $item) {

            if (!is_null($item->getEnabled())) {
                $images = null;
                if ($item->getImage()) :
                    $imageFile = $this->imageHelper->getMediaPath(
                        $item->getImage(),
                        \Mageplaza\Blog\Helper\Image::TEMPLATE_MEDIA_TYPE_POST
                    );
                    $imagesCollection[] = new DataObject([
                            'url' => $this->imageHelper->getMediaUrl($imageFile, $this->getStoreId()),
                            'caption' => null,
                        ]
                    );
                    $images = new DataObject(['collection' => $imagesCollection]);
                endif;
                $postSiteMapCollection[$item->getId()] = new DataObject([
                    'id' => $item->getId(),
                    'url' => $this->router . '/post/' . $item->getUrlKey(),
                    'images' => $images,
                    'updated_at' => $item->getUpdatedAt(),
                ]);
            }
        }

        return $postSiteMapCollection;
    }
```
