### ISSUE TITLE
Not working with porto theme

### ISSUE THREAD

**Issue by prosmack** [mageplaza/magento-2-blog#129]
### Preconditions

1. Magento: 2.1.10
2. PHP: 7.0.27
3. MySQL: 5.6
4. Porto magento 2 theme

### Steps to reproduce

1. install magento 2.1.10
2. install and enable porto theme
3. install mageplaza blog extension

### Expected result

1. The post should be made without error

### Actual result

1. Fatal error: Call to a member function add() on array in ***/app/code/Mageplaza/Blog/Plugin/PortoTopmenu.php on line 75

**Comment by Kenny1994** [comment]
Hi,
Your reported bug has been found and resolved.
Here is the resolved issue commit detail, please check: https://github.com/mageplaza/magento-2-blog/commit/f375c4efa15a06282fc374aec899a8761ccc2062.
If there are any further problems, please feel free to contact us.
Thank you very much!
