### ISSUE TITLE
Page not found when access rss.xml

### ISSUE THREAD

**Issue by guaneagler** [mageplaza/magento-2-blog#130]
### Preconditions

1. Magento: 2.2.2
2. PHP: 7.0.26
3. MySQL: 5.6.33
4. module version: 2.6.1

### Steps to reproduce

1.  Install module
2.  leave the 'Url Suffix' as default
3.  Crate one post, and access rss.xml

### Expected result

1.  show rss page.

### Actual result

1. Show page not found

In 98 line of Router.php file, We check the 'Url Suffix', and it logic also include the rss suffix filter. This may be the issue.
We can avoid this issue by add 'Url Suffix' manual, But I think fix it will be perfect.
ths.

**Comment by Kenny1994** [comment]
Hi,
The problem has been found on my test local.
Here is my fix, please check and make sure it is working normally: https://github.com/mageplaza/magento-2-blog/commit/3d54037b68ec2f470ebcb5881a5d1b0d3655a6de
Thank you very much for reporting the bug.

**Comment by guaneagler** [comment]
Thank you
