### ISSUE TITLE
Module is causing me errors on di:compile, and I can't remove it

### ISSUE THREAD

**Issue by dmarkos** [mageplaza/magento-2-blog#131]
I installed the blog module and it started causing me errors on setup:di:compile. So I decided to remove it. I tried disabling, and then uninstalling the module by using --remove-data and --clear-static-content but the error persists and the module is still visible in the modules list, as disabled. I don't have any other 3rd party modules installed, except mageplaza-core which is required for the blog to run. 

The error on setup:di:compile is:

For now my only wish is to remove the module in order for my setup to work again without errors. However after uninstalling the module, there is still a file inside vendor that if I remove it, the system returns even more errors.

### Preconditions

1. Magento: 2.2.2
2. PHP: 7.1.13
3. MySQL: 
4. MariaDB 10.1.30
5. Windows 2008 server
6. Xampp v3.2.2

### Steps to reproduce

1. Install the module
2. Run setup:di:compile
3. Get bellow error
4. Disable and uninstall the module
5. Still get bellow error

### Expected result

1. A system running without errors

### Actual result

1.
`Mageplaza\Blog\Model\ResourceModel\Post\Grid\Collection
                Incompatible argument type: Required type: \Magento\Framework\DB
\Adapter\AdapterInterface. Actual type: \Mageplaza\Blog\Model\ResourceModel\Post
\Grid\connection; File:
C:/xampp/htdocs/magento2/vendor/mageplaza/magento-2-blog-extension/Model/Resourc
eModel/Post/Grid/Collection.php`

`Mageplaza\Blog\Model\ResourceModel\Tag\Grid\Collection
                Incompatible argument type: Required type: \Magento\Framework\DB
\Adapter\AdapterInterface. Actual type: \Mageplaza\Blog\Model\ResourceModel\Tag\
Grid\connection; File:
C:/xampp/htdocs/magento2/vendor/mageplaza/magento-2-blog-extension/Model/Resourc
eModel/Tag/Grid/Collection.php`

`Mageplaza\Blog\Model\ResourceModel\Topic\Grid\Collection
                Incompatible argument type: Required type: \Magento\Framework\DB
\Adapter\AdapterInterface. Actual type: \Mageplaza\Blog\Model\ResourceModel\Topi
c\Grid\connection; File:
C:/xampp/htdocs/magento2/vendor/mageplaza/magento-2-blog-extension/Model/Resourc
eModel/Topic/Grid/Collection.php`

`Total Errors Count: 3`

  `[Magento\Framework\Validator\Exception]
  Error during compilation`

`setup:di:compile`

**Comment by Kenny1994** [comment]
Hi,
I fixed this problem, please download the latest Blog version to fix it.
Here is my compilation test: 

![screenshot_102](https://user-images.githubusercontent.com/26645811/38285662-7deb4490-37eb-11e8-9f7f-11acce4f2459.png)
