### ISSUE TITLE
Most Viewed posts in wrong order due to numbers_view being a varchar field

### ISSUE THREAD

**Issue by NickvdMeij** [mageplaza/magento-2-blog#132]
### Preconditions

1. Magento:  v2.0.12
2. PHP: 7.0.26
3. MySQL: 5.6

### Steps to reproduce

1.  Install plugin
2.  Generated some fake data
2.  go to a page where `Mageplaza\Blog\Block\Frontend\MostView` is used
3.  view the `Most Viewed` posts

### Expected result
1. the `Most Viewed` is ordered by views in descending order

### Actual result

1. the `Most Viewed` is ordered in (semi-)random order

The problem here is that the following logic is executed:

`Mageplaza\Blog\Block\Frontend\MostView:38`
```PHP
$collection->getSelect()
            ->joinLeft(
                ['traffic' => $collection->getTable('mageplaza_blog_post_traffic')],
                'main_table.post_id=traffic.post_id',
                'numbers_view'
            )
            ->order('numbers_view DESC')
            ->limit((int)$this->helperData->getBlogConfig('sidebar/number_mostview_posts') ?: 4);
```

However, the DB column `numbers_view` is a varchar. This means that it will order the posts in *alphabetical* descending order, instead of numeric.

say you have 4 posts with the corresponding `numbers_view` of `4`, `8`, `90`, `401`. If it orders them descending, it will put the `90` as the first item, while actually the `401` should be on top (since its most viewed). This is, like said before, the problem with the varchar and alphabetical ordering instead of numeric ordering.

A temporary workaround is to replace `->order('numbers_view DESC')` with `->order('CAST(numbers_view as SIGNED INTEGER) DESC')` which will make sure the posts get ordered correctly.

To fix this issue, I'd suggest changing the `numbers_view` to an unsigned integer type.

**Comment by Kenny1994** [comment]
Hi,
Thank you so much for your suggestion.
We have tested and we have found the reported problem on our site.
Therefore, here is the fix: https://github.com/mageplaza/magento-2-blog/commit/baf70a40c934cdfb1b2047a043d02f95ca665c61. Please check again.
If there are any further problems, please feel free to contact us. 
Thank you very much!
