### ISSUE TITLE
Exception when saving existing blog post (Failed to parse time string)

### ISSUE THREAD

**Issue by OvalMedia** [mageplaza/magento-2-blog#134]
When saving an existing blog post I get the following exception.
I suspect this has to do with the fact that my date format is not as expected?

> 1 exception(s):
Exception #0 (Exception): DateTime::__construct(): Failed to parse time string (20.04.18 11:43) at position 9 (1): Double time specification

Exception #0 (Exception): DateTime::__construct(): Failed to parse time string (20.04.18 11:43) at position 9 (1): Double time specification
#0 /www/vendor/magento/framework/Stdlib/DateTime/Timezone.php(307): DateTime->__construct('20.04.18 11:43', Object(DateTimeZone))
#1 /www/vendor/mageplaza/magento-2-blog-extension/Controller/Adminhtml/Post/Save.php(132): Magento\Framework\Stdlib\DateTime\Timezone->convertConfigTimeToUtc('20.04.18 11:43')
#2 /www/vendor/mageplaza/magento-2-blog-extension/Controller/Adminhtml/Post/Save.php(83): Mageplaza\Blog\Controller\Adminhtml\Post\Save->prepareData(Object(Mageplaza\Blog\Model\Post), Array)
#3 /www/generated/code/Mageplaza/Blog/Controller/Adminhtml/Post/Save/Interceptor.php(24): Mageplaza\Blog\Controller\Adminhtml\Post\Save->execute()
#4 /www/vendor/magento/framework/App/Action/Action.php(107): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->execute()
#5 /www/vendor/magento/module-backend/App/AbstractAction.php(229): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /www/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /www/vendor/magento/framework/Interception/Interceptor.php(138): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callParent('dispatch', Array)
#8 /www/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#9 /www/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 /www/vendor/magento/framework/Interception/Interceptor.php(153): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /www/generated/code/Mageplaza/Blog/Controller/Adminhtml/Post/Save/Interceptor.php(39): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callPlugins('dispatch', Array, NULL)
#12 /www/vendor/magento/framework/App/FrontController.php(55): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /www/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#15 /www/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#16 /www/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#17 /www/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /www/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#19 /www/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#20 {main}

### Preconditions

1. Magento: 2.2.3
2. PHP: 7.1
3. MySQL: mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
4. 

### Steps to reproduce

1. Create a new blog post and save it
2. open the same post and save it again
3. 

### Expected result
 
1.  The blog post should be updated
 
### Actual result

1. Shop breaks with above quoted exception

**Comment by Kenny1994** [comment]
Hi,
Could you please tell me which timezone you have used?

**Comment by DocOlson** [comment]
Timezone is Europe/Berlin.

This is what I did to make it work for ME:

`$date = false;
        if (isset($data['publish_date']) && !empty($data['publish_date'])) {
            $date = \DateTime::createFromFormat('d.m.d H:i:s', $data['publish_date']);
        }

        if ($date) {
            $date = $date->format('Y-m-d H:i:s');
        }

        $data['publish_date'] = $timezone->convertConfigTimeToUtc($date);`

**Comment by Kenny1994** [comment]
Hi,
We will look on this time zone issue and I will provide you the best solution for this.
Thank you very much!

**Comment by jamesryanbell** [comment]
Hi @Kenny1994, has there been any progress on this please, we are also facing the same issue but with the US timezone.

Thanks,
James

**Comment by NickyBass** [comment]
Same for me, i'm facing the same issue. Time Zone is Europe/Rome

**Comment by mattyl** [comment]
Same issue using Europe/London

Exception #0 (Exception): DateTime::__construct(): Failed to parse time string (24/08/2018 15:00) at position 0 (2): Unexpected character

php 7.1 - magento 2.2.5

**Comment by mattyl** [comment]
Code from @OvalMedia didn't work for me but this did

		//$data['publish_date'] = $timezone->convertConfigTimeToUtc(isset($data['publish_date']) ? $data['publish_date'] : null);
		$date = false;
		if (isset($data['publish_date']) && !empty($data['publish_date'])) {
				$date = $timezone->date($data['publish_date'])->format('Y-m-d H:i:s');
		}
		$data['publish_date'] = $timezone->convertConfigTimeToUtc($date);

by using the timezone and not the application (which in my bootstrap is using UTC) it seems to correctly resolve the issue

**Comment by thaimageplaza** [comment]
Hi Mattyl

The issue has been solved. Please update the latest version Blog extension.
Thank you very much!

**Comment by michelecanal** [comment]
Hi,
In my opinion upgrading to 3.0.3 re-introduce this problem.
Also I have the same problem in 3.0.2 saving author information

**Comment by thaimageplaza** [comment]
Hi Michel.
To solve your issue, please download, unzip and replace attach file.
The path to the file needs to be changed: "Mageplaza\Blog\Model\ResourceModel\Author.php
[Author.zip](https://github.com/mageplaza/magento-2-blog/files/2528071/Author.zip)
"
Please check again. Thank you!

**Comment by michelecanal** [comment]
Hi
good work! Thanks!

Have a nice day!

**Comment by netdesign** [comment]
> Hi Michel.
> To solve your issue, please download, unzip and replace attach file.
> The path to the file needs to be changed: "Mageplaza\Blog\Model\ResourceModel\Author.php
> [Author.zip](https://github.com/mageplaza/magento-2-blog/files/2528071/Author.zip)
> "
> Please check again. Thank you!

Hi @thaimageplaza thanks for your useful FIX.

Just to keep track of the differences between the two Author.php sources I'm attaching the PATCH.

diff ORIGINAL__Author.php Author.php

[Author.patch.11.02.2019.php.zip](https://github.com/mageplaza/magento-2-blog/files/2850509/Author.patch.11.02.2019.php.zip)
