### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method Magento\Sitemap\Helper\Data::getBlogConfig() in /vendor/mageplaza/magento-2-blog-extension/Model/Sitemap.php on line 61

### ISSUE THREAD

**Issue by rbur0425** [mageplaza/magento-2-blog#135]
### Preconditions

1. Magento: 2.2.3
2. PHP: 7.1.16
3. MySQL: 5.7

### Steps to reproduce

1.  Install better blog extension via Composer
2. Ran pp bin/magento setup:upgrade and php bin/magento setup:di:compile then php bin/magento cache:flush
3. Went to Catalog > Product > and edited a configurable product

### Expected result

1. should go to product page

### Actual result

1. I get the error

Fatal error: Uncaught Error: Call to undefined method Magento\Sitemap\Helper\Data::getBlogConfig() in <my site path>/vendor/mageplaza/magento-2-blog-extension/Model/Sitemap.php on line 61

**Comment by Kenny1994** [comment]
Hi,
I have tested on our local and it is working normally.
Could you please upgrade to the latest blog version? Maybe you are using an old Blog version.
Otherwise, please just sent us the package that you used to produce the issue so that we can check that package.
Thank you very much!

**Comment by thaimageplaza** [comment]
Hi ntuong95,
Please update the last version for Blog extension. The error has been fixed
Thank you very much!

**Comment by Ig0r-M** [comment]
Apparently there is no release for 2.7.0, updating now to 3.0.3 and will retest
