### ISSUE TITLE
blog with image doesn't appear on main blog page or category blog page

### ISSUE THREAD

**Issue by xaixis** [mageplaza/magento-2-blog#136]
when i insert a new blog if i put image for that it will be apear on main blog page : https://aroadecor.com/blog
but if i put image for it , blog gonna disappear from main page but i still can see that as single post ( i put direct URL of post on browser )

https://aroadecor.com/blog/post/بررسی-انواع-سینک-ظرفشویی
as you can see this post is present at website but because of it has image on post , it will disappear from main blog page : https://aroadecor.com/blog

### Preconditions
1. Magento: 2.1.3
2. PHP: 7
3. MySQL: 5.6
4. 

### Expected result
to shown all post on main blog page

### Actual result
only post without image appear on main blog page

**Comment by Kenny1994** [comment]
Hi,
Could you please check again? I see that it still appear at the main blog page
You can check this post: 
![selection_066](https://user-images.githubusercontent.com/26645811/40169846-1f6a70b2-59f1-11e8-8423-74607b7cb286.jpg)
https://aroadecor.com/blog/post/بررسی-انواع-سینک-ظرفشویی

**Comment by xaixis** [comment]
yes thank you for your review .
i fix that .
the problem was with the timing of blog . cause i change the timing from A.D to sun calendar the timing of server was different and they appear 1 day after i put them so i put them 1 day behind and everything work fine
