### ISSUE TITLE
[ReflectionException] Class Magento\Config\Model\Config\Reader\Source\Deployed\DocumentRoot does not exist

### ISSUE THREAD

**Issue by metamorphosis00** [mageplaza/magento-2-blog#138]
_Error on setup:di:compile [ReflectionException] Class Magento\Config\Model\Config\Reader\Source\Deployed\DocumentRoot. I find its used in vendor\mageplaza\magento-2-blog-extension\Model\Sitemap.php_

### Preconditions

1. Magento: 2.1
2. PHP: 7.0.22
3. MySQL: Ver 14.14 Distrib 5.7.19-17

### Steps to reproduce

1. php bin/magento setup:di:compile (SSH console)

### Expected result

1. Compiling

### Actual result

1.  http://prntscr.com/jut62s [ReflectionException] Class Magento\Config\Model\Config\Reader\Source\Deployed\DocumentRoot does not exist

**Comment by Kenny1994** [comment]
Hi,
I have checked the issue on the latest Blog version and see that it is working normally.
![selection_004](https://user-images.githubusercontent.com/26645811/41456310-3cfa3dd6-70aa-11e8-8d01-eb65836518d6.png)

To resolve the problem, please use the latest version on Github.
Thank you very much!

**Comment by kriby** [comment]
@Kenny1994 this issue is reproducible on Magento 2.2
Magento\Config\Model\Config\Reader\Source\Deployed\DocumentRoot class is not present on 2.1 and was added on 2.2.

**Comment by gaurid-iprogrammer** [comment]
Hi,

I am also getting the same issue after running following command
 sudo php bin/magento setup:di:compile

This is my local environment:
Magento: 2.1.10
Php:  7.0.30

**Comment by nasimqota** [comment]
Hi, 
after running compiler 
php bin/magento setup:di:compile
I  get this error.

 [ReflectionException]
  Class Magento\Config\Model\Config\Reader\Source\Deployed\DocumentRoot does not exist

it's Magento 2.1.3
Php 7.0.30

**Comment by xsanza9** [comment]
We had the same problem,

We tryed using 'develop' branch and it worked fine.

Regards
