### ISSUE TITLE
getMosviewPosts() return a wrong value

### ISSUE THREAD

**Issue by shinesoftware** [mageplaza/magento-2-blog#14]
Hi guys,

after the installation I get this error:

> Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in /var/www/html2/magento2.local/app/code/Mageplaza/Blog/view/frontend/templates/sidebar/mostview.phtml on line 14

Debugging the code the getMosviewPosts() return an empty string instead of an array:

https://github.com/mageplaza/magento-2-blog-extension/blob/v2.2.0/Helper/Data.php#L270

furthermore the filterItems() method in the data.php helper check the $item->getStoreIds() without success. It returns -1 instead the Store_Ids set in the database table or an empty array().

https://github.com/mageplaza/magento-2-blog-extension/blob/v2.2.0/Helper/Data.php#L297

I think that you can solve it in this way. Starting from this code:

> $itemStore = $item->getStoreIds() ? explode(',', $item->getStoreIds()) : -1;

and considering the $item->getStoreIds() could be ZERO so a better condition is 

> $itemStore = is_numeric($item->getStoreIds()) ? explode(',', $item->getStoreIds()) : array();

Any idea?

**Comment by Kenny1994** [comment]
Hi,
Please try download the lastest version on github. 
Tell me if you have any problems. Thanks !
