### ISSUE TITLE
Porto theme compatibility problem (Magento 2.2)

### ISSUE THREAD

**Issue by Fidelity88** [mageplaza/magento-2-blog#140]
### Preconditions

1. Magento: 2.2.4
2. PHP: 7.0.27
3. MySQL: 5.6
4. Porto magento 2 theme

### Steps to reproduce

1. install magento 2.2.4
2. install and enable latest porto theme
3. install mageplaza blog extension

### Expected result

1. Homepage should work
2. Blog extension should work as expected

### Actual result

1. Fatal error: Call to a member function add() on array in vendor/mageplaza/magento-2-blog-extension/Plugin/PortoTopmenu.php on line 75

Stack trace: #0 /vendor/magento/framework/Interception/Interceptor.php(146): Mageplaza\Blog\Plugin\PortoTopmenu->afterGetStoreCategories(Object(Smartwave\Megamenu\Block\Topmenu\Interceptor), Array, true, false, true)

**Comment by Fidelity88** [comment]
Might be the same as issue #129. Although, this was with an older version of Magento 2 (2.1) and probably an older version of the Porto theme too.

**Comment by thaimageplaza** [comment]
Hi Fidelity,
Please update Blog extension's the latest version.
The error has been fixed.
Please check again.
Have a nice day.
