### ISSUE TITLE
500 error exposing SQL query code on the product page

### ISSUE THREAD

**Issue by vetshopdeveloper** [mageplaza/magento-2-blog#144]
500 error exposing SQL query code on the product page

2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1',' at line 2, query was: SELECT COUNT(*) FROM `mageplaza_blog_post` AS `main_table`
 INNER JOIN `mageplaza_blog_post_product` AS `related` ON related.post_id=main_table.post_id AND related.entity_id= WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1', `store_ids`)))) AND (`publish_date` <= '2018-08-22 07:18:21')

Exception #1 (PDOException): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1',' at line 2

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1',' at line 2, query was: SELECT COUNT(*) FROM `mageplaza_blog_post` AS `main_table`
 INNER JOIN `mageplaza_blog_post_product` AS `related` ON related.post_id=main_table.post_id AND related.entity_id= WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1', `store_ids`)))

### Preconditions

1. Magento: 2.2.5
2. PHP: 7.0.30
3. MySQL: 10.0.34-MariaDB
4. Better Blog Version | 2.7.0

### Steps to reproduce

1. Open product page view network trafix
2.  view request to page_cache/block/render/id/507/?blocks=%5B"social-create-captcha"%2C"social-forgot-password-captcha"%2C"social-login-captcha"%5D&handles=%5B"default"%2C"catalog_product_view"%2C"catalog_product_view_type_configurable"%2C"catalog_product_view_id_507"%2C"catalog_product_view_sku_3226"%5D&originalRequest=%7B"route"%3A"catalog"%2C"controller"%3A"product"%2C"action"%3A"view"%2C"uri"%3A"%2Fnexgard-chewables-for-dogs-10-1-24-lbs-blue"%7D&version=872c3744ed29a690d1f88e586e06cad3

### Expected result

1.  no 500 error

### Actual result

1. returns 500 error with above exceptions

**Comment by thaimageplaza** [comment]
Hi, 
I used Magento 2.2.5, PHP 7.0.28, MySQL 10.3.9-MariaDB,  Blog extension version 3.0.2.
And I see it normal working.
You can check and update Blog extension's the latest version.
Have a nice day!
