### ISSUE TITLE
 Does not appear in the admin menu of magento 2.2.5

### ISSUE THREAD

**Issue by daniellof** [mageplaza/magento-2-blog#145]
I installed the module via composer and also downloaded the files and in none of them showed the blog on the admin menu. Core items but not blog posts appear. In store settings appears normally, however I do not have the menu more than trigger a post, etc.
When I tested it on version 2.2.2 of magento it would appear normally, can you help me with that?

**Comment by LongJackson** [comment]
I've installed the module on both 2.2.2 and 2.2.5 version. And I never see anything abnormal. May I guess you did not notice that the Blog extension appeared in the Content category.  My screen capture below.
http://prntscr.com/ktdksk

Thanks for the installation.

**Comment by RustyIngles** [comment]
I had the same issue as @daniellof but now you've said about the Content category @LongJackson I can see it there, the documentation needs to be updated I think.

Thanks for your help

**Comment by LongJackson** [comment]
Thanks for your notice. We'll get the documentation upgraded soon.

**Comment by nkajic** [comment]
Hi all,
I had same issue with admin menu not being show. To reproduce this problem
Stores > Configuration > Mageplaza extensions > Information > "Enable Mageplaza Menu" needs to be set on "NO"

**Comment by ChienNguyenVP** [comment]
Hi, 
Thank you for your opinion. 
It is really helpful.
