### ISSUE TITLE
No changelog for v3 series of releases in documentation

### ISSUE THREAD

**Issue by vetshopdeveloper** [mageplaza/magento-2-blog#146]
### Preconditions

1. Magento: 
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by thaimageplaza** [comment]
Hi,
Thanks for your response.
To your question, please check file \mageplaza\magento-2-blog\CHANGELOG.
In the file, you can see a link "https://www.mageplaza.com/changelog/m2-blog.txt".
Please access the link,  all the information is already contained in it.
http://prntscr.com/kzma3x
I hope you can be satisfied with these answers. If you have any other questions, please don’t hesitate to contact me again. Have a nice day!

**Comment by vetshopdeveloper** [comment]
Hi, Thank you for the response. 

But it is still a bug in your documentation on GitHub. As there is no mention of v3.0 in the readme.md.

**Comment by thaimageplaza** [comment]
Thanks for your response.
You can find it in the link  "https://www.mageplaza.com/changelog/m2-blog.txt".
Please check the image below. http://prntscr.com/kzoxc0
Thank you!

**Comment by thaimageplaza** [comment]
Thank you for noticing.
The information is now all written into the file  \mageplaza\magento-2-blog\CHANGELOG.
readme.md will be soon deleted.
