### ISSUE TITLE
Localize datetime on frontend based on site locale

### ISSUE THREAD

**Issue by alinalexandru** [mageplaza/magento-2-blog#147]
### Preconditions

1. Magento: 2.2.5
2. PHP: 7.0
3. MySQL: 5.7 
4. 

### Steps to reproduce

1. Use other locale that is not english
2. Check the monthly archive list
3. Check the published date, created date.

### Expected result

1. All the dates should be translated using the site locale settings

### Actual result

1. Are displayed in english.

I think that \Magento\Framework\Stdlib\DateTime\TimezoneInterface should be used.
I am trying to make a pull request for this issue.

**Comment by thaimageplaza** [comment]
Thanks for your response.
To solve your issue, Please replace the file mageplaza/magento-2-blog/Helper/data.php with the file attached.
I hope you can be satisfied with these answers. If you have any other questions, please don’t hesitate to contact me again. Have a nice day!
[Data.zip](https://github.com/mageplaza/magento-2-blog/files/2426478/Data.zip)

**Comment by thaimageplaza** [comment]
If you have any other solution, Please share with us.
Thank you in advance!
