### ISSUE TITLE
Error: Something went wrong while saving the Post.

### ISSUE THREAD

**Issue by alefemafra** [mageplaza/magento-2-blog#149]
### Preconditions

1. Magento: 2.2.6
2. PHP: 7.1.16
3. MySQL: 5.7.24
4. 

### Steps to reproduce

1.  Create New post.
2. Save

### Expected result

1.  Save my post

### Actual result

1. Something went wrong while saving the Post.
![captura de tela 2018-10-29 as 11 38 16](https://user-images.githubusercontent.com/11546384/47657457-e125be00-db6f-11e8-8f9f-fc1f5a5b0397.png)

**Comment by thaimageplaza** [comment]
Hi,
Please send me more specific error messages.
I need more information to solve your issue.
Please kindly understand. Thank you very much!
