### ISSUE TITLE
Blog Sidebar Shows After Footer

### ISSUE THREAD

**Issue by Hammadi89** [mageplaza/magento-2-blog#150]
Blog Sidebar shows at the bottom of the page, and my theme sidebar appear on right, and there is no options in theme to disable that sidebar. kindly help me!

Blog Link
https://bakehouse.pk/blog.html

**Comment by ChienNguyenVP** [comment]
Hi,
To solve your issue, please unzip and replace the attached file in the path:
Mageplaza\Blog\view\frontend\layout\mpblog_design.xml
If your problem still occurs, please let me know. I will continue to help you solve it.
Have a nice day!
[mpblog_design.zip](https://github.com/mageplaza/magento-2-blog/files/2533276/mpblog_design.zip)

**Comment by Hammadi89** [comment]
I will try it and let you know if the issue resolve

Thank you for your support

Regards,
Hammad Ali
