### ISSUE TITLE
Import from WP not working

### ISSUE THREAD

**Issue by bigshusha** [mageplaza/magento-2-blog#152]
Import not working
### Preconditions

1. Magento: 2.2.6
2. PHP: PHP Version 7.0.30-0+deb9u1
3. MySQL: 10.1.26-MariaDB-0+deb9u1
4. 
### Steps to reproduce

1. Clear install
2. complete all settings
3. try to import from WP
---Connect successfully. To start import process press "Import" button---
pressing "Import"

### Expected result

1. Wait for import

### Actual result

1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/10991213/47910250-ec902680-de9a-11e8-84d7-ed9a94294a9f.png)

---A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.---

deploy, compile, reindex, clear all this i done

**Comment by bigshusha** [comment]
When I try to add post I get this
![image](https://user-images.githubusercontent.com/10991213/47910916-e8fd9f00-de9c-11e8-857a-bc489d0848e9.png)

**Comment by LongJackson** [comment]
Hi,
I'm sorry to hear your issue.
The solution on this thread may fix it up https://github.com/mageplaza/magento-2-blog/issues/134.
If the problem insists, feel free to keep in touch.

**Comment by bigshusha** [comment]
This solution is not fix any bug.

**Comment by thaimageplaza** [comment]
Hi,
I have updated some function in the file Category.php.
The path: Mageplaza\Blog\Model\ResourceModel\Category.php
[Category.zip](https://github.com/mageplaza/magento-2-blog/files/2547618/Category.zip)
Please unzip and replace it.
If your problem still occurs, I need more information.
So please contact me at https://mageplaza.freshdesk.com/support/home. 
I will continue to help you solve it.
Thank you!
