### ISSUE TITLE
Blank page afther updating to M2.2.7

### ISSUE THREAD

**Issue by CompleteWebwinkels** [mageplaza/magento-2-blog#156]
1. Magento: 2.2.7
2. PHP: 7.1.24
3. MySQL: 10.1.37

### Afther upgrading to M2.2.7 with composer faq landing page gives a blank screen. ###
See https://dev.completebeveiliging.nl/blog.html/

Author information also gives 404.. This author no longer exists. Please create the post to access the author management session.

Thank's in advanced, Edwin

**Comment by thaimageplaza** [comment]
Hi Edwin,
To solved, you can re-save in Blog configuration.
Or you can refer in link: 
https://github.com/mageplaza/magento-2-blog/commit/7db7a7229c12d7fa6dd76c4bcccad01b911fbea4
Please check again. Thank you!

**Comment by CompleteWebwinkels** [comment]
@thaimageplaza Sorry didn't work, afther unstalling, removing vendor files and instaled with composer.
Afther unchecking every default in storeview it's working now, and all the old posted blogs are back 👍 

https://completebeveiliging.nl/blog.html
