### ISSUE TITLE
Magento 2.3 zend problem

### ISSUE THREAD

**Issue by michelecanal** [mageplaza/magento-2-blog#158]
### Preconditions
1. Magento: 2.3
2. PHP: 7.1

### Steps to reproduce
1. access to [site]/blog/post/rss.xml

### Expected result

1.  Rss list

### Actual result
Error:
Invalid parameter: parameter must be a non-empty string","1":"#0 [...]/vendor\/zendframework\/zend-feed\/src\/Writer\/FeedFactory.php(53)

**Comment by thaimageplaza** [comment]
Hi Michel,
Thank you for contact our.
To fix your issue, please replace the attach file in path: Mageplaza/Blog/Block/Post/Rss/Lists.php
Please check again. Thank you!
[Lists.zip](https://github.com/mageplaza/magento-2-blog/files/2701979/Lists.zip)
