### ISSUE TITLE
Since install extension blog now my site-configuration doesn't work

### ISSUE THREAD

**Issue by FireSnow2019** [mageplaza/magento-2-blog#159]
Since we installed this blog extension developed( by mageplaza) we are getting errors in accessing magento (Store>Configuration) error

Notice: Undefined index: id in /home/Magento2/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line **63**

What should i do?

Thank you

**Comment by thaimageplaza** [comment]
Hi,
To solve your issue, please re-install the Blog extension.
If your problem still occurs, please let me know. 
I will continue to help you solve it.
Thank you!

**Comment by thaimageplaza** [comment]
Hi,
Since there is no issue left, I will close this Issue now.
Thank you!
