### ISSUE TITLE
Import from AW magento1

### ISSUE THREAD

**Issue by xSQL** [mageplaza/magento-2-blog#160]
### Preconditions

1. Magento: 2.3
2. PHP: 7.1
3. MySQL: 5

### Steps to reproduce

1. Import from admin AW blog for magento 1 

### Actual result

1. [Mon Dec 24 11:26:49.869191 2018] [php7:error] [pid 5661] [client 127.0.0.1:38730] PHP Fatal error:  Uncaught Error: Call to undefined method Mageplaza\\Blog\\Model\\ResourceModel\\Category::isImported() in /home/www/htdocs/tt-energy/vendor/mageplaza/magento-2-blog-extension/Model/Import/AheadWorksM1.php:407\nStack trace:\n#0 /home/www/htdocs/tt-energy/vendor/mageplaza/magento-2-blog-extension/Model/Import/AheadWorksM1.php(77): Mageplaza\\Blog\\Model\\Import\\AheadWorksM1->_importCategories(Array, Object(mysqli))\n#1 /home/www/htdocs/tt-energy/vendor/mageplaza/magento-2-blog-extension/Controller/Adminhtml/Import/Import.php(161): Mageplaza\\Blog\\Model\\Import\\AheadWorksM1->run(Array, Object(mysqli))\n#2 /home/www/htdocs/tt-energy/vendor/mageplaza/magento-2-blog-extension/Controller/Adminhtml/Import/Import.php(101): Mageplaza\\Blog\\Controller\\Adminhtml\\Import\\Import->processImport(Object(Mageplaza\\Blog\\Model\\Import\\AheadWorksM1), Array)\n#3 /home/www/htdocs/tt-energy/generated/code/Mageplaza/Blog/Controller/Adminhtml/Import/Import/Interceptor.php(24): Mageplaza\\Blog\\Controller\\Adminhtml\\Import\\Import->execute()\n#4 /home/www/h in /home/www/htdocs/tt-energy/vendor/mageplaza/magento-2-blog-extension/Model/Import/AheadWorksM1.php on line 407

**Comment by ChienNguyenVP** [comment]
Hi,
To solve your problem, please change the following file:
[Category.zip](https://github.com/mageplaza/magento-2-blog/files/2707035/Category.zip)
at the path: Mageplaza\Blog\Model\ResourceModel\Category.php
If you have any other questions, please contact me.
Thank you!

**Comment by xSQL** [comment]
@ChienNguyenVP Thank you. Its help
