### ISSUE TITLE
Unable to import posts from Wordpress

### ISSUE THREAD

**Issue by abg20knet** [mageplaza/magento-2-blog#162]
### Preconditions

1. Magento: 2.2.6
2. PHP: 7.1
3. MySQL: MariaDB 10.1
4. Better Blog: 3.0.3

### Steps to reproduce

1. Go to Admin->Content->BetterBlog->Import
2. Set Wordpress DB details
3. Click Check Connection, then Import

### Expected result

1. Import process should start

### Actual result

1. I get the error: 
`A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.`
system.log says:
`[2019-01-21 10:44:46] main.ERROR: Unable to generate url key. Please check the setting and try again. [] []`

Magento admin interface locale is Italian as Wordpress locale.
I have already replaced Category.php (#152) but it didn't solve the problem.
I also had the issued mentioned in #134 and solved it by replacing Author.php with the one provided by @thaimageplaza

**Comment by abg20knet** [comment]
> Hi,
> With your problem, you need to replace the file: [Category.zip](https://github.com/mageplaza/magento-2-blog/files/2778684/Category.zip) at the path:
> /mageplaza/magento-2-blog-extension/Model/ResourceModel/Category.php
> I hope you are satisfied with my answer.
> Have a nice day!

Sorry, i forgot to mention i already replaced that file, but it didn't solve the problem

**Comment by ChienNguyenVP** [comment]
Hi,
I'm also using Magento 226 just like you and I tried replacing Category.php.
However, I didn't have the same error.
Are you sure you have replaced the correct file and path?
Thank you!

**Comment by abg20knet** [comment]
> Hi,
> I'm also using Magento 226 just like you and I tried replacing Category.php.
> However, I didn't have the same error.
> Are you sure you have replaced the correct file and path?
> Thank you!

Yes, i replaced Author.php and Category.php in ResourceModel directory,
ran setup:upgrade, cleared compiled code, fixed permissions, etc...

The error from system.log seems to be printed out from Helper/Data.php, line 395:
`throw new LocalizedException(__('Unable to generate url key. Please check the setting and try again.'));`

**Comment by ChienNguyenVP** [comment]
Hi,
I think your problem is in WordPress.php file at the path: 
\Model\Import\WordPress.php
Can't add 'url_key' fields at the lines: 144, 298, 431.
Please check again.
If you have trouble, don't hesitate to contact us.
Thank you!

**Comment by abg20knet** [comment]
> Hi,
> I think your problem is in WordPress.php file at the path:
> \Model\Import\WordPress.php
> Can't add 'url_key' fields at the lines: 144, 298, 431.
> Please check again.
> If you have trouble, don't hesitate to contact me.
> Thank you!

I solved the issue by replacing lines 144, 298 and 431:

`'url_key'           => $post['post_name'],
                    //'url_key'           => $this->helperData->generateUrlKey($postModel->getResource(), $postModel, $post['post_name']),`

**Comment by ChienNguyenVP** [comment]
Hi,
Everything works normally again?

**Comment by abg20knet** [comment]
> Hi,
> Everything works normally again?

Yes, the import process works now, i've imported ~1400 posts succesfully

**Comment by ChienNguyenVP** [comment]
Thank you! I will close this issue now.
