### ISSUE TITLE
Set design option ( post layout ) 

### ISSUE THREAD

**Issue by krystian15** [mageplaza/magento-2-blog#166]
Hi i have problem to set layout of post ( this option is allowed? ) 

Magento : 2.3.0
Magento 2 blog : 2.6.0

**Comment by Kenny1994** [comment]
Hi krystian15,

I'm Kenny from Mageplaza.

Regarding your question, currently, you can set the design ( layout ) for each post and the option is always allowed.
Therefore, could you please tell me what is the problem in details?

I'm looking forward to hearing from you.
Thank you!

**Comment by krystian15** [comment]
@Kenny1994 I fixed this problem, thanks for message :D

**Comment by Kenny1994** [comment]
@krystian15 ok, no problem.
