### ISSUE TITLE
404 on post pages

### ISSUE THREAD

**Issue by mshYat** [mageplaza/magento-2-blog#168]
### Preconditions

1. Magento: 2.2.7
2. PHP: 7.1
3. MySQL: 5.7
4. Magento 2 Blog Extension: 3.0.4

### Steps to reproduce

1. Create post.

### Expected result

1. Normall post page.

### Actual result

1. 404 on all post pages.
![1](https://user-images.githubusercontent.com/34918349/53556336-443e5600-3b4c-11e9-9754-db5a93c2958e.PNG)

**Comment by thaimageplaza** [comment]
Hi,
To solve issue, please replace your file with attach file.
These are modified files:
Mageplaza/Blog/Controller/Post/View.php
Please check again. Thank you!
[View.zip](https://github.com/mageplaza/magento-2-blog/files/2917896/View.zip)

**Comment by mshYat** [comment]
View.zip works fine.
