### ISSUE TITLE
Want to search blog from all pages

### ISSUE THREAD

**Issue by CharanjeetE** [mageplaza/magento-2-blog#169]
I want to search the blog posts from all other pages in my site. On blog page search is working but on other pages search is not showing the blog posts results.
### Preconditions

1. Magento: 2.2
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. Search from home page not working
2. search from blog page working 
3. 

### Expected result

1. Want to search should work on home page and other pages.

### Actual result

1. [Screenshot, logs]
Only search is working on blog page.

**Comment by thaimageplaza** [comment]
Hi, 
Firstly, I truly apologize for the inconvenience.
Unfortunately, the current version has not supported this function yet. 
I'm so sorry for that. 
However, we will consider developing it in the future so please look forward to this. 
Thank you very much for your feedback.

**Comment by CharanjeetE** [comment]
May I know when you are going to release next version.


Thanks and Regards
Charanjit singh

**Comment by thaimageplaza** [comment]
Hi,
Sorry for the late reply.
Sorry to inform you that we have no plans to develop this feature yet.
However, it was saved by us and will be developed in future versions.
So please wait for this.
Thank you very much!

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.
