### ISSUE TITLE
Cannot find where to modify 2 column left

### ISSUE THREAD

**Issue by to8gal** [mageplaza/magento-2-blog#171]
### Preconditions
1. Magento: 2.2.4
2. PHP: 7.0.30
3. MySQL: Mariadb 5.16.3
4. 

### Steps to reproduce
find where in layout xml files is set 2columns-left design

### Expected result
1.  find it in NAME_MODULE_view_frontend_layout

### Actual result
all is set to 1column already but body class is still "mpblog-post-index page-layout-2columns-right" even if I delete sidebar still css give me problem

**Comment by thaimageplaza** [comment]
Hi.
Could you please explain your problem in more details/ steps by steps to replicate the problem and send me some screenshots?
Thank you in advance!

**Comment by to8gal** [comment]
Hello,  is hard to replicate or put screenshots about it, in the post index page I just need to have a 1 column layout instead of 2columns left or right.
Usually I would do that trough layout.xml files, but here all xml are set to 1column, but still I have a 2column solution on front end (actually I see you can choose it on the backend of magetno, left or right 2 columns but not 1column

**Comment by joekersh** [comment]
The '1column' part of the layout file is completely ignored, you will find the layout set in controller method e.g. Mageplaza\Blog\Controller\Post\Index from the helper function getSidebarLayout() in Mageplaza\Blog\Helper\Data

I just put a plugin after this helper function to return '1column' as a string. And it works.

Here is the plugin function:

`public function afterGetSidebarLayout()
    {
        return '1column';
    }`

**Comment by NgoDuVietHung97** [comment]
Hi,

We appreciate your feedback, the following is our solution.
Please download and replace the attached files:
[Mageplaza.zip](https://github.com/mageplaza/magento-2-blog/files/3170986/Mageplaza.zip)

1. Data.php: app/code/Mageplaza/Blog/Helper/Data.php
2. SideBarLR.php: app/code/Mageplaza/Blog/Model/Config/Source/SideBarLR.php

If you have any problem, please let us know.
Thank you!

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.

**Comment by to8gal** [comment]
I sorry, did notanswer but actually this solved the problem, can you change it to solved?!

**Comment by mashasauer** [comment]
This is fixing main blog page layout, but breaking the post layout :(
