### ISSUE TITLE
Error on frontend

### ISSUE THREAD

**Issue by Kroellie** [mageplaza/magento-2-blog#173]
Steps to reproduce:

backend: create blog post, with a tag
frontend: navigate to blog post just created
backend: delete the post
frontend: refresh the page

error with malformed SQL shows:

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE (main_table.enabled='1')' at line 2, query was: SELECT `main_table`.*, `mageplaza_blog_post_tag`.`position` FROM `mageplaza_blog_tag` AS `main_table`
 INNER JOIN `mageplaza_blog_post_tag` ON main_table.tag_id=mageplaza_blog_post_tag.tag_id AND mageplaza_blog_post_tag.post_id= WHERE (main_table.enabled='1')
Exception #1 (PDOException): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE (main_table.enabled='1')' at line 2

**Comment by NgoDuVietHung97** [comment]
Hi,
To solve your issue, you should update file Router.php.
The file path:
Mageplaza\Blog\Controller\Router.php
Here is the update file.
[Router.zip](https://github.com/mageplaza/magento-2-blog/files/3016890/Router.zip)

**Comment by Kroellie** [comment]
Resolved

**Comment by nawabamit** [comment]
Hi. I have found the same issue. As you instructions, I have updated router file. but still got the same error

**Comment by nawabamit** [comment]
https://user-images.githubusercontent.com/24496702/58780547-e3b13000-85f6-11e9-8115-a1ffa2963efb.png
please look at the issue.

**Comment by NgoDuVietHung97** [comment]
Hi @nawabamit,

I'm not sure that I can understand your problem, so please explain your problem step by step to reproduce your problem.
Then, I can help you fix it in the shortest time.
Thank you in advance!
