### ISSUE TITLE
Multistore view post

### ISSUE THREAD

**Issue by Kroellie** [mageplaza/magento-2-blog#174]
We have 3 store views with the following url setup for different languages:

1) https://www.website.com/uk
2) https://www.website.com/us
3) https://www.website.com/ca

We create a post in english for store view 1 and 2.
We create the translated post in store view 3.
The post in store view 3 is showing up correctly in the frontend with a proper page layout.
The post in view 1 and 2 however is having errors. It shows a page where the sidebar is missing, and the store's 404 page is integrated in the content of the blog post: "oops, something went wrong".
When setting that post to a single store view, the issue is gone again and the sidebar is showing.

**Comment by NgoDuVietHung97** [comment]
Hi,
To resolve your issue, please replace the file below at the path:
Mageplaza/Blog/Controller/Post/View.php
[View.zip](https://github.com/mageplaza/magento-2-blog/files/3021406/View.zip)
Thank you!

**Comment by Kroellie** [comment]
Resolved! Thanks!
