### ISSUE TITLE
Need pagination on custom posts page

### ISSUE THREAD

**Issue by CharanjeetE** [mageplaza/magento-2-blog#175]
### Preconditions

1. Magento: 2.2.2
2. PHP: 7.1
3. MySQL: 
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. Showing posts with the pagination like given in the attached image. It is better blog extension I am using.I have created a widget to show the posts on my custom page. I want to show the pagination on this page.

Please check my template file attached.

[sales.phtml.zip](https://github.com/mageplaza/magento-2-blog/files/3022025/sales.phtml.zip)

### Actual result

1. [Screenshot, logs]

**Comment by NgoDuVietHung97** [comment]
Hi,
If you want to show posts with pagination, you can update the file below at the path:

**Comment by NgoDuVietHung97** [comment]
Hi, 
If you want to show posts with the pagination, you can update 2 files below at the path:
Mageplaza\Blog\view\frontend\templates\widget\posts.phtml
Mageplaza\Blog\Block\Widget\Posts.php: Posts.php
Here is attach file: 
[Desktop.zip](https://github.com/mageplaza/magento-2-blog/files/3022320/Desktop.zip)

**Comment by CharanjeetE** [comment]
I have a lot of custom code in my file please can you change in my attached file.

**Comment by CharanjeetE** [comment]
Ok Thanks you saved my day. Thanks a lot again

**Comment by CharanjeetE** [comment]
Hi @NgoDuVietHung97,
everything is working fine but there is some issue on all pages it is showing diffrent no. of posts. But I want 12 posts on every page.

**Comment by NgoDuVietHung97** [comment]
Hi,
If you want to show 12 or any number of posts on your page, you can go back-end => Content => Better Blog => Configuration.
Here, you can see a field  'Blogs per Page Allowed Values', you can customize a number of posts on your page here.

**Comment by CharanjeetE** [comment]
This is already done but not have any effect on frontend it still showing different no. of posts on all pages.

**Comment by NgoDuVietHung97** [comment]
Have you tried clearing the cache?
You can clear the cache by on back-end, going to System => Tools => Cache Management and Flush Magento Cache.
If it still doesn't work, please let me know.
Thank you!

**Comment by CharanjeetE** [comment]
Yes already cleaned cache. But not working.

**Comment by NgoDuVietHung97** [comment]
I tried on my site and everything still works normally. 
Are you sure you have replaced the correct file in the correct path?

**Comment by CharanjeetE** [comment]
Yes I have replaced right files.

**Comment by NgoDuVietHung97** [comment]
Hi @CharanjeetE,
Sorry for the slow reply!
Has your problem been solved?

**Comment by evolvan** [comment]
Hi @NgoDuVietHung97  
Yes I have solved it by my own coding.

**Comment by NgoDuVietHung97** [comment]
Hi @evolvan,

I'm glad you solved your problem.
If you have no further questions, I will close this issue.
Have a nice day!
