### ISSUE TITLE
No security at all in comments functionality

### ISSUE THREAD

**Issue by kweij** [mageplaza/magento-2-blog#180]
First a warning: DO NOT USE the comments functionality in it's current state!

All user generated content is NOT escaped, not in de frontend and even not in the backend. I can insert javascript in a comment and it will be executed in the admin even _before_ the comment is approved. This is a mayor security risk and should be fixed through out the codebase.

**Comment by NgoDuVietHung97** [comment]
Hi @kweij,
Thanks for your feedback!
To fix these issues, you can replace these files follow the path:
\Mageplaza\Blog\Controller\Post\View.php
\Mageplaza\Blog\view\frontend\web\js\comment.js
[Mageplaza.zip](https://github.com/mageplaza/magento-2-blog/files/3083594/Mageplaza.zip)

**Comment by kweij** [comment]
Hi @NgoDuVietHung97, 

Thanks for the active reponse, but when I search I find plenty more files that print out unescaped user content, it's not only these two files. Besides, I think the fix should be implemented in the codebase and released as a new version, that way this module can be installed as designed (with composer). And I'm not just going to download and open a served zip-file, no offence.

I think MagePlaza should fix this thoroughly, until then, I refrain from using the comment functionality.

**Comment by NgoDuVietHung97** [comment]
Hi @kweij,

We have updated them on develop branch, please download and use.
You can see details at commit:
https://github.com/mageplaza/magento-2-blog/commit/ccd66c7ff50c9c4b4fccc4e84aeb6a9bec878aac

If you have any other questions, please don’t hesitate to contact me again.
Have a nice day!

**Comment by kweij** [comment]
Hi @NgoDuVietHung97 ,

The commit you reference does not contain security fixes for the XSS vector. It does not add escaping to all user content. I've also checked the develop branch, but that one does not contains escaping of user content either, so maybe the required changed aren't merged or pushed yet into develop.

**Comment by NgoDuVietHung97** [comment]
Hi @kweij,

I’m not sure that I can understand your question, so could you please explain your problem in more details to replicate the problem and send me some screenshots?

I really hope for your cooperation.
Thank you!

**Comment by kweij** [comment]
What I did, after installing the module successfully:
- I've enabled comments (using Magento, not Disqus or Facebook)
- Added the comment "<script>alert('HACKED!');</script>"
- Go to the admin to moderate the comments and see an alert pop up "HACKED!"

Then I investigated that template and other templates that render user generated content (comment, username, ...) and I noticed that most of it - if not all of it - was not escaped.

**Comment by NgoDuVietHung97** [comment]
Hi @kweij,

Like I said before, we fixed this error.
You can see more details at commit https://github.com/mageplaza/magento-2-blog/commit/ccd66c7ff50c9c4b4fccc4e84aeb6a9bec878aac or can see the change at file: 
app/code/Mageplaza/Blog/Controller/Post/View.php

You can clone blog extension on develop branch and test.
If it still isn't working, please let me know.
Have a nice day!

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.
