### ISSUE TITLE
Not possible to remove related products

### ISSUE THREAD

**Issue by tookuul-owner** [mageplaza/magento-2-blog#181]
After a post has been associated with products, it is impossible to remove all related products, there is always one remaining.

### Preconditions

1. Magento:  2.3
2. PHP: 7.2
3. MySQL:  5.7
4. Better Blog 3.0.4

### Steps to reproduce

1. Create a new post
2. Associate it with one or more products
3. Save post
4. Attempt to remove all related products
5. One related products remains and it is impossible to remove

### Expected result

1. It should be possible to remove all related products

### Actual result

1. One product always remains

**Comment by NgoDuVietHung97** [comment]
Hi,
I tried installing Magento 2.3 and expanding blog 3.0.4 and everything still works fine.

Please describe in detail this error or send me a screenshot of your error. It will help me fix your problem as quickly as possible.

Thank you!

**Comment by thaimageplaza** [comment]
Closed due to no response within 7 days.
