### ISSUE TITLE
Posts URLs are being generated on a weird way 

### ISSUE THREAD

**Issue by julianmurillo** [mageplaza/magento-2-blog#182]
For two store views (FR and EN), there have been some posts configured and created. 
Subsequently there are weird url's generated that are being submitted to Google, for instance:

https://www.XXX.org/en/blog/post/special-offer is okay, but there is also another url generated for the French store, which is basically a 404 and is reported on Google as a Submitted URL with crawl issues: https://www.XXX.org/fr/blog/post/special-offer (this last url should not be generated) 

When looking at the backend, there is only one blog created, which is the one with the url https://www.XXX.org/en/blog/post/special-offer

So every time a blog post is created for one store view, there seems to be a similar url generated for the another store view, which should not happen.

### Preconditions
1. Magento: 2.2.7
2. PHP: 7.0.33-1 (cli) (built: Feb  8 2019 10:44:27) ( NTS )
3. MySQL: Ver 14.14 Distrib 5.6.37-82.2, for debian-linux-gnu (x86_64) using  6.3

**Comment by NgoDuVietHung97** [comment]
Hi @julianmurillo,

Thanks for your response.
I have reproduced the problem and I have attached to you the patch.
Please download and replace the attached files: 
[Mageplaza.zip](https://github.com/mageplaza/magento-2-blog/files/3140596/Mageplaza.zip)


Router.php: Mageplaza\Blog\Controller\Router.php
View.php: Mageplaza\Blog\Controller\Post\View.php
Data.php: Mageplaza\Blog\Helper\Data.php

I hope you can be satisfied with these answers.
If you have any other questions, please don’t hesitate to contact me again.
Have a nice day!

**Comment by julianmurillo** [comment]
Hi @NgoDuVietHung97 

After making the adjustments I noticed that the anchor tag of the post image and the anchor tag of the post title (on the post listing page) is base_url/blog/post/test-blog-post (a 404-page), while the right post url seems to be blog/test-blog-post (this last one let see the right blog post).
Somehow /post/ Is added to the post url.

**Comment by NgoDuVietHung97** [comment]
Hi @julianmurillo,

Sorry, I send the wrong file before.
I just updated the file in the previous comment.
Please download and use them.
Thank you!

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.

**Comment by julianmurillo** [comment]
Hi,

Sorry for not commenting before, but after waiting for the Google validation, I notice that the issue is still persisting -as commented on the 2nd of May-. Can you help me further on this?

**Comment by julianmurillo** [comment]
@NgoDuVietHung97 @thaimageplaza the issue has unfortunately not been solved, after replacing the files with the new ones you've provided. The wrong url's are still saved in the sitemaps of the respective store views.

**Comment by NgoDuVietHung97** [comment]
Hi @julianmurillo,

I can not reproduce your problem on my local, so could you provide me some screenshot?
I am looking forward to hearing from you.
Thank you very much!

**Comment by julianmurillo** [comment]
Hi @NgoDuVietHung97 sure!

As you see in the screenshots; we've created a blog post with url special-offer who would only be shown on the English store view (there are two stores views -the second one is a French store view-).

So the issue is that when looking at the sitemaps of the French store view, a url has been generated as well (which is the one returning a 404-error and being crawled by Google). 

Regarding the blog posts that have been created for the French store view, their url's are also being generated in the sitemaps of the English store view.

<img width="1336" alt="Schermafbeelding 2019-06-14 om 08 41 50" src="https://user-images.githubusercontent.com/31846739/59488991-5933c080-8e81-11e9-80f1-e8627a8c6b92.png">

<img width="1337" alt="Schermafbeelding 2019-06-14 om 08 43 31" src="https://user-images.githubusercontent.com/31846739/59488992-5933c080-8e81-11e9-9c37-9f206ab751df.png">

<img width="1241" alt="Schermafbeelding 2019-06-14 om 08 43 45" src="https://user-images.githubusercontent.com/31846739/59488993-5933c080-8e81-11e9-8232-22e7cfd40ba9.png">

I hope this makes the situation more clear for you.

**Comment by NgoDuVietHung97** [comment]
Hi @julianmurillo,

Sorry for the last response.
I am checking your problem and I will notify you when it solved.
Have a nice day!

**Comment by NgoDuVietHung97** [comment]
Hi @julianmurillo,

I have checked your problem.
I think this problem isn't important. The important thing here is you access right URL and you can get the right post.
However, I will surely not to our developer to consider developing it in the further so please look forward to this.
Thank you very much for your feedback!

**Comment by julianmurillo** [comment]
Hi @NgoDuVietHung97 
This issue seems to be important to me. I understand that we can access the right URL -so we get the right post-.
However, the wrong generated URL is saved in the sitemaps, by which Google crawls it and then complains about it because it returns a 404-error. This is -therefore- bad for the rankings.

**Comment by NgoDuVietHung97** [comment]
Hi @julianmurillo,

I have a solution for this case. 
When you access the wrong URL and you can not get any post, it will redirect you to Not Found Page instead of 404-error.
Is that OK? Please let me know.
Thanks!

**Comment by bakkerpj** [comment]
Hey @NgoDuVietHung97

I think we're dancing around the core issue, which is that invalid URLs are generated for all store views and end up in the sitemap. Your suggestion is to suppress those invalid URLs afterwards. Why not fix it properly and prevent this from happening in the first place?

**Comment by NgoDuVietHung97** [comment]
Hi @bakkerpj,

You need to know, we did not generate full URL, we just generated URL-key.
When you access URL, we will trim the URL and get URL-key, then we can get the post by URL-key in database. 
For now, I think that is the best solution to solve this problem.

**Comment by NgoDuVietHung97** [comment]
Hi,

I have found the solution to this issue.
Please download and replace the attached file:

Sitemap.php: Mageplaza\Blog\Model\Sitemap.php 
[Sitemap.zip](https://github.com/mageplaza/magento-2-blog/files/3332799/Sitemap.zip)

Try this solution and let me know the result.
Thank you!

**Comment by NgoDuVietHung97** [comment]
Hi,

I have found a solution to this problem.
Please download and replace the attached file:

Sitemap.php: Mageplaza\Blog\Model\Sitemap.php
[Sitemap.zip](https://github.com/mageplaza/magento-2-blog/files/3333253/Sitemap.zip)

Try this solution and let me know the result.
Thank you!

**Comment by julianmurillo** [comment]
Hi @NgoDuVietHung97 At a first glance, this solution seems to work. I will keep you posted on our progress. 
Would you eventually include this fix in a future version of the module?

**Comment by NgoDuVietHung97** [comment]
Hi @julianmurillo,

This is a temporary solution. We have to review and improve this solution, and we will update this issue as soon as possible.
Thank you very much for your feedback!
