### ISSUE TITLE
Blogs Category, Topic and Tags are not Clickable

### ISSUE THREAD

**Issue by GaneshTIF** [mageplaza/magento-2-blog#183]
### Preconditions

1. Magento: Magento 2.3.0
2. PHP: 7.2

### Steps to reproduce

1. Create a Blog and Add a Category, Tag, Topics
2. The Category, Tag and Topic are shown on the Blogs List 
3. But the category, Tag and Topic are not Clickable to read all blogs in the category or with required Tag or on given topic

### Expected result

1. User should be able to see Blogs as per the Category, Topic Or Tag

### Actual result

1. Unable to click on the Blog Categorization by Category, Topic, or Tag

![image](https://user-images.githubusercontent.com/50449729/57452790-4fb3a900-7282-11e9-9386-d4d7d1251a29.png)

**Comment by NgoDuVietHung97** [comment]
Hi @GaneshTIF,

Thank for your response, but everything still works normally on my environment. I can still sort post by topics, tags, and categories.

Have you tried clearing the cache?
After adding a new post, you must clear the cache so the post can be displayed right on the frontend. 

You can clear the cache by the following way: 
Login to Magento Backend/System/Cache Management/Flush Magento Cache

If you have any other questions, please don’t hesitate to contact me again.
Have a nice day!

**Comment by GaneshTIF** [comment]
Hi,
I tried clearing the cache and Flushed the Magento Cache a few times as well. But the issues stays.
You can navigate to my site and check 
[dev2.tryitfirst.online/reading.htm](url)

for further reference.

Thanks
Ganesh

**Comment by NgoDuVietHung97** [comment]
Hi @GaneshTIF,

Sorry for the late reply.

The problem you encounter is just a CSS error.
Did you have some customizations in our CSS file? If so, please customize it to the original.
Thank you!

**Comment by NgoDuVietHung97** [comment]
Or you can download and replace my attached files:
[Mageplaza.zip](https://github.com/mageplaza/magento-2-blog/files/3164814/Mageplaza.zip)

1. app/code/Mageplaza/Blog/view/frontend/templates/category/widget.phtml
2. app/code/Mageplaza/Blog/view/frontend/templates/tag/widget.phtml
3. app/code/Mageplaza/Blog/view/frontend/templates/topic/widget.phtml

Thank you!

**Comment by GaneshTIF** [comment]
Hi NgoDuVietHung97
I replaced the phtml files you shared. This works good with the mobile view.

But on the Desktop view it still remains. 
I am using the Chrome Browser for the test.

Thanks
Ganesh

**Comment by NgoDuVietHung97** [comment]
Hi @GaneshTIF,

Sorry, I sent the wrong file before.
This is right attached files:
[Mageplaza.zip](https://github.com/mageplaza/magento-2-blog/files/3165951/Mageplaza.zip)

1. app/code/Mageplaza/Blog/view/frontend/templates/category/widget.phtml
2. app/code/Mageplaza/Blog/view/frontend/templates/tag/widget.phtml
3. app/code/Mageplaza/Blog/view/frontend/templates/topic/widget.phtml

You can download and replace to use them.

**Comment by GaneshTIF** [comment]
Thanks NgoDuVietHung97.
It works correctly now.

Thanks for the much needed help
