### ISSUE TITLE
I CAN'T ACTIVE MY EXTENCION

### ISSUE THREAD

**Issue by JoaoOlsenTecnico** [mageplaza/magento-2-blog#184]
Good afternoon, I'm having a problem with your blog extension, I can not activate for some reason, I put name and email click activate and the page loads but it continues without activating. Can you help me?
Magento 2.3 - v3.0.4 Blog
![image](https://user-images.githubusercontent.com/32138879/57476462-ff7e1c00-726c-11e9-8183-051212110b8d.png)

**Comment by NgoDuVietHung97** [comment]
Hi @JoaoOlsenTecnico,

Thanks for your response.
I have reproduced the problem and I have attached to you the patch.

Please download and replace the attached files:
Active.php: app/code/Mageplaza/Core/Model/Active.php

If you have any other problems, please let us know.
Thank you!

**Comment by NgoDuVietHung97** [comment]
Hi @JoaoOlsenTecnico, 

Thanks for your response.
I have reproduced the problem and I have attached to you the patch.

Please download and replace the attached files:
[Activate.zip](https://github.com/mageplaza/magento-2-blog/files/3164579/Activate.zip)
Active.php: app/code/Mageplaza/Core/Model/Active.php

If you have any other problems, please let us know.
Thank you!

**Comment by JoaoOlsenTecnico** [comment]
THANK YOU MY FRIEND!

**Comment by tomkingfisher** [comment]
I have the same issue and get the error - Email address is invalid.

We are installing this using composer, will the patch be committed to the repo package?

**Comment by NgoDuVietHung97** [comment]
Hi @tomkingfisher,

Maybe your email is not valid, you can try to enter the email again.
We just updated it on the local environment and we will update soon, so please look forward to this.
Thank you!

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.
