### ISSUE TITLE
Blog list empty despite blog entered and enabled

### ISSUE THREAD

**Issue by ttkdigital** [mageplaza/magento-2-blog#185]
### Preconditions

1. Magento: 2.3
2. PHP: 7.2.17
3. MySQL: 5.7.26
4. 

### Steps to reproduce

1. Go to the blog page - reports no posts
2. 
3. 

### Expected result

1. See a list of the current enabled blogs

### Actual result

1. http://hotbox2.cfa-uat.com/blog

**Comment by NgoDuVietHung97** [comment]
Hi @ttkdigital,

This error may be because you haven't updated publish date or you haven't cleared the cache after adding the post.

Have you tried update publish date and clearing the cache after adding the post?
If you still get the error, don't hesitate to contact me again.

Thank you!

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.
