### ISSUE TITLE
AW magento 1 import - tags with apostrophes

### ISSUE THREAD

**Issue by mattyl** [mageplaza/magento-2-blog#188]
My clients used apostrophes in their tags - this caused the import to fail
I added this line
$name = mysqli_real_escape_string($connection, $name); // smb mod to deal with apostrophes
before line 207 in Model/Import/AheadWorksM1.php
this solved the issue

**Comment by NgoDuVietHung97** [comment]
Hi @mattyl,

Thank for your feedback.
We highly appreciate any ideas, suggestions, and comment like your and consider them in our next improvement to make our product better.
Thank you very much!

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.
