### ISSUE TITLE
Error when saving blog post without an image

### ISSUE THREAD

**Issue by OvalMedia** [mageplaza/magento-2-blog#189]
### Preconditions

1. Magento: 2.2.8
2. PHP: 7.1
3. Mageplaza module version: 3.0.4

### Steps to reproduce

1. Create a blog post without image
2. Save

or...

1. Create a blog post including image
2. Save
3. Open up for editing
4. Save it again

### Expected result

1. Blog post should save the updates

### Actual result

1. Magento throws an exception "The file was not uploaded."

So basically the module always expects a new image to be attached to a post even if there already has been uploaded an image to it.

Full Exception:

Exception #0 (Exception): The file was not uploaded.
<pre>#1 Magento\MediaStorage\Model\File\Uploader->__construct('image', &Magento\MediaStorage\Helper\File\Storage\Database#0000000060cfa2ea000000004348112d#, &Magento\MediaStorage\Helper\File\Storage#0000000060cfa511000000004348112d#, &Magento\MediaStorage\Model\File\Validator\NotProtectedExtension#0000000060cfa510000000004348112d#) called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111]
#2 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\MediaSto...', array('image', &Magento\MediaStorage\Helper\File\Storage\Database#0000000060cfa2ea000000004348112d#, &Magento\MediaStorage\Helper\File\Storage#0000000060cfa511000000004348112d#, &Magento\MediaStorage\Model\File\Validator\NotProtectedExtension#0000000060cfa510000000004348112d#)) called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:108]
#3 Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\MediaSto...', array('fileId' => 'image')) called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#4 Magento\Framework\ObjectManager\ObjectManager->create('\Magento\MediaSt...', array('fileId' => 'image')) called at [generated/code/Magento/MediaStorage/Model/File/UploaderFactory.php:43]
#5 Magento\MediaStorage\Model\File\UploaderFactory->create(array('fileId' => 'image')) called at [vendor/mageplaza/module-core/Helper/Media.php:108]
#6 Mageplaza\Core\Helper\Media->uploadImage(array('author_id' => 1, 'name' => 'strgsrg', 'enabled' => 1, 'front' => 0, 'short_descriptio...' => 'srgsarg', 'post_content' => 'aregargarg', 'store_ids' => array(0), 'categories_ids' => 4, 'topics_ids' => '', 'tags_ids' => '', 'publish_date' => '5/27/2019', 'publish_time' => array(17, 25, 47), 'url_key' => '', 'meta_title' => '', 'meta_description' => '', 'meta_keywords' => '', 'meta_robots' => 'INDEX,FOLLOW'), 'image', 'post', NULL) called at [vendor/mageplaza/magento-2-blog-extension/Controller/Adminhtml/Post/Save.php:138]
#7 Mageplaza\Blog\Controller\Adminhtml\Post\Save->prepareData(&Mageplaza\Blog\Model\Post#0000000060cfa50b000000004348112d#, array('author_id' => 1, 'name' => 'strgsrg', 'enabled' => 1, 'front' => 0, 'short_descriptio...' => 'srgsarg', 'post_content' => 'aregargarg', 'store_ids' => array(0), 'categories_ids' => 4, 'topics_ids' => '', 'tags_ids' => '', 'publish_date' => '5/27/2019', 'publish_time' => array(17, 25, 47), 'url_key' => '', 'meta_title' => '', 'meta_description' => '', 'meta_keywords' => '', 'meta_robots' => 'INDEX,FOLLOW')) called at [vendor/mageplaza/magento-2-blog-extension/Controller/Adminhtml/Post/Save.php:92]
#8 Mageplaza\Blog\Controller\Adminhtml\Post\Save->execute() called at [vendor/magento/framework/App/Action/Action.php:107]
#9 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#) called at [vendor/magento/module-backend/App/AbstractAction.php:235]
#10 Magento\Backend\App\AbstractAction->dispatch(&Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#11 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#12 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#13 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor#0000000060cfa7c6000000004348112d#, &Closure#0000000060cfa7c8000000004348112d#, &Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#14 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#) called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#15 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(&Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor#0000000060cfa7c6000000004348112d#, &Closure#0000000060cfa7c8000000004348112d#, &Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#16 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#17 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#), NULL) called at [generated/code/Mageplaza/Blog/Controller/Adminhtml/Post/Save/Interceptor.php:26]
#18 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#) called at [vendor/magento/framework/App/FrontController.php:55]
#19 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#20 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#21 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#)
#22 call_user_func_array(&Closure#0000000060cfa2f6000000004348112d#, array(&Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#)) called at [vendor/m2epro/magento2-extension/Plugin/AbstractPlugin.php:34]
#23 Ess\M2ePro\Plugin\AbstractPlugin->execute('dispatch', &Magento\Framework\App\FrontController\Interceptor#0000000060cfa2c4000000004348112d#, &Closure#0000000060cfa2f6000000004348112d#, array(&Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#)) called at [vendor/m2epro/magento2-extension/Plugin/HealthStatus/Magento/Framework/App/FrontController.php:42]
#24 Ess\M2ePro\Plugin\HealthStatus\Magento\Framework\App\FrontController->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#0000000060cfa2c4000000004348112d#, &Closure#0000000060cfa2f6000000004348112d#, &Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#25 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#26 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#), array(array('mstCoreDispatch'))) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#27 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000060cfa38c000000004348112d#) called at [vendor/magento/framework/App/Http.php:136]
#28 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#29 Magento\Framework\App\Http\Interceptor->___callParent('launch', array()) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#30 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/msp/shield/Plugin/AppInterfacePlugin.php:111]
#31 MSP\Shield\Plugin\AppInterfacePlugin->aroundLaunch(&Magento\Framework\App\Http\Interceptor#0000000060cfa36b000000004348112d#, &Closure#0000000060cfa36f000000004348112d#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#32 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/msp/adminrestriction/Plugin/AppInterfacePlugin.php:134]
#33 MSP\AdminRestriction\Plugin\AppInterfacePlugin->aroundLaunch(&Magento\Framework\App\Http\Interceptor#0000000060cfa36b000000004348112d#, &Closure#0000000060cfa36f000000004348112d#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#34 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/msp/antivirus/Plugin/AppInterfacePlugin.php:104]
#35 MSP\AntiVirus\Plugin\AppInterfacePlugin->aroundLaunch(&Magento\Framework\App\Http\Interceptor#0000000060cfa36b000000004348112d#, &Closure#0000000060cfa36f000000004348112d#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#36 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#37 Magento\Framework\App\Http\Interceptor->___callPlugins('launch', array(), NULL) called at [generated/code/Magento/Framework/App/Http/Interceptor.php:26]
#38 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:257]
#39 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#0000000060cfa36b000000004348112d#) called at [pub/index.php:37]
</pre>

**Comment by Kroellie** [comment]
+1

**Comment by NgoDuVietHung97** [comment]
Hi,

Sorry for the late response.

I tried to reproduce your problem on my local but I don't get any error like yours.
This issue may be because of your Core version is out of date. So please update the Core module to the latest version.

If you still get this error, please let me know. I will help you fix it as soon as possible.
Have a nice day!

**Comment by OvalMedia** [comment]
All modules are up to date. I just upgraded to 3.0.5 but the changes in that were unrelated.
Unfortunately the error still persists.

**Comment by OvalMedia** [comment]
In vendor\mageplaza\module-core\Helper\Media.php (function uploadImage) it simply assumes if 'delete' is not set in $data that a new image has been uploaded. 

`$uploader = $this->uploaderFactory->create(['fileId' => $fileName]);`

throws an exception which is not being caught. So simply by putting that part into the following try/catch block solves the problem:
```

public function uploadImage(&$data, $fileName = 'image', $type = '', $oldImage = null)
{
	if (isset($data[$fileName]['delete']) && $data[$fileName]['delete']) {
		if ($oldImage) {
			try {
				$this->removeImage($oldImage, $type);
			} catch (Exception $e) {
				$this->_logger->critical($e->getMessage());
			}
		}
		$data['image'] = '';
	} else {
		try {
			$uploader = $this->uploaderFactory->create(['fileId' => $fileName]);
			$uploader->setAllowedExtensions(['jpg', 'jpeg', 'gif', 'png']);
			$uploader->setAllowRenameFiles(true);
			$uploader->setFilesDispersion(true);
			$uploader->setAllowCreateFolders(true);
			$path = $this->getBaseMediaPath($type);

			$image = $uploader->save(
				$this->mediaDirectory->getAbsolutePath($path)
			);

			if ($oldImage) {
				$this->removeImage($oldImage, $type);
			}

			$data['image'] = $this->_prepareFile($image['file']);
		} catch (Exception $e) {
			$data['image'] = isset($data['image']['value']) ? $data['image']['value'] : '';
		}
	}

	return $this;
}

```

**Comment by NgoDuVietHung97** [comment]
Hi @OvalMedia,

To solve your problem, please download and replace attach files:

Media.php: Mageplaza/Core/Helper/Media.php
[Media.zip](https://github.com/mageplaza/magento-2-blog/files/3231686/Media.zip)

Please check it again, you will see it work normally.

If you have any other problem, don't hesitate to contact me again.
Thank you!

**Comment by OvalMedia** [comment]
Well, this is just my proposed solution (and it works). Please update the repo. Thank you.

**Comment by NgoDuVietHung97** [comment]
Hi @OvalMedia, 

Thanks for your feedback.
We will update the repository soon.
Have a nice day!

**Comment by OvalMedia** [comment]
This issue is STILL not fixed in the current release.

**Comment by NgoDuVietHung97** [comment]
Hi @OvalMedia,

We have a better solution for this problem and we have updated it on branch "develop".
Please check the commit: https://github.com/mageplaza/magento-2-blog/commit/684fb37d849de752f886aafbbdfeedb10f26f812

We have to review this solution and we will update in the next version.
Thank you!

**Comment by OvalMedia** [comment]
Then why don't you release it? I need this for a production environment, I don't want to mess with a develop branch. Your official release is clearly broken and you keep referring to a develop branch?

**Comment by NgoDuVietHung97** [comment]
Hi @OvalMedia,

We always want customers to use the best products and services.
So, we need to check it carefully before releasing a new version.
Please look forward to this.
Thank you!

**Comment by OvalMedia** [comment]
But you DO see the irony?

**Comment by AndyJAllen** [comment]
Anyone experiencing new issues here with 2.3.2? Getting errors when trying to upload images. "File Validation Failed" and get a banner up top "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

**Comment by mjoraid** [comment]
> Hi @OvalMedia,
> 
> To solve your problem, please download and replace attach files:
> 
> Media.php: Mageplaza/Core/Helper/Media.php
> [Media.zip](https://github.com/mageplaza/magento-2-blog/files/3231686/Media.zip)
> 
> Please check it again, you will see it work normally.
> 
> If you have any other problem, don't hesitate to contact me again.
> Thank you!

Just tried your solution and replaced the media.php file. It fixed saving posts issue. Thank you.

**Comment by arumcomputer** [comment]
Why isn't the a new release? The problem is still there in the latest stable 3.0.6.
Even in the Master Branch the fix seems not to be committed.

**Comment by Bang512** [comment]
Hi @arumcomputer,

We have found a better solution for this problem and we have updated on branch master of the Blog extension.
Please download the latest version on GitHub (branch master) and you can see no errors with this version.
Thanks!

**Comment by arumcomputer** [comment]
Hi @Bang512,

and why don't you just make a new release after a version with such a big issue for over a half a year? I am using composer and it is listening to tags / releases, because in my eyes it is unsafe to use dev-master as a requirement in a production system.

**Comment by Bang512** [comment]
Hi @arumcomputer,

We have to review it carefully to make sure the issue (include this) and new features working as expected.
For now, please use the latest version on GitHub, we will release the new version as soon as possible.

Thanks for your understanding!

**Comment by parekhreena** [comment]
I have create a patch for this and generated Pull Request to merge to master branch here: https://github.com/mageplaza/module-core/pull/33
