### ISSUE TITLE
404 page on all new posts

### ISSUE THREAD

**Issue by Kroellie** [mageplaza/magento-2-blog#190]
I'm having the same issue as described in #168 again.

**Comment by Kroellie** [comment]
Upon investigation it is related to setting more than 1 storeview in the post. For example we have US and GB, when the post is selected for both shops, the 404 appears.

**Comment by NgoDuVietHung97** [comment]
Hi @Kroellie,

To solve your problem, please download and replace the attached files:

There are modified files:
Router.php: Mageplaza/Blog/Controller/Router.php
Data.php: Mageplaza/Blog/Helper/Data.php
[Mageplaza.zip](https://github.com/mageplaza/magento-2-blog/files/3230657/Mageplaza.zip)

Please check it again.
Thank you!

**Comment by Kroellie** [comment]
Unfortunately, the problem persists...

**Comment by erickamoedo** [comment]
Same problem here (http://prntscr.com/nv4dr4)

i have Magento 3.2.1 with "en_US" and  "pt_BR "


I already try replace the modified files:

- View.zip 
- Router.php: Mageplaza/Blog/Controller/Router.php
- Data.php: Mageplaza/Blog/Helper/Data.php

But Unfortunately, the problem persists too

Please somebody can help us?

**Comment by NgoDuVietHung97** [comment]
Hi,

Sorry for the late reply.

Everything still working normally on my environment. 
Could you please provide me some screenshot?
With it, I can help you fix this issue in the shortest time.

I'm looking forward to hearing from you.
Have a nice day!

**Comment by NgoDuVietHung97** [comment]
Hi,

Sorry for the late response.
I just update attached file in my comment before, so could you please download and replace them.
Then please let me know the result.
Thank you!

**Comment by Kroellie** [comment]
Sorry, still the same...

**Comment by Kroellie** [comment]
The controllername is not 'post' anymore due to #195 so case 'default' needs to be modified as well on line 159 of Router.php. However, still the issue persists.

**Comment by NgoDuVietHung97** [comment]
Hi,

I see everything still work well on my local environment, so could you please send some screenshots?
With it, I will help you fix this in the shortest time.
Thank you in advance!

**Comment by Kroellie** [comment]
sure, screenshot of post in multiple store_ids: https://prnt.sc/nvbyjb screenshot of post in single store_id: https://prnt.sc/nvbyqp

**Comment by NgoDuVietHung97** [comment]
Hi @Kroellie,

Please let me know your URL when you access the post. I need to know this is correctly URL or not.
Thank you!

**Comment by erickamoedo** [comment]
Hi,

i get "ERR_TOO_MANY_REDIRECTS", maybe it's because a timeout?

http://prntscr.com/nvfr7e

this error is just for new posts

**Comment by erickamoedo** [comment]
PS: is my first time with Btter Blog MagePlaza

**Comment by Kroellie** [comment]
Erickamoedo has a different issue. Mine is showing on this page: https://powerball.shop:8443/nl/kennis/powerball-fabrikanten

**Comment by NgoDuVietHung97** [comment]
Hi @erickamoedo,

You can see the solution to your issues here: 
https://github.com/mageplaza/magento-2-blog/issues/170

If you have any other problem, please let me know.
Have a nice day!

**Comment by NgoDuVietHung97** [comment]
Hi @Kroellie,

Please download and replace the attached file:
View.php: Mageplaza/Blog/Controller/Post/View.php
[View.zip](https://github.com/mageplaza/magento-2-blog/files/3239488/View.zip)

If it still doesn't work normally, please don't hesitate to contact me again.
Thank you!

**Comment by Kroellie** [comment]
:( PHP message: PHP Fatal error:  Cannot declare class Mageplaza\Blog\Controller\Post\View, because the name is already in use in /var/www/site/vendor/mageplaza/magento-2-blog-extension/view/frontend/templates/post/view.phtml on line 0" while reading response header from upstream

**Comment by Kroellie** [comment]
+1 fixed!
