### ISSUE TITLE
blank.html is being downloaded upon category edit

### ISSUE THREAD

**Issue by Kroellie** [mageplaza/magento-2-blog#191]
When going to the categories submenu under content menu, upon loading the page, a file called blank.html is being downloaded. This comes from an iframe included in view/adminhtml/templates/category/edit/form.phtml.

**Comment by NgoDuVietHung97** [comment]
Hi @Kroellie,

To solve this issue, you can download and replace the attached file:

form.phtml: Mageplaza/view/adminhtml/templates/category/edit/form.phtml
[form.zip](https://github.com/mageplaza/magento-2-blog/files/3230716/form.zip)

I hope you satisfied with my answers.
If you have any problem, please contact me via this issue.
Thank you!
