### ISSUE TITLE
styling of view.phtml is wrong

### ISSUE THREAD

**Issue by Kroellie** [mageplaza/magento-2-blog#192]
Viewing a post on the frontend, I notice related posts placed to the right of the post itself. Upon investigation this is related to the following code in view.phtml:

post-list-content col-md-9 col-sm-8

Why is there a mention of col-md and col-sm? And if this is relevant where are the col-md-3 and col-sm-4 entries?

When I remove the col-md-9 col-sm-8 part, the page looks... ok-ish.

**Comment by NgoDuVietHung97** [comment]
Hi @Kroellie,

Thanks for contacting us!

Class col-md and col-sm allow websites to be compatible with many different screen sizes. 
So if you remove class col-md-9 and col-sm-8, with the screen size of the desktop, it will be work normally, but with a screen size smaller, the web page will be broken.
Therefore, class col-md-9 and col-sm-8 are necessary.

I hope you can be satisfied with my answer. 
If you have any other question, please don't hesitate to contact me again.
Have a nice day!
