### ISSUE TITLE
No possibility to disable RSS feed

### ISSUE THREAD

**Issue by Kroellie** [mageplaza/magento-2-blog#193]
Please have the feature RSS toggle on/off present.

**Comment by NgoDuVietHung97** [comment]
Hi @Kroellie,

Firstly, I truly apologize for the inconvenience.

Unfortunately, the current version has not supported this function yet. I'm so sorry about that.
However, I had custom this feature for you, so please download and replace these file to use this feature.
[Mageplaza.zip](https://github.com/mageplaza/magento-2-blog/files/3230456/Mageplaza.zip)

Here is the path:
config.xml: app/code/Mageplaza/Blog/etc/config.xml
Frontend.php: app/code/Mageplaza/Blog/Block/Frontend.php
list.phtml: app/code/Mageplaza/Blog/view/frontend/templates/post/list.phtml
system.xml: app/code/Mageplaza/Blog/etc/adminhtml/system.xml

About this feature, I will surely note it to our developer to consider developing it in the future so please look forward to this. 
Thank you very much for your feedback.

**Comment by jensruegge** [comment]
No update on this ?
The RSS feed option is still not deactivatable, after 3 years!

**Comment by jensruegge** [comment]
Can I please also get this customized solution?
