### ISSUE TITLE
Frontpage contains all blog posts

### ISSUE THREAD

**Issue by Kroellie** [mageplaza/magento-2-blog#196]
It would be nice to be able to select some blog posts to be shown on the frontpage of the blog. Now ALL blog posts are shown, looks a bit messy.

**Comment by NgoDuVietHung97** [comment]
Hi @Kroellie,

Firstly, I truly apologize for the inconvenience.

Unfortunately, the current version has not supported this function yet. I'm so sorry about that. 
However, I will surely note it to consider developing it in the future so please look forward to this. 

Thank you very much for your feedback!

**Comment by Kroellie** [comment]
No problem, it would improve your product though... take it on your roadmap.
