### ISSUE TITLE
The file was not uploaded

### ISSUE THREAD

**Issue by swtrustly** [mageplaza/magento-2-blog#197]
### Preconditions
Upgraded server from 2.2.3 to 2.2.8 and blog posts can't be saved anymore. 
1. Magento: 2.2.8 
2. PHP: 7.0
3. All file permissions are good, full rights in pub/

### Expected result

1. Blog post should be saved. 

### Actual result
Save throws an error.
Blog post is not changed.

Note. Product editing still works as expected, even with big images added. So it doesn't seem to be a fileinfo or file size problem.

{"0":"The file was not uploaded.","1":"<pre>#1 Magento\\MediaStorage\\Model\\File\\Uploader->__construct() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:111]\n#2 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:108]\n#3 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:56]\n#4 Magento\\Framework\\ObjectManager\\ObjectManager->create() called at [generated\/code\/Magento\/MediaStorage\/Model\/File\/UploaderFactory.php:43]\n#5 Magento\\MediaStorage\\Model\\File\\UploaderFactory->create() called at [vendor\/mageplaza\/module-core\/Helper\/Media.php:108]\n#6 Mageplaza\\Core\\Helper\\Media->uploadImage() called at [app\/code\/Mageplaza\/Blog\/Controller\/Adminhtml\/Post\/Save.php:135]\n#7 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save->prepareData() called at [app\/code\/Mageplaza\/Blog\/Controller\/Adminhtml\/Post\/Save.php:90]\n#8 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:107]\n#9 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:235]\n#10 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#11 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#12 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]\n#13 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#14 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#15 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->___callPlugins() called at [generated\/code\/Mageplaza\/Blog\/Controller\/Adminhtml\/Post\/Save\/Interceptor.php:26]\n#16 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:55]\n#17 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#18 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#19 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [app\/code\/Infortis\/Cgen\/Plugin\/Magento\/Framework\/App\/FrontController.php:32]\n#20 Infortis\\Cgen\\Plugin\\Magento\\Framework\\App\\FrontController->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#21 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#22 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#23 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:136]\n#24 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:257]\n#25 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:37]\n<\/pre>","url":"\/whitewaterAdmin\/mageplaza_blog\/post\/save\/id\/10\/key\/940dd3fdf4ae658c988d49cc2ca0a2310b8a21dbbd637ad600a3eae1bc396b17\/active_tab\/post\/","script_name":"\/index.php"}

**Comment by NgoDuVietHung97** [comment]
Hi @swtrustly,

To solve your problem, you need to download and replace Media.php file following the path:
Mageplaza/Core/Helper/Media.php.

You can see more detail at issue https://github.com/mageplaza/magento-2-blog/issues/189
If you have any other problem, please let me know, I will help you fix it as soon as possible.
Have a nice day!

**Comment by swtrustly** [comment]
> Hi @swtrustly,
> 
> To solve your problem, you need to download and replace Media.php file following the path:
> Mageplaza/Core/Helper/Media.php.

It seems we have the core module in the vendor folder so I did an ugly fix right there and replaced the file in module-core. Should I be worried that this error comes back with next update?
module-core seems to be upgraded recently.

**Comment by NgoDuVietHung97** [comment]
Hi @swtrustly,

We will fix it in the next version of core-module, so don't worry about that.
The thing to do now is to make everything work normally.
Does the Blog Extension work normally? Please let me know the result.
Thank you!

**Comment by swtrustly** [comment]
Yes, it fixed the issue! Fast response, much appreciated. :)

**Comment by parekhreena** [comment]
I have created a patch for this and generated Pull Request to merge to master branch here: https://github.com/mageplaza/module-core/pull/33
