### ISSUE TITLE
Suggestion for date format

### ISSUE THREAD

**Issue by OvalMedia** [mageplaza/magento-2-blog#198]
The module comes with a list of predefined date formats. I am missing the common format in germany: 'd.m.Y'.

So it would be nice if we optionally could inject a custom format from the template like this:

`$block->getDateFormat($post->getPublishDate(), false, 'd.m.Y');
`

Changes needed:

\Block\Frontend.php:

```
public function getDateFormat($date, $monthly = false, $dateType = false)
{
	return $this->helperData->getDateFormat($date, $monthly, $dateType);
}
```
\Helper\Data.php:

```
public function getDateFormat($date, $monthly = false, $dateType = false)
{
	$dateTime = (new \DateTime($date, new \DateTimeZone('UTC')));
	$dateTime->setTimezone(new \DateTimeZone($this->getTimezone()));

	if (!$dateType) {
		$dateType = $this->getBlogConfig($monthly ? 'monthly_archive/date_type_monthly' : 'general/date_type');
	}
	$dateFormat = $dateTime->format($dateType);

	return $dateFormat;
}
```

**Comment by NgoDuVietHung97** [comment]
Hi @OvalMedia,

Thanks for your feedback.
About your problem you mentioned, I think it's a necessary edition for our Blog Extension and we will update this in the next version.

We highly appreciate any ideas, suggestion, and comment like yours and consider them in our next improvement to make our product better.

Thank you very much!

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.
