### ISSUE TITLE
Fatal error: Class AbstractData app\code\Mageplaza\Blog\Helper\Data.php on line 42

### ISSUE THREAD

**Issue by Gagan557** [mageplaza/magento-2-blog#199]
Preconditions
Magento: 2.1.17
PHP:
MySQL:

Actual result
Fatal error: Class 'Mageplaza\Core\Helper\AbstractData' not found in C:\wamp64\www\njdr\app\code\Mageplaza\Blog\Helper\Data.php on line 42
![Screenshot (212)](https://user-images.githubusercontent.com/35591297/58624867-d6423000-82ee-11e9-9fde-77e1a7594f32.png)

**Comment by NgoDuVietHung97** [comment]
Hi @Gagan557,

I’m not sure that I can understand your issue, so could you please explain your problem steps by steps to replicate the problem?
I really hope for your cooperation. 
Thank you!
