### ISSUE TITLE
This extension is not actived show Better blog

### ISSUE THREAD

**Issue by Gagan557** [mageplaza/magento-2-blog#200]
### Preconditions

1. Magento: 2.1.17
2. PHP: 
3. MySQL: 

### Steps to reproduce

1.  
2. 
3. 

### Expected result

1. 

### Actual result

I also installed Magento core extension but show same error. This extension is not activated
1. [Screenshot, logs]
![Screenshot (214)](https://user-images.githubusercontent.com/35591297/58699231-a1031400-83ba-11e9-9b52-37c5f51b13da.png)

**Comment by NgoDuVietHung97** [comment]
Hi @Gagan557,

To solve your problem, please download and replace file I have attached:

config.xml
[config.zip](https://github.com/mageplaza/magento-2-blog/files/3240879/config.zip)

Then, please clean the cache and let me know the result.
Have a nice day!

**Comment by Gagan557** [comment]
This error is solved but no options show to update blog post in Content 
![Screenshot (215)](https://user-images.githubusercontent.com/35591297/58700933-2688c300-83bf-11e9-92f1-95b61d8ded20.png)

**Comment by NgoDuVietHung97** [comment]
Hi @Gagan557,

Can you see menu Mageplaza on the left? Click it and you can see all our extension.
Thank you!

**Comment by Gagan557** [comment]
Yes  extension is installed but no option show to add blog post in content section

**Comment by thaimageplaza** [comment]
Hi @Gagan557 
Please make sure the Blog extension has been successfully installed.
You can find the extension in "CONTENT->Better Blog"
https://i.imgur.com/MfwltlT.png
Or "MAGEPLAZA->Better Blog"
https://i.imgur.com/D0fDpcp.png

Please check again. Thank you!

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.
