### ISSUE TITLE
No widget for sidebar

### ISSUE THREAD

**Issue by Kroellie** [mageplaza/magento-2-blog#201]
It would be great if we could place the 'most read' and 'latest' sidebar block as a widget in M2.

**Comment by thaimageplaza** [comment]
Hi @Kroellie 
Thank you for contacting us.
Unfortunately, the current version has not supported this function yet. 
I'm so sorry for that. 

However, I will surely note it to our developer to consider about developing it in the future so please look forward to this. 
Thank you very much for your feedback.
