### ISSUE TITLE
Something went wrong while saving the Post.

### ISSUE THREAD

**Issue by Teerree4** [mageplaza/magento-2-blog#202]
### Preconditions

1. Magento: 2.2.6
2. PHP: 7.2 

### Steps to reproduce

1. Create a Post 
2. Save Post

### Expected result

1. The post is created without problems.

### Actual result

1. Something went wrong while saving the Post.
2. This post no longer exists.

As a theme I use last, but I don't seem able to be able to create the post.
Any idea on the kind of error?

**Comment by NgoDuVietHung97** [comment]
Hi @Teerree4,

I have reproduced your problem in my local environment.
To solve your problem, please download and replace the attached file:

Image.php: Mageplaza/Blog/Helper/Image.php
[Image.zip](https://github.com/mageplaza/magento-2-blog/files/3247042/Image.zip)

If you have any problem, please let me know.
Thank you!

**Comment by Teerree4** [comment]
Hello! I uploaded the file, but unfortunately nothing has changed. I checked in the logs and it gives me this error.

`[2019-06-03 10:22:49] main.CRITICAL: Exception message: DateTime::__construct(): Failed to parse time string (03/giu/2019 10:22:49) at position 0 (0): Unexpected character
Trace: #0 /var/www/beta/vendor/magento/framework/Stdlib/DateTime.php(57): DateTime->__construct('03/giu/2019 10:...')
#1 /var/www/beta/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(2802): Magento\Framework\Stdlib\DateTime->formatDate(Object(Zend_Date), true)
#2 /var/www/beta/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(3030): Magento\Framework\DB\Adapter\Pdo\Mysql->formatDate(Object(Zend_Date))
#3 /var/www/beta/vendor/magento/framework/Model/ResourceModel/AbstractResource.php(183): Magento\Framework\DB\Adapter\Pdo\Mysql->prepareColumnValue(Array, Object(Zend_Date))
#4 /var/www/beta/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(541): Magento\Framework\Model\ResourceModel\AbstractResource->_prepareDataForTable(Object(Mageplaza\Blog\Model\Author), 'mageplaza_blog_...')
#5 /var/www/beta/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(817): Magento\Framework\Model\ResourceModel\Db\AbstractDb->_prepareDataForSave(Object(Mageplaza\Blog\Model\Author))
#6 /var/www/beta/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(413): Magento\Framework\Model\ResourceModel\Db\AbstractDb->updateObject(Object(Mageplaza\Blog\Model\Author))
#7 /var/www/beta/vendor/magento/framework/Model/AbstractModel.php(647): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Mageplaza\Blog\Model\Author))
#8 /var/www/beta/vendor/mageplaza/magento-2-blog-extension/Model/ResourceModel/Post.php(523): Magento\Framework\Model\AbstractModel->save()
#9 /var/www/beta/vendor/mageplaza/magento-2-blog-extension/Model/ResourceModel/Post.php(184): Mageplaza\Blog\Model\ResourceModel\Post->saveAuthor()
#10 /var/www/beta/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(831): Mageplaza\Blog\Model\ResourceModel\Post->_afterSave(Object(Mageplaza\Blog\Model\Post))
#11 /var/www/beta/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(418): Magento\Framework\Model\ResourceModel\Db\AbstractDb->processAfterSaves(Object(Mageplaza\Blog\Model\Post))
#12 /var/www/beta/vendor/magento/framework/Model/AbstractModel.php(647): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Mageplaza\Blog\Model\Post))
#13 /var/www/beta/vendor/mageplaza/magento-2-blog-extension/Controller/Adminhtml/Post/Save.php(97): Magento\Framework\Model\AbstractModel->save()
#14 /var/www/beta/generated/code/Mageplaza/Blog/Controller/Adminhtml/Post/Save/Interceptor.php(24): Mageplaza\Blog\Controller\Adminhtml\Post\Save->execute()
#15 /var/www/beta/vendor/magento/framework/App/Action/Action.php(107): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->execute()
#16 /var/www/beta/vendor/magento/module-backend/App/AbstractAction.php(235): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /var/www/beta/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /var/www/beta/vendor/magento/framework/Interception/Interceptor.php(138): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callParent('dispatch', Array)
#19 /var/www/beta/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /var/www/beta/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /var/www/beta/vendor/magento/framework/Interception/Interceptor.php(153): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#22 /var/www/beta/generated/code/Mageplaza/Blog/Controller/Adminhtml/Post/Save/Interceptor.php(39): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callPlugins('dispatch', Array, NULL)
#23 /var/www/beta/vendor/magento/framework/App/FrontController.php(55): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /var/www/beta/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /var/www/beta/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#26 /var/www/beta/.modman/Ultimo/app/code/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php(32): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /var/www/beta/vendor/magento/framework/Interception/Interceptor.php(135): Infortis\Cgen\Plugin\Magento\Framework\App\FrontController->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /var/www/beta/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#29 /var/www/beta/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#30 /var/www/beta/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#31 /var/www/beta/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#32 /var/www/beta/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http\Interceptor->launch()
#33 /var/www/beta/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#34 {main} [] []
`

**Comment by NgoDuVietHung97** [comment]
Hi @Teerree4,

This error occurs due to timezone different in many different locations.
To solve this error, you can download and replace the attached file:

Author.php: Mageplaza/Blog/Model/ResourceModel/Author.php
[Author.zip](https://github.com/mageplaza/magento-2-blog/files/3247105/Author.zip)

Thank you!

**Comment by Teerree4** [comment]
Magnificent, it worked perfectly. Thank you so much!

**Comment by NgoDuVietHung97** [comment]
Hi @Teerree4,

If there are any other problems arising, please feel free to let us know.
We always ready to solve them for you.
Have a nice day!
