### ISSUE TITLE
Saving Post with no image fails

### ISSUE THREAD

**Issue by espressobytes** [mageplaza/magento-2-blog#203]
### Preconditions

1. Magento: 2.3.1
2. PHP: 7.2.16
3. MySQL: 5.7.25
4. Mageplaza Blog Extension: Version 3.0.5 

### Steps to reproduce

1. Install Mageplaza Blog Extension via composer
2. Activate Extension in Magento-Configuration
3. In Magento-Admin Navigate to Content -> Manage Posts
4. Click on Add New Post
5. Type in Title, Description and some content but **upload no image**
6. Click on Save

(btw: it doesn't matter if you're in developer or production mode) 

### Expected result

1. The blog post should be saved

### Actual result

1. An Exception occurred:

`{"0":"The file was not uploaded.","1":"<pre>#1 Magento\\MediaStorage\\Model\\File\\Uploader->__construct() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:116]\n#2 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:108]\n#3 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:56]\n#4 Magento\\Framework\\ObjectManager\\ObjectManager->create() called at [generated\/code\/Magento\/MediaStorage\/Model\/File\/UploaderFactory.php:43]\n#5 Magento\\MediaStorage\\Model\\File\\UploaderFactory->create() called at [vendor\/mageplaza\/module-core\/Helper\/Media.php:108]\n#6 Mageplaza\\Core\\Helper\\Media->uploadImage() called at [vendor\/mageplaza\/magento-2-blog-extension\/Controller\/Adminhtml\/Post\/Save.php:138]\n#7 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save->prepareData() called at [vendor\/mageplaza\/magento-2-blog-extension\/Controller\/Adminhtml\/Post\/Save.php:92]\n#8 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#9 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:231]\n#10 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#11 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#12 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]\n#13 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#14 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#15 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->___callPlugins() called at [generated\/code\/Mageplaza\/Blog\/Controller\/Adminhtml\/Post\/Save\/Interceptor.php:26]\n#16 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#17 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#18 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#19 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#20 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#21 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#22 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:136]\n#23 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:258]\n#24 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:40]\n<\/pre>","url":"\/admin_SHACO\/mpblog\/post\/save\/key\/74d548cb08bdc253795125d9b38d2b4b8a1873781544733fe4323a8272027fb5\/active_tab\/post\/","script_name":"\/index.php"}`

I can save a blog post without image. But that only works the following way:
1. Add a post with an arbitrary image. Save that
2. Open that post and delete the image. Save
Now the blog has no image

**Comment by anthonyg900** [comment]
I am experiencing the same issue on:

- Mageplaza Blog Extension: Version 3.0.5
- Magento Version: 2.2.1

**Comment by NgoDuVietHung97** [comment]
Hi,

To solve your problem, you just need to download and replace file Image.php.
You can see more details at issue https://github.com/mageplaza/magento-2-blog/issues/202
If you have any other problem, don't hesitate to contact me again.
Have a nice day!

**Comment by espressobytes** [comment]
@NgoDuVietHung97 
Thanks a lot. It works! :-)
Since we prefer installation of Extensions via composer:
Are you going to correct that in the repo? (I created a pull request for it: https://github.com/mageplaza/magento-2-blog/pull/204)
Otherwise I would have to create a patch.

**Comment by NgoDuVietHung97** [comment]
Hi @espressobytes,

Firstly, I'm so sorry about this inconvenience.
We will fix this in the next version of Blog Extension and we will release the new version soon, so please look forward this.
Thank you for your understanding!

**Comment by higi90** [comment]
> Hi @espressobytes,
> 
> Firstly, I'm so sorry about this inconvenience.
> We will fix this in the next version of Blog Extension and we will release the new version soon, so please look forward this.
> Thank you for your understanding!

Thank you @NgoDuVietHung97, we are also waiting for new release.

**Comment by NgoDuVietHung97** [comment]
Hi,

We have found a better solution to this problem.
Please check to commit https://github.com/mageplaza/magento-2-blog/commit/97d4798b4c481c54f6df5798572b7cba6a0a7546
We have updated it on branch "develop" and we will update this on branch master soon.
Thanks!

**Comment by wagento** [comment]
I am getting this error as well. Can you push your change?

**Comment by NgoDuVietHung97** [comment]
Hi @wagento,

We have found a better solution for this issue, please check commit:
https://github.com/mageplaza/magento-2-blog/commit/684fb37d849de752f886aafbbdfeedb10f26f812
We will update and release a new version soon, so please look forward to this.
Thank you very much!

**Comment by wagento** [comment]
It would be great to get this in composer. (It will only take a second to merge)

**Comment by NgoDuVietHung97** [comment]
Hi @wagento,

This is just a temporary solution, we have to review and improve this solution.
We will update this issue as soon as possible.
Thanks so much for your contribution!

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.

**Comment by higi90** [comment]
Hello @thaimageplaza,

when can we expect merge and release of https://github.com/mageplaza/magento-2-blog/commit/684fb37d849de752f886aafbbdfeedb10f26f812  ?

**Comment by dexterofcodex** [comment]
Issue still present in version 3.0.6

Is there an ETA for the fix?

**Comment by NgoDuVietHung97** [comment]
Hi @dexterofcodex,

We have updated on the branch "develop" and we will release a new version as soon as possible.
So, please look forward to this.
Thank you!

**Comment by dexterofcodex** [comment]
@NgoDuVietHung97  thanks!

**Comment by jwktje** [comment]
This still happens today
