### ISSUE TITLE
Not possible to "translate" blog

### ISSUE THREAD

**Issue by rdk-pmis** [mageplaza/magento-2-blog#207]
### Preconditions

1. Magento: 2.2.8
2. PHP: 7.1
3. MySQL: MariaDb 10.1.40
4. 

### Steps to reproduce

1. Make a blog and remember the url key
2. Set the store view to a specific store view
3. Save the blog
4. Make a new blog using the same url key
5. Set the store view to a different one than the first blog

### Expected result

1.  Blog should be saved using the same url key

### Actual result

1. Blog gets saved with a unique url key based on the one you filled in

**Comment by NgoDuVietHung97** [comment]
Hi @rdk-pmis,

To solve this problem, please download and replace the attached file following the path:
Data.php: Mageplaza\Blog\Helper\Data.php
[Data.zip](https://github.com/mageplaza/magento-2-blog/files/3337352/Data.zip)

If you have any other problem, please let me know.
Thank you!

**Comment by rdk-pmis** [comment]
This doesn't completely solve the issue. The both get saved with the same URL key, however when I switch store views I still end up with a 404 page. Even when I go from list view in the second store view to the post I get a 404 page. Database shows both have been saved under the same url key.

**Comment by NgoDuVietHung97** [comment]
Hi @rdk-pmis,

Please download and replace the attached files:
 - Data.php: Mageplaza\Blog\Helper\Data.php
 - Router.php: Mageplaza\Blog\Controller\Router.php
[Mageplaza.zip](https://github.com/mageplaza/magento-2-blog/files/3337950/Mageplaza.zip)

Try it and let me know the result.
Thank you!

**Comment by rdk-pmis** [comment]
The issue isn't solved. I tried if it helped when I set Add Store Id to URL to yes, but that doesn't solve it either. I always get a 404.

**Comment by NgoDuVietHung97** [comment]
Hi @rdk-pmis,

I am checking this problem and I will notify you soon.
Thank you!

**Comment by NgoDuVietHung97** [comment]
Hi @rdk-pmis,

I have updated the attached file, please download and use them.
And don't forget to set the option "Add store code to URL" to "Yes".
Thank you!

**Comment by rdk-pmis** [comment]
I didn't set "Add store code to URL" to "Yes" and it already works.
Please make sure these changes also make their way into the official releases, since we use composer to install the blog extension and with any future updates these fixes would be lost again.

**Comment by NgoDuVietHung97** [comment]
Hi @rdk-pmis,

This is just a temporary solution.
We have to review and improve this solution, and we will update this as soon as possible.
Thank you very much for your feedback!

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.

**Comment by rdk-pmis** [comment]
> Closed due no response within 7 days.

Who should respond? As far as I know a permanent solution was still needed.

**Comment by KaiRo-at** [comment]
Yes, this is still an issue in current versions.
