### ISSUE TITLE
Is it possible to add sort / place of "Related posts" under product to be #2 ?

### ISSUE THREAD

**Issue by RoyWilliam** [mageplaza/magento-2-blog#208]
### Preconditions

1. Magento: 2.3.2
2. PHP: 7.2

I want "Detail" to be #1 - and then "Related posts" #2

Thanx

**Comment by NgoDuVietHung97** [comment]
Hi @RoyWilliam,

I'm not sure I can understand your problem.
Could you please explain your problem step by step/in more details to reproduce this problem and send me some screenshot?

Thank you in advance!

**Comment by RoyWilliam** [comment]
It's not a problem/issue - but a small change or update
![Skjermbilde 2019-07-04 kl  12 15 26](https://user-images.githubusercontent.com/13084846/60659426-ab9b4800-9e55-11e9-8f5b-36045757c961.png)

**Comment by NgoDuVietHung97** [comment]
Hi @RoyWilliam,

To customize this, you just need to download and replace the attached file:
 - catalog_product_view: Mageplaza/Blog/view/frontend/layout/catalog_product_view
[catalog_product_view.zip](https://github.com/mageplaza/magento-2-blog/files/3358879/catalog_product_view.zip)

Then, please clear the cache. You will see the "Related Product" at the next tab as you want.
Thank you!

**Comment by RoyWilliam** [comment]
Hmmm
It worked.
Thanx!

**Comment by RoyWilliam** [comment]
Now run mageplaza/magento-2-blog-extension 3.1.2 (Not working properly)
It seams like I need a new version of «catalog_product_view» 

Magento 2.3.4-p2
php7.3
Ubuntu 18.04.5
