### ISSUE TITLE
failed to parse date string

### ISSUE THREAD

**Issue by weizhilee** [mageplaza/magento-2-blog#209]
### Preconditions

1. Magento: 2.3.2
2. PHP: 7.2.17
3. MySQL: 5.7
4. Tue, 09 Jul 2019 10:12:44 +0800
UTC=false

### Steps to reproduce

1. save Post
2. 
3. 

### Expected result

1. post save success

### Actual result

1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/42196134/60854121-abbe8d80-a231-11e9-8323-f429571fe9f6.png)

[2019-07-09 02:03:55] main.CRITICAL: Exception message: DateTime::__construct(): Failed to parse time string (2019年7月9日 上午2:03:55) at position 4 (�): Unexpected character
Trace: <pre>#1 Magento\Framework\Stdlib\DateTime->formatDate() called at [vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:2863]
#2 Magento\Framework\DB\Adapter\Pdo\Mysql->formatDate() called at [vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:3094]
#3 Magento\Framework\DB\Adapter\Pdo\Mysql->prepareColumnValue() called at [vendor/magento/framework/Model/ResourceModel/AbstractResource.php:184]
#4 Magento\Framework\Model\ResourceModel\AbstractResource->_prepareDataForTable() called at [vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php:544]
#5 Magento\Framework\Model\ResourceModel\Db\AbstractDb->_prepareDataForSave() called at [vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php:821]
#6 Magento\Framework\Model\ResourceModel\Db\AbstractDb->updateObject() called at [vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php:415]
#7 Magento\Framework\Model\ResourceModel\Db\AbstractDb->save() called at [vendor/magento/framework/Model/AbstractModel.php:655]
#8 Magento\Framework\Model\AbstractModel->save() called at [app/code/Mageplaza/Blog/Model/ResourceModel/Post.php:523]
#9 Mageplaza\Blog\Model\ResourceModel\Post->saveAuthor() called at [app/code/Mageplaza/Blog/Model/ResourceModel/Post.php:184]
#10 Mageplaza\Blog\Model\ResourceModel\Post->_afterSave() called at [vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php:835]
#11 Magento\Framework\Model\ResourceModel\Db\AbstractDb->processAfterSaves() called at [vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php:420]
#12 Magento\Framework\Model\ResourceModel\Db\AbstractDb->save() called at [vendor/magento/framework/Model/AbstractModel.php:655]
#13 Magento\Framework\Model\AbstractModel->save() called at [app/code/Mageplaza/Blog/Controller/Adminhtml/Post/Save.php:97]
#14 Mageplaza\Blog\Controller\Adminhtml\Post\Save->execute() called at [generated/code/Mageplaza/Blog/Controller/Adminhtml/Post/Save/Interceptor.php:24]
#15 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#16 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#17 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#18 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#19 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#20 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#21 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#22 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callPlugins() called at [generated/code/Mageplaza/Blog/Controller/Adminhtml/Post/Save/Interceptor.php:39]
#23 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:159]
#24 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:99]
#25 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#26 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#27 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#28 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#29 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:137]
#30 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#31 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#32 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]

**Comment by NgoDuVietHung97** [comment]
Hi @weizhilee,

This problem has been solved in issue https://github.com/mageplaza/magento-2-blog/issues/165
Please follow the solution to resolve it.
Thank you!

**Comment by weizhilee** [comment]
resolved it
thanks
