### ISSUE TITLE
Enable Additional Links sitemap.xml create issue

### ISSUE THREAD

**Issue by Tezus** [mageplaza/magento-2-blog#210]
### Preconditions

1. Magento: 2.3.0
2. PHP: 7.1.3
3. MySQL: 
4. 

### Steps to reproduce

1.  enable Enable Additional Links sitemap.xml create issue
2.  add links. and create new sitemap.xml
3.  Additional Links fetch "http://https://www.xyz.com"
4. main issue is this "http://https://"

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by NgoDuVietHung97** [comment]
Hi @Tezus,

I'm not sure I can understand your problem.
So, could you please explain your problem in more details and send me some screenshot.
With it, I will be able to understand your problem and help you fix it in the shortest time.

Thank you!

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.
