### ISSUE TITLE
compiling issue lversion 3.10

### ISSUE THREAD

**Issue by mattyl** [mageplaza/magento-2-blog#212]
changing Block/Adminhtml/Category/Edit/Tab/Post.php has caused a compilation issue

PHP Fatal error:  Cannot use Magento\Framework\Object as Object because 'Object' is a special class name in /var/www/vhosts/azuni.co.uk/httpdocs/vendor/mageplaza/magento-2-blog-extension/Block/Adminhtml/Category/Edit/Tab/Post.php on line 31
-bash-4.2$ php bin/magento setup:di:compile

**Comment by mattyl** [comment]
magento 2.3.2
also
Block/Adminhtml/Category/Edit/Tab/Post.php on line 31
Block/Adminhtml/Post/Edit/Tab/Product.php on line 32
Block/Adminhtml/Tag/Edit/Tab/Post.php on line 31
Block/Adminhtml/Topic/Edit/Tab/Post.php on line 31

**Comment by BezV8** [comment]
Observing the same behaviour here, also on Magento 2.3.2

**Comment by NgoDuVietHung97** [comment]
Hi,

Sorry for the late response.
To solve this problem, please download and replace the attached files:
[Mageplaza.zip](https://github.com/mageplaza/magento-2-blog/files/3470249/Mageplaza.zip)

 - Post.php: Mageplaza/Blog/Block/Adminhtml/Category/Edit/Tab/Post.php
 - Post.php: Mageplaza/Blog/Block/Adminhtml/Tag/Edit/Tab/Post.php
 - Post.php: Mageplaza/Blog/Block/Adminhtml/Topic/Edit/Tab/Post.php
 - Product.php: Mageplaza/Blog/Block/Adminhtml/Post/Edit/Tab/Product.php

Then, please try to run the command again and let me know the result.
Thank you!

**Comment by mattyl** [comment]
thanks that seems to fix it

**Comment by BezV8** [comment]
I've just tested the fix out here as well and it's compiling successfully. Thanks.

**Comment by chrispiebacon** [comment]
Is there a composer version we can point at that includes this fix?

**Comment by NgoDuVietHung97** [comment]
Hi @chrispiebacon,

We will update this and release the new version as soon as possible so please look forward to this.
Thank you!

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.

**Comment by Julime** [comment]
This isn't fixed.
