### ISSUE TITLE
Blog image not getting removed after checking "Delete Image" checkbox and saving the post

### ISSUE THREAD

**Issue by magentopits** [mageplaza/magento-2-blog#214]
### Preconditions

1. Magento: 2.3.2
2. PHP: 7.2
3. MySQL: 5.7

### Steps to reproduce

1. Create a blog post with image.
2. Edit the blog.
3. Check "Delete Image" checkbox and save post.

### Expected result

1. The image is removed.

### Actual result

1. The image is not removed.

**Comment by magentopits** [comment]
I fixed the issue by replacing,
$fieldset->addField('image', \Mageplaza\Blog\Block\Adminhtml\Renderer\Image::class, [
with
$fieldset->addField('image', \Mageplaza\Core\Block\Adminhtml\Renderer\Image::class, [
in file magento-2-blog-extension\Block\Adminhtml\Post\Edit\Tab\Post.php line no. 221

**Comment by NgoDuVietHung97** [comment]
Hi @magentopits,

Thanks for your feedback.
Here is our solution to this problem. Please download and replace the attached file:
 - Save.php: Mageplaza/Blog/Controller/Adminhtml/Post/Save.php
[Save.zip](https://github.com/mageplaza/magento-2-blog/files/3490670/Save.zip)

Then, try to create a new post and save it again.
Thank you!

**Comment by magentopits** [comment]
Hi @NgoDuVietHung97,
The fix worked fine. Thank you.
