### ISSUE TITLE
share post on facebook its not show post image

### ISSUE THREAD

**Issue by deepakmagento** [mageplaza/magento-2-blog#215]
### Preconditions

1. Magento: 2.2.4
2. PHP: 7.0
3. MySQL: 5.6
4. 

### Steps to reproduce

1. whne post share on facebook its show randon image not show post image
2. 
3. 

### Expected result

1. Need to show particular post image that i have shared

### Actual result

1. [Screenshot, logs]

**Comment by NgoDuVietHung97** [comment]
Hi @deepakmagento,

I'm not sure I can understand your problem.
When sharing the post on facebook, we just share the link of the post, not the post with the image.
We share the link, you click the link and you can access to the post.

Please check your problem again and please let me know if I misunderstand your problem.
Thank you!

**Comment by deepakmagento** [comment]
can post image as well . how can share post image also ??

**Comment by NgoDuVietHung97** [comment]
Hi @deepakmagento,

Sorry for the late response.
Unfortunately, the current version has not supported this function yet. I'm so sorry about that. However, I will surely note it to our developer to consider developing it in the future so please look forward to this. 

Thank you very much for your feedback.

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.
