### ISSUE TITLE
Disabled posts still showing in sitemap.xml

### ISSUE THREAD

**Issue by KineticTaicho** [mageplaza/magento-2-blog#216]
### Preconditions
1. Magento: 2.2.4
2. Blog extension 3.0.6

### Steps to reproduce
1. disable a post via Magento admin
2. generate sitemap.xml via Magentop admin

### Expected result
1. when a post is disabled, it will be removed from sitemap.xml

### Actual result
1.  find links to disabled posts in sitemap.xml
find the disabled post link:
https://crownbees.com/cbdev/faq-central/post/what-is-polyculture.html
in sitemap:
https://crownbees.com/cbdev/sitemap.xml

### OTHER SOLUTIONS TRIED

We downloaded a revised "sitemap.php" from a similar issue posted earlier. This updated file removed ALL posts from the sitemap, leaving only the category links:

https://crownbees.com/sitemap.xml

Thank you for any help!

**Comment by NgoDuVietHung97** [comment]
Hi @KineticTaicho,

To solve this problem, please download and replace the attache files:
 - Sitemap.php: Mageplaza/Blog/Mode/Sitemap.php

[Sitemap.zip](https://github.com/mageplaza/magento-2-blog/files/3500895/Sitemap.zip)

Then, try to generate sitemap.xml file again and let me know the result.
Thank you!

**Comment by KineticTaicho** [comment]
That seems to have fixed the sitemap problem, thank you!
