### ISSUE TITLE
Wordpress import broken.

### ISSUE THREAD

**Issue by BezV8** [mageplaza/magento-2-blog#217]
Related to #162, there still seems to be problems importing posts from wordpress into the Better Blog extension. I solved it using the same method as abg2knet and found that there was still a line in \Model\Import\WordPress.php that had
`'url_key' => $this->helperData->generateUrlKey($postModel->getResource(), $postModel, $post['post_name']`
replacing this with
`'url_key' => $post['post_name']`
solved the issues
### Preconditions

1. Magento: 2.3.2
2. PHP:  7.2
3. Better Blog: 3.1.0

**Comment by NgoDuVietHung97** [comment]
Hi @BezV8,

Thanks for your feedback.
We will check this problem and give you a response as soon as possible.

Thank you very much!

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.

**Comment by BezV8** [comment]
This is still an a bug with the latest version of the extension as installed via composer. Has this fix been incorporated into a future version?

**Comment by BezV8** [comment]
This problem is still present in the latest version of the extension.
