### ISSUE TITLE
Better Blog Comment Button Not working

### ISSUE THREAD

**Issue by grosoasap** [mageplaza/magento-2-blog#218]
### Preconditions

1. Magento: 
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by grosoasap** [comment]
After Writing any comment The comment button is not working

**Comment by NgoDuVietHung97** [comment]
Hi @grosoasap,

I can not reproduce your problem on my local machine.
Could you please explain your problem step by step and send me some screenshot?
With it, I can understand your problem and help you fix this in the shortest time.

I am looking forward to hearing from you.
Thanks!

**Comment by grosoasap** [comment]
![Capture](https://user-images.githubusercontent.com/54885657/64504159-dee1d380-d2eb-11e9-9046-7d5a8257d943.PNG)
Please Find the attached png
Highlighted button is not working
is their any requirement to change the internal source code of the module

**Comment by NgoDuVietHung97** [comment]
Hi @grosoasap,

Sorry but I still can not reproduce your problem on my local environment.
You can refer to the screenshot: 
![image](https://user-images.githubusercontent.com/32929797/64591290-a5849300-d3d3-11e9-95ed-51ad604f1c92.png)

Please let me know your version of Magento and Blog extension.
Thanks!

**Comment by grosoasap** [comment]
Magento ver. 2.3.1 and blog_v3.0.6_ce_mageplaza

**Comment by grosoasap** [comment]
Social comment is working but default comment button is not working

**Comment by tuyentay** [comment]
I have installed the same version of blog, but cannot reproduce the error. You can refer to my configuration
x-special/nautilus-clipboard
copy
file:///home/tuyen/Pictures/Screenshot%20from%202019-09-11%2016-12-52.png

**Comment by tuyentay** [comment]
![Screenshot from 2019-09-11 16-12-52](https://user-images.githubusercontent.com/55084549/64687425-a7725300-d4b4-11e9-8845-d474b25af46d.png)

**Comment by tuyentay** [comment]
Hi @grosoasap ,
I have installed the same blog version, but am unable to reproduce the error. You can refer to my configuration.
![Screenshot from 2019-09-11 16-12-52](https://user-images.githubusercontent.com/55084549/64687529-e0122c80-d4b4-11e9-80b0-800a4dd99de8.png)

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.
