### ISSUE TITLE
Move Author Info and Related Posts to Post Sidebar

### ISSUE THREAD

**Issue by mashasauer** [mageplaza/magento-2-blog#219]
I would like to have Authors Info (image and name) and Related Posts block in the post sidebar rather than in content area below the post. 
These blocks are currently part of the View.phtml and not separate files.
I have tried to create separate template files with these sections and include them in sidebar through post layout but I got error 500.
Could you please advise what is required to move these sections to separate template files and include them in sidebar through post layout?
 
Thanks.

**Comment by NgoDuVietHung97** [comment]
Hi @mashasauer,

I'm not sure I can understand your requirements. You don't have the related post in the post view page, just related product, please check it again.

You can simply move author information to the sidebar by the way update sidebar layout file and add a new template for that.
To do that, you can update file mpblog_post_view.xml like that:
```
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="1column" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <update handle="mpblog_design"/>
    <body>
        <referenceContainer name="content">
            <block class="Mageplaza\Blog\Block\Post\View" name="mpblog.post.view" template="post/view.phtml" cacheable="false">
                <block class="Mageplaza\Blog\Block\Post\RelatedProduct" name="related.category.products" as="related_products" template="Magento_Catalog::product/list.phtml"/>
            </block>
        </referenceContainer>
        <referenceContainer name="columns">
            <referenceContainer name="div.sidebar.main" htmlTag="div" htmlClass="sidebar sidebar-main">
                <referenceContainer name="blog.sidebar.main" label="Sidebar Main">
                    <block class="Mageplaza\Blog\Block\Post\View" name="mpblog.sidebar.author" template="Mageplaza_Blog::author/info.phtml" ifconfig="blog/sidebar/search/enable_search"/>
                </referenceContainer>
            </referenceContainer>
        </referenceContainer>
    </body>
</page>
```

and you just need to cut the template for author information and put it into the new template define in the layout file that has been updated.

Please let me know if you have any other questions or problems.
Thanks!

**Comment by mashasauer** [comment]
Hi @NgoDuVietHung97 ,
thank you for your fast reply, it's really appreciated.

I have followed your instructions and moved authors info to the sidebar, thank you!

Regarding related posts, actually there are both related posts and related products inside view.phtml template, please see attached screenshot of the file from the module.
But I followed the same logic and managed to move them to sidebar :)

Thanks again for your help!
<img width="1200" alt="Screenshot 2019-09-09 at 17 12 15" src="https://user-images.githubusercontent.com/19184078/64546086-44ed4b80-d32a-11e9-92d7-22d1103b3a57.png">
