### ISSUE TITLE
Unable to add/edit blog post

### ISSUE THREAD

**Issue by RustyIngles** [mageplaza/magento-2-blog#221]
### Preconditions

1. Magento: 2.3.2
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. Create/Edit a blog post
2. Click save
3. Error message appears

### Expected result

1. Blog post uis saved

### Actual result

1. [Screenshot, logs]

We are shown the following error:

1 exception(s):
Exception #0 (Exception): The file was not uploaded.

Exception #0 (Exception): The file was not uploaded.
<pre>#1 Magento\MediaStorage\Model\File\Uploader->__construct('image', &Magento\MediaStorage\Helper\File\Storage\Database#0000000020d2a35e0000000051f2a771#, &Magento\MediaStorage\Helper\File\Storage#0000000020d2a4640000000051f2a771#, &Magento\MediaStorage\Model\File\Validator\NotProtectedExtension#0000000020d2a4660000000051f2a771#) called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116]
#2 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\MediaSto...', array('image', &Magento\MediaStorage\Helper\File\Storage\Database#0000000020d2a35e0000000051f2a771#, &Magento\MediaStorage\Helper\File\Storage#0000000020d2a4640000000051f2a771#, &Magento\MediaStorage\Model\File\Validator\NotProtectedExtension#0000000020d2a4660000000051f2a771#)) called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:66]
#3 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\MediaSto...', array('fileId' => 'image')) called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#4 Magento\Framework\ObjectManager\ObjectManager->create('\Magento\MediaSt...', array('fileId' => 'image')) called at [generated/code/Magento/MediaStorage/Model/File/UploaderFactory.php:43]
#5 Magento\MediaStorage\Model\File\UploaderFactory->create(array('fileId' => 'image')) called at [vendor/mageplaza/module-core/Helper/Media.php:108]
#6 Mageplaza\Core\Helper\Media->uploadImage(array('author_id' => 1, 'name' => 'Miniature Effect...', 'enabled' => 1, 'short_descriptio...' => 'What are they?', 'post_content' => '<p style="text-a...', 'store_ids' => array(0), 'image' => array('value' => 'r/0/r0_189_2362_...'), 'categories_ids' => '', 'topics_ids' => '', 'tags_ids' => '', 'in_rss' => 0, 'allow_comment' => 1, 'publish_date' => '06/21/2019', 'publish_time' => array(16, 16, 52), 'url_key' => 'miniature-effect...', 'meta_title' => '', 'meta_description' => '', 'meta_keywords' => '', 'meta_robots' => 'INDEX,FOLLOW', 'layout' => 'empty'), 'image', 'post', 'r/0/r0_189_2362_...') called at [vendor/mageplaza/magento-2-blog-extension/Controller/Adminhtml/Post/Save.php:141]
#7 Mageplaza\Blog\Controller\Adminhtml\Post\Save->prepareData(&Mageplaza\Blog\Model\Post#0000000020d2a46e0000000051f2a771#, array('author_id' => 1, 'name' => 'Miniature Effect...', 'enabled' => 1, 'short_descriptio...' => 'What are they?', 'post_content' => '<p style="text-a...', 'store_ids' => array(0), 'image' => array('value' => 'r/0/r0_189_2362_...'), 'categories_ids' => '', 'topics_ids' => '', 'tags_ids' => '', 'in_rss' => 0, 'allow_comment' => 1, 'publish_date' => '06/21/2019', 'publish_time' => array(16, 16, 52), 'url_key' => 'miniature-effect...', 'meta_title' => '', 'meta_description' => '', 'meta_keywords' => '', 'meta_robots' => 'INDEX,FOLLOW', 'layout' => 'empty')) called at [vendor/mageplaza/magento-2-blog-extension/Controller/Adminhtml/Post/Save.php:92]
#8 Mageplaza\Blog\Controller\Adminhtml\Post\Save->execute() called at [generated/code/Mageplaza/Blog/Controller/Adminhtml/Post/Save/Interceptor.php:24]
#9 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#10 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#0000000020d2a2870000000051f2a771#) called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#11 Magento\Backend\App\AbstractAction->dispatch(&Magento\Framework\App\Request\Http#0000000020d2a2870000000051f2a771#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#12 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000020d2a2870000000051f2a771#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#13 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000020d2a2870000000051f2a771#) called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#14 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(&Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor#0000000020d2a1d50000000051f2a771#, &Closure#0000000020d2a1d70000000051f2a771#, &Magento\Framework\App\Request\Http#0000000020d2a2870000000051f2a771#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#15 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000020d2a2870000000051f2a771#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#16 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000020d2a2870000000051f2a771#), NULL) called at [generated/code/Mageplaza/Blog/Controller/Adminhtml/Post/Save/Interceptor.php:39]
#17 Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000020d2a2870000000051f2a771#) called at [vendor/magento/framework/App/FrontController.php:159]
#18 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#0000000020d2a2870000000051f2a771#, &Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor#0000000020d2a1d50000000051f2a771#) called at [vendor/magento/framework/App/FrontController.php:99]
#19 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#0000000020d2a2870000000051f2a771#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#20 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000020d2a2870000000051f2a771#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#21 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000020d2a2870000000051f2a771#) called at [app/code/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php:32]
#22 Infortis\Cgen\Plugin\Magento\Framework\App\FrontController->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#0000000020d2a3640000000051f2a771#, &Closure#0000000020d2a1290000000051f2a771#, &Magento\Framework\App\Request\Http#0000000020d2a2870000000051f2a771#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#23 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000020d2a2870000000051f2a771#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#24 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000020d2a2870000000051f2a771#), array(array('page_cache_from_...', 'default_store_se...', 'storeCookieValid...', 'install', 'configHash'))) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#25 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000020d2a2870000000051f2a771#) called at [vendor/magento/framework/App/Http.php:137]
#26 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#27 Magento\Framework\App\Http\Interceptor->___callParent('launch', array()) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#28 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#29 Magento\Framework\App\Http\Interceptor->___callPlugins('launch', array(), array(array('firstdataconnect...'))) called at [generated/code/Magento/Framework/App/Http/Interceptor.php:26]
#30 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#31 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#0000000020d2a2eb0000000051f2a771#) called at [index.php:39]
</pre>

**Comment by tuyentay** [comment]
Hi @RustyIngles ,
Please download and replace the file:Mageplaza/Blog/Controller/Adminhtml/Post/Save.php
[Save.zip](https://github.com/mageplaza/magento-2-blog/files/3608900/Save.zip)

**Comment by RustyIngles** [comment]
Thank you, that's working now
