### ISSUE TITLE
Exception adding a Blog Post

### ISSUE THREAD

**Issue by CafeRico** [mageplaza/magento-2-blog#222]
1. Magento: 2.3.2
2. PHP: 7.1

### Steps to reproduce
1. Adding a Blog Post - after clicking the SAVE button

### Actual result
`{"0":"The file was not uploaded.","1":"<pre>#1 Magento\\MediaStorage\\Model\\File\\Uploader->__construct('image', &Magento\\MediaStorage\\Helper\\File\\Storage\\Database#000000002b305d9900000000116d0bd3#, &Magento\\MediaStorage\\Helper\\File\\Storage#000000002b30756d00000000116d0bd3#, &Magento\\MediaStorage\\Model\\File\\Validator\\NotProtectedExtension#000000002b30756300000000116d0bd3#) called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:116]\n#2 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\MediaSto...', array('image', &Magento\\MediaStorage\\Helper\\File\\Storage\\Database#000000002b305d9900000000116d0bd3#, &Magento\\MediaStorage\\Helper\\File\\Storage#000000002b30756d00000000116d0bd3#, &Magento\\MediaStorage\\Model\\File\\Validator\\NotProtectedExtension#000000002b30756300000000116d0bd3#)) called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:66]\n#3 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\MediaSto...', array('fileId' => 'image')) called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:56]\n#4 Magento\\Framework\\ObjectManager\\ObjectManager->create('\\Magento\\MediaSt...', array('fileId' => 'image')) called at [generated\/code\/Magento\/MediaStorage\/Model\/File\/UploaderFactory.php:43]\n#5 Magento\\MediaStorage\\Model\\File\\UploaderFactory->create(array('fileId' => 'image')) called at [vendor\/mageplaza\/module-core\/Helper\/Media.php:108]\n#6 Mageplaza\\Core\\Helper\\Media->uploadImage(array('author_id' => 1, 'name' => 'Welcome', 'enabled' => 1, 'short_descriptio...' => 752783310214752783310214, 'post_content' => '<p><span>7527833...', 'store_ids' => array(0), 'categories_ids' => 2, 'topics_ids' => '', 'tags_ids' => '', 'in_rss' => 0, 'allow_comment' => 1, 'publish_date' => '9\/12\/2019', 'publish_time' => array(14, 31, 07), 'url_key' => 'welcome-to-cafe-...', 'meta_title' => 'welcome-to-cafe-...', 'meta_description' => 'welcome-to-cafe-...', 'meta_keywords' => 'welcome-to-cafe-...', 'meta_robots' => 'INDEX,FOLLOW', 'layout' => '1column'), 'image', 'post', NULL) called at [vendor\/mageplaza\/magento-2-blog-extension\/Controller\/Adminhtml\/Post\/Save.php:141]\n#7 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save->prepareData(&Mageplaza\\Blog\\Model\\Post#000000002b30756b00000000116d0bd3#, array('author_id' => 1, 'name' => 'Welcome', 'enabled' => 1, 'short_descriptio...' => 752783310214752783310214, 'post_content' => '<p><span>7527833...', 'store_ids' => array(0), 'categories_ids' => 2, 'topics_ids' => '', 'tags_ids' => '', 'in_rss' => 0, 'allow_comment' => 1, 'publish_date' => '9\/12\/2019', 'publish_time' => array(14, 31, 07), 'url_key' => 'welcome-to-cafe-...', 'meta_title' => 'welcome-to-cafe-...', 'meta_description' => 'welcome-to-cafe-...', 'meta_keywords' => 'welcome-to-cafe-...', 'meta_robots' => 'INDEX,FOLLOW', 'layout' => '1column')) called at [vendor\/mageplaza\/magento-2-blog-extension\/Controller\/Adminhtml\/Post\/Save.php:92]\n#8 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#9 Magento\\Framework\\App\\Action\\Action->dispatch(&Magento\\Framework\\App\\Request\\Http#000000002b305c4200000000116d0bd3#) called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:231]\n#10 Magento\\Backend\\App\\AbstractAction->dispatch(&Magento\\Framework\\App\\Request\\Http#000000002b305c4200000000116d0bd3#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#11 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->___callParent('dispatch', array(&Magento\\Framework\\App\\Request\\Http#000000002b305c4200000000116d0bd3#)) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#12 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Request\\Http#000000002b305c4200000000116d0bd3#) called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]\n#13 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch(&Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor#000000002b305f3900000000116d0bd3#, &Closure#000000002b305f3f00000000116d0bd3#, &Magento\\Framework\\App\\Request\\Http#000000002b305c4200000000116d0bd3#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#14 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Request\\Http#000000002b305c4200000000116d0bd3#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#15 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->___callPlugins('dispatch', array(&Magento\\Framework\\App\\Request\\Http#000000002b305c4200000000116d0bd3#), NULL) called at [generated\/code\/Mageplaza\/Blog\/Controller\/Adminhtml\/Post\/Save\/Interceptor.php:26]\n#16 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->dispatch(&Magento\\Framework\\App\\Request\\Http#000000002b305c4200000000116d0bd3#) called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#17 Magento\\Framework\\App\\FrontController->processRequest(&Magento\\Framework\\App\\Request\\Http#000000002b305c4200000000116d0bd3#, &Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor#000000002b305f3900000000116d0bd3#) called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#18 Magento\\Framework\\App\\FrontController->dispatch(&Magento\\Framework\\App\\Request\\Http#000000002b305c4200000000116d0bd3#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#19 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', array(&Magento\\Framework\\App\\Request\\Http#000000002b305c4200000000116d0bd3#)) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#20 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Request\\Http#000000002b305c4200000000116d0bd3#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#21 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', array(&Magento\\Framework\\App\\Request\\Http#000000002b305c4200000000116d0bd3#), array(array('default_store_se...', 'page_cache_from_...', 'storeCookieValid...', 'install', 'configHash'))) called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#22 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(&Magento\\Framework\\App\\Request\\Http#000000002b305c4200000000116d0bd3#) called at [vendor\/magento\/framework\/App\/Http.php:137]\n#23 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#24 Magento\\Framework\\App\\Bootstrap->run(&Magento\\Framework\\App\\Http\\Interceptor#000000002b305c3600000000116d0bd3#) called at [index.php:39]\n<\/pre>","url":"\/admin_16yuvj\/mageplaza_blog\/post\/save\/key\/5bb2fde0fca510c166d69a611897a3ef330a9b62a88098d118be298468e6b5e6\/active_tab\/post\/","script_name":"\/index.php"}
`

I get an error with an exception number. The Exception file in /var/reprt/ reads as above.

Any advice would be gratefully received.

Kevin

**Comment by tuyentay** [comment]
Hi @CafeRico ,
Please download and replace the file:Mageplaza/Blog/Controller/Adminhtml/Post/Save.php
x-special/nautilus-clipboard
copy
file:///opt/lampp/htdocs/magento2/app/code/Mageplaza/Blog/Controller/Adminhtml/Post/Save.php

**Comment by tuyentay** [comment]
Hi @CafeRico ,
Please download and replace the file:Mageplaza/Blog/Controller/Adminhtml/Post/Save.php
[Save.zip](https://github.com/mageplaza/magento-2-blog/files/3608895/Save.zip)

**Comment by CafeRico** [comment]
Tutentay

Thanks. That worked.

What is the Blogs front page? I created a Blog post:

http://dev.caferico.co.uk/blog/welcome-to-cafe-rico-blog.html

but

http://dev.caferico.co.uk/blog/<http://dev.caferico.co.uk/blog/welcome-to-cafe-rico-blog.html>

doesn’t show a list of posts?

Kevin Russell
Digital Marketing Manager
E: kevin@caferico.co.uk<mailto:kevin@caferico.co.uk>
T: 01305 761900
Click here to view our Catalogue online<https://issuu.com/cafericocoffee/docs>

**Comment by tuyentay** [comment]
Hi @CafeRico ,
Sorry for my slow response.But here,
The main blog home page is to display a list of posts,
Besides, you can also click Category, Tags,... to display the posts of the same type.
![Screenshot from 2019-09-16 08-47-34](https://user-images.githubusercontent.com/55084549/64931110-861cb880-d860-11e9-86d8-b1c3d51ce4c9.png)
If you have any other issues, don't hesitate to contact me again.
Have a nice day!

**Comment by CafeRico** [comment]
Thanks for the response. What is the main blog home page?

http://dev.caferico.co.uk/blog

doesn’t show anything?

Kevin Russell
Digital Marketing Manager
E: kevin@caferico.co.uk<mailto:kevin@caferico.co.uk>
T: 01305 761900
Click here to view our Catalogue online<https://issuu.com/cafericocoffee/docs>

**Comment by tuyentay** [comment]
Hi @CafeRico ,
http://dev.caferico.co.uk/blog
To run the path as above, you need to leave the Suffix Url field blank.
![Screenshot from 2019-09-16 16-41-29](https://user-images.githubusercontent.com/55084549/64948533-812c2900-d8a1-11e9-91c1-d0d72ba83170.png)
Please clear the cache and reload the page

**Comment by tuyentay** [comment]
Hi @CafeRico <https://github.com/CafeRico> ,
http://dev.caferico.co.uk/blog
To run the path as above, you need to leave the Suffix Url field blank.
if not default http://dev.caferico.co.uk/blog+field value Url Suffix.
Please clear the cache and reload the page

Vào Th 2, 16 thg 9, 2019 vào lúc 16:08 CafeRico <notifications@github.com>
đã viết:

**Comment by CafeRico** [comment]
Tuyentay

Thank you for your continued help. I have flushed the Cache and visit:

http://dev.caferico.co.uk/blog

but get a 404 page. I have included my configuration below:

[cid:image001.jpg@01D56D49.C2EB5320]

Kevin Russell
Digital Marketing Manager
E: kevin@caferico.co.uk<mailto:kevin@caferico.co.uk>
T: 01305 761900
Click here to view our Catalogue online<https://issuu.com/cafericocoffee/docs>

**Comment by tuyentay** [comment]
CafeRico <https://github.com/CafeRico>,
Please download and replace the file Mageplaza/Blog/Helper/Data.php
Make sure you leave the Suffix Url field blank in the configuration.
If you still get the same error, you can provide me with the version of
blog you are using


Vào Th 3, 17 thg 9, 2019 vào lúc 17:21 CafeRico <notifications@github.com>
đã viết:

**Comment by CafeRico** [comment]
Tuyentay

Downloading the data.php file and removing the URL Suffix did the trick. Thank you!

Kevin

**Comment by KilalaPhu** [comment]
@tuyentay  can you give me about your contact. im vietnamese, can you add me zalo 0868908879

**Comment by tuyentay** [comment]
Hi @KilalaPhu ,
I am very sorry because I do not use zalo. If you have a problem, don't hesitate to ask us questions. Have a nice day

**Comment by KilalaPhu** [comment]
you have use skype: buiphu1
i just learn magento2  and want contact with you to learn more

**Comment by tuyentay** [comment]
Hi @KilalaPhu ,
Unfortunately, I also do not use skype. Maybe when the time is up, I'll download the zalo app and add you later.

**Comment by KilalaPhu** [comment]
@tuyentay  you can let me how to edit template list blog post and detail blog post
because i don't know a lot about magento2

**Comment by tuyentay** [comment]
@KilalaPhu ,To edit the post, you can do the following:
1. Visit admin page.
2. https://i.imgur.com/Qoe3zIB.png
3. https://i.imgur.com/xdRaz7C.png

**Comment by KilalaPhu** [comment]
@tuyentay  i want change the template of the frontend. list and detail 
https://imgur.com/hpsZOXD
https://imgur.com/DszTPox

**Comment by KilalaPhu** [comment]
@tuyentay  how custom list post template. i coppy folder post in extension vendor\mageplaza\magento-2-blog-extension to app\design\frontend\Solwin\freego\Mageplaza_magento-2-blog-extension\templates

how to rename folder Mageplaza_magento-2-blog-extension to it work 
https://imgur.com/VgpoMiH

**Comment by tuyentay** [comment]
@KilalaPhu ,
Have you activated the mageplaza-blog module yet?
https://i.imgur.com/Wgrqs47.png  .
To edit templates (lists and details), we recommend that you do not edit. 
Because things are really good.
thanks

**Comment by KilalaPhu** [comment]
@tuyentay  i had install magento-2-blog-extension and i know how to customized template list and details
but i dont see code in your folder in your photo
https://imgur.com/Aa13GjT

i edit template list and details because i want change a desgin

**Comment by tuyentay** [comment]
@KilalaPhu ,
I have created more foder code and put my module in it,
I recommend not placing the module here https://i.imgur.com/bR27ucV.png .
You can refer here, how to create a module and get it running.
https://www.mageplaza.com/kb/how-create-hello-world-module-magento-2.html

**Comment by KilalaPhu** [comment]
@tuyentay why recommend not placing the module here https://i.imgur.com/bR27ucV.png .
i think customized just custom file necessary for it running. dont coppy all file in folder module into folder in code..
it will duplicate a lot file

**Comment by tuyentay** [comment]
@KilalaPhu ,
You can imagine that these are core modules, we should not edit them to avoid encountering errors.
So the module I created more, up to in foder code.
Here you can copy our blog module to the code

**Comment by KilalaPhu** [comment]
@tuyentay  ok thanks you so much.
you can share for me a  project magento 2. you had code done 
my email : strongover@gmail.com

**Comment by tuyentay** [comment]
@KilalaPhu ,
- You can go to the top of the page and click on mageplaza to find free products.
- Or you can visit https://www.mageplaza.com to find the suitable products
Thank you

**Comment by amenk** [comment]
Please release a new version with the patch

**Comment by KilalaPhu** [comment]
@tuyentay   
how use 1column
not use LEFT = '2columns-left'; and RIGHT = '2columns-right';
i add more 1columns for template but in admin slider dont have option to choose
please see file photo attack
https://imgur.com/nTghkHK

**Comment by Bang512** [comment]
Hi @KilalaPhu,

Sorry for the late response.
Unfortunately, Our extension does not support this option yet.
You can edit code to change the layout of the blog post page is "1column".
In file:
\Mageplaza\Blog\Controller\Post\Index.php 
change
`$page->getConfig()->setPageLayout($this->_helperBlog->getSidebarLayout());`
to 
`$page->getConfig()->setPageLayout('1column');`

**Comment by jwktje** [comment]
It looks like I might have a similar issue but it only happens when trying to add related products to a post. This is the report

```
{"0":"The file was not uploaded.","1":"<pre>#1 Magento\\MediaStorage\\Model\\File\\Uploader->__construct() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:116]\n#2 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:66]\n#3 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:56]\n#4 Magento\\Framework\\ObjectManager\\ObjectManager->create() called at [generated\/code\/Magento\/MediaStorage\/Model\/File\/UploaderFactory.php:43]\n#5 Magento\\MediaStorage\\Model\\File\\UploaderFactory->create() called at [vendor\/mageplaza\/module-core\/Helper\/Media.php:108]\n#6 Mageplaza\\Core\\Helper\\Media->uploadImage() called at [vendor\/mageplaza\/magento-2-blog-extension\/Controller\/Adminhtml\/Post\/Save.php:141]\n#7 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save->prepareData() called at [vendor\/mageplaza\/magento-2-blog-extension\/Controller\/Adminhtml\/Post\/Save.php:92]\n#8 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save->execute() called at [generated\/code\/Mageplaza\/Blog\/Controller\/Adminhtml\/Post\/Save\/Interceptor.php:24]\n#9 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#10 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:231]\n#11 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#12 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#13 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]\n#14 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#15 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#16 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->___callPlugins() called at [generated\/code\/Mageplaza\/Blog\/Controller\/Adminhtml\/Post\/Save\/Interceptor.php:39]\n#17 Mageplaza\\Blog\\Controller\\Adminhtml\\Post\\Save\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#18 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#19 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#20 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#21 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#22 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#23 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:136]\n#24 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#25 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:258]\n#26 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:40]\n<\/pre>","url":"\/beheer\/mageplaza_blog\/post\/save\/id\/1\/key\/55c71801845af06bd7997218b4bbc35a111c3f51f9711bcc72550546e9b10dc7\/back\/edit\/active_tab\/product\/","script_name":"\/index.php"}
```

**Comment by Bang512** [comment]
Hi @jwktje,

Sorry for the late response.
We have fixed this issue on branch master. Please upgrade the Blog extension and Core module to the latest version. You will not encounter this error anymore.

Have a nice day!
