### ISSUE TITLE
Creating posts error

### ISSUE THREAD

**Issue by JoaoOlsenTecnico** [mageplaza/magento-2-blog#223]
### Preconditions

1. Magento: 2.3
2. PHP: 7.1.24
3. MySQL: 5.7.24

### Steps to reproduce
1. Click to create a new post.
2. Fill in all fields
3. don't put a picture in the post

### Expected result

1. Post be saved

### Actual result

1. Server is in production mode so returns standard Magento error
![image](https://user-images.githubusercontent.com/32138879/65171976-7a78ef80-da22-11e9-8424-52c33047fc7e.png)

**Comment by tuyentay** [comment]
Hi @JoaoOlsenTecnico ,
Please download and replace the file.

- Mageplaza/Blog/Controller/Adminhtml/Author/Save.php

- Mageplaza/Blog/Controller/Adminhtml/Post/Save.php
[Mageplaza.zip](https://github.com/mageplaza/magento-2-blog/files/3629003/Mageplaza.zip)
If you still have any questions please let us know.

**Comment by JoaoOlsenTecnico** [comment]
> Hi @JoaoOlsenTecnico ,
> Please download and replace the file.
> 
> * Mageplaza/Blog/Controller/Adminhtml/Author/Save.php
> * Mageplaza/Blog/Controller/Adminhtml/Post/Save.php
>   [Mageplaza.zip](https://github.com/mageplaza/magento-2-blog/files/3629003/Mageplaza.zip)
>   If you still have any questions please let us know.

THANKS!!
