### ISSUE TITLE
Post authors not imported from wordpress.

### ISSUE THREAD

**Issue by BezV8** [mageplaza/magento-2-blog#225]
Post authors are not being created or assigned when running an import from wordpress.

### Preconditions

1. Magento: 2.3.2
2. PHP: 7.2
3. MySQL: 5.6
4. magento-2-blog: 3.1.0

### Steps to reproduce

1. Import posts from Wordpress

### Expected result

1. Post authors are imported alongside post content and assigned to the correct posts.

### Actual result

1. All posts are assigned to the user who ran the import command.

**Comment by NgoDuVietHung97** [comment]
Hi @BezV8,

Sorry for the late response.
I am trying to reproduce your problem in my local environment and I will notify you soon.
Thanks for your patience.

**Comment by NgoDuVietHung97** [comment]
Hi @BezV8,

I have reproduced your problem on my local and I have a solution to this problem.
Please download and replace the attached file following the path:
 - \Mageplaza\Blog\Model\Import\WordPress.php

[WordPress.zip](https://github.com/mageplaza/magento-2-blog/files/3680446/WordPress.zip)

Then please let me know the result.

**Comment by BezV8** [comment]
Hello @NgoDuVietHung97 
Apologies for the delay in responding, I didn't get the notification.

I have tested that and it has broken importing completely. I'm getting the "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later." error again. Seems to be related to #162 and #217 

I can't see 3.1.0 listed anywhere in the releases on github. Are there problems with this release that would mean downgrading to 3.0.6 is necessary?

**Comment by Bang512** [comment]
Hi @BezV8,

Thanks for your feedback.
Could you give some screenshot or video when you import the post from Wordpress into Magento?
I have tested this on the local environment and I can import posts completely.

Thanks!

**Comment by BezV8** [comment]
Hi @Bang512 
I've attached a screenshot to this comment. The result I am seeing is identical to that in the tickets mentioned in my previous comment.

![Screenshot_2019-10-28 Import Settings Better Blog Content Import(1)](https://user-images.githubusercontent.com/33320744/67686990-7b8d2d00-f98f-11e9-9977-f10efae89890.png)

**Comment by Bang512** [comment]
Hi @BezV8,

Sorry I can not reproduce this problem in my local environment.
Have you tried to use the solution of issue #162 and # 217 yet?
Is this fix your problem?

Thanks!

**Comment by Bang512** [comment]
Closed due no response within 7 days.
