### ISSUE TITLE
Composer version not up to date

### ISSUE THREAD

**Issue by jwktje** [mageplaza/magento-2-blog#230]
As mentioned on issue #203 , I am experiencing an old closed issue. 

When requiring like so ` "mageplaza/magento-2-blog-extension": "dev-master"` the bug doesn't occur.

Please update the version on composer if possible

**Comment by Bang512** [comment]
Hi @jwktje,

We need to consider and update a few other issues to release a new version.
So please look for this, we will update the version on composer as soon as possible.

Thank you very much for your feedback!

**Comment by jwktje** [comment]
Okay! Is there anything I could do in the meantime to help this process? 

Good luck and let me know when the composer version is updated.

**Comment by jwktje** [comment]
```
[14-Nov-2019 18:39:55 UTC] PHP Fatal error:  Cannot use Magento\Framework\Object as Object because 'Object' is a special class name in /vendor/mageplaza/magento-2-blog-extension/Block/Adminhtml/Post/Edit/Tab/Product.php on line 32
```

**Comment by jwktje** [comment]
The current git version introduces new errors. 
Can you let me know what the latest stable version before 3.0.6 is? So I can roll back to this until a new stable version is ready.

**Comment by jwktje** [comment]
I found that commit 684fb37 is a partial solution to my bugs. Why is this not released yet?

**Comment by Bang512** [comment]
Hi @jwktje,

Sorry for the late response.
Please check the latest version of our Blog extension (v3.1.0 on the branch master), you will see al the error has been solved.
Thanks!

**Comment by jwktje** [comment]
Okay I will test straight away! Any chance this will also be updated on composer today?

**Comment by jwktje** [comment]
The fix works. No more bugs. Please please please put version 3.1.0 in Composer. That would be great!

**Comment by Bang512** [comment]
Hi @jwktje,

We have to review this version carefully and we will put version 3.1.0 in Comper as soon as possible, so please wait for this.
Thanks for your understanding!

**Comment by jwktje** [comment]
I understand. Any update since last week?

**Comment by Bang512** [comment]
Hi @jwktje,

We have not yet released a new version for now.
Please use the latest version on the branch master.
We will let you know when we release the new version of Blog extension.

Thanks!

**Comment by Bang512** [comment]
Hi @jwktje,

We released a new version of Blog extension, you can download via composer.
Please check again, your problem should be fixed.
Thanks!

**Comment by Bang512** [comment]
Closed due no response within 7 days.
