### ISSUE TITLE
The AheadWorks M1 importer does not escape all it's queries.

### ISSUE THREAD

**Issue by newicon-member** [mageplaza/magento-2-blog#231]
### Preconditions
1. Magento: 2.3.3
2. PHP: 7.2.21
3. MySQL: 5.7.26
4. Magento-2-Blog: 3.0.6

### Steps to reproduce
1. Attempt to import an AheadsWork M1 Blog database where one of the aw_blog_tags entries (in the 'tag' field) contains an apostrophe.

### Expected result
1. Import should work ... or at least provide a reasonable error message.

### Actual result
'Warning: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, boolean given in /......../vendor/mageplaza/magento-2-blog-extension/Model/Import/AheadWorksM1.php on line 219' is generated

1.  This generates an Exception which is uncaught in the extension.
2. Nothing is logged in the M2 logs
3. M2 admin area gives it's standard unhelpful error : 'A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.'

### Proposed solution
Either...

 * Ideally use PDO to escape all the queries in the extension implicitly

...or to fix just this issue...

 * use 'mysqli_real_escape_string(...)' to escape this query, so line 211 becomes:
`$tagTableSql = "SELECT * FROM '" . $data['table_prefix'] . self::TABLE_TAG . "' WHERE 'tag' = '" . mysqli_real_escape_string($connection, $name) . "'";`

N.B. I've replaced the backticks in the line above with single apostrophes since otherwise it messed with the formatting.

Apologies, I don't have time to work on this myself for now (If do I find time I'll come back and do a pull request) so I've done my import and moved on ... but I thought you should know.

**Comment by NgoDuVietHung97** [comment]
Hi @newicon-member,

Sorry for the late response.
I am trying to reproduce your problem in my local environment and I will let you know whenever I solved this problem.
Thanks for your patience!

**Comment by Bang512** [comment]
HI @newicon-member,

I can not reproduce your problem on my local environment.
Could you please send me the database you use to import from AheadWorks M1 to our Blog extension?

I am looking forward to hearing from you.
Thank you!

**Comment by newicon-member** [comment]
Hi NgoDuVietHung97 & Bang512,

I can't provide the exact database since it contains confidential information (I know that sounds strange for a blog ... but that's where I'm at unfortunately), however you can clearly see the issue by manually inspecting the codebase.

See here https://github.com/mageplaza/magento-2-blog/blob/master/Model/Import/AheadWorksM1.php#L215

... the variable $name is not properly escaped when the SQL string is built, instead it is manually surrounded by apostrophes ... consequently if the variable $name contains an apostrophe the SQL will be invalid, the $name variable was previously read from the M1 table `aw_blog_tags` field `tag` and there is no inherent reason why this _won't_ contain apostrophes.

With the greatest respect if you can't see what's wrong with this by inspection then I suggest you read up on SQL injection.

Thanks.

**Comment by Bang512** [comment]
Hi @newicon-member,

Thanks for taking the time to speak about this issue and SQL injection.

Doing with you has been great. I've learned so much from you and have made several updates to our products based on your thorough, thoughtful feedback. I appreciate everything you've done to make our company the best it can be.

Please keep in touch. Good luck with everything!

**Comment by Bang512** [comment]
Closed due no response within 7 days.

**Comment by newicon-member** [comment]
Hi all,

Not sure why this was closed as it isn't fixed, see
https://github.com/mageplaza/magento-2-blog/blob/master/Model/Import/AheadWorksM1.php#L218

The fix I suggested would take at most 5 minutes to commit.

Thanks

**Comment by Bang512** [comment]
Hi @newicon-member,

We need to review be careful and we will update this issue in the next release.
Thanks for your contribution!

Regards

**Comment by DougallWinshipRO** [comment]
OK thanks for the clarification, I totally understand you wanting to review carefully! It's just a bit odd to mark tickets as closed when the issue is still open. Thanks again.
