### ISSUE TITLE
Better Blog: Extension is not activated - Activation isn't possible

### ISSUE THREAD

**Issue by InaBurger** [mageplaza/magento-2-blog#232]
Hello!

I just installed Better Blog (Version: 3.0.6), but I can't activate this extension.

### Preconditions

At first I had the normal version of the blog tool. At this moment, I wasn't able to activate the tool - as soon as I started to hit the button "activate now", nothing happened. Afterwards I was looking for a solution and I found one here (but for another better blog version).

I used this one: https://github.com/mageplaza/magento-2-blog/issues/184

Now I'm able to click on the "activate now" button and it leads me to the code (I can't change the information in this field), but when I want to refresh the page, it seems like the config wasn't changed at all and I can try it again - with the same effect.

1. Magento: 2.3.2
2. PHP: unknown
3. MySQL: unknown
4. 

### Steps to reproduce

1. try: without changing the active.php file
2. try: after changing the active.php file i could fill in the details, but it didn't really saved the config
3. 

### Expected result

1. I just want to activate the tool

### Actual result

1. [Screenshot, logs]

**Comment by NgoDuVietHung97** [comment]
Hi @InaBurger,

Sorry for the late response.
Please update our Blog extension and Core module to lastest version (Blog v3.1.0 and Core v1.4.6)
Then, try to activate this extension again and let me know the result.
Thanks!

**Comment by InaBurger** [comment]
> Hi @InaBurger,
> 
> Sorry for the late response.
> Please update our Blog extension and Core module to lastest version (Blog v3.1.0 and Core v1.4.6)
> Then, try to activate this extension again and let me know the result.
> Thanks!

Hi, @NgoDuVietHung97 

It's fine. Where do I find those Updates?
I have another problem - the activation of the theme Porto isn't possible either. Both of them need the same Active.php-File, right? And that's the reason why I can't activate it?

**Comment by KilalaPhu** [comment]
@NgoDuVietHung97  hi can you help me the issue 
https://github.com/mageplaza/magento-2-blog/issues/233

**Comment by Bang512** [comment]
Hi @InaBurger,

Sorry for the late response.
You can find the latest version of Blog extension and Core module on branch master of this.
And about the problem activation of the theme Porto, please contact with Porto team to get the best support.
Thanks!

**Comment by Bang512** [comment]
Closed due no response within 7 days.
