### ISSUE TITLE
it error can not input url from other website 

### ISSUE THREAD

**Issue by KilalaPhu** [mageplaza/magento-2-blog#233]
https://imgur.com/uNDOe5D
please look image in url

**Comment by Bang512** [comment]
Hi @KilalaPhu,

In URL Key, you need to put in it only url-key of the post, not include the domain.
http://prntscr.com/q35uys
http://prntscr.com/q35v7j

You can follow this guide to know more about our extension:
http://docs.mageplaza.com/blog-m2/?_ga=2.43932833.541093291.1574923500-650958518.1574923500

Please let me know if you have another question or problem, I will help you.
Have a nice day!

**Comment by Bang512** [comment]
Closed due no response within 7 days.
