### ISSUE TITLE
Add script on the header of each article

### ISSUE THREAD

**Issue by Farmaa** [mageplaza/magento-2-blog#234]
I was wondering if it would be possible to add structured data in json-ld for each article in my Mageplaza better blog.

right now I cannot, only way I can think of is using google tag manager but it is not advised by Google.

regards,
Davide

**Comment by Bang512** [comment]
Hi @Farmaa, 

I'm not sure I can understand your question.
What data structure you want to add in Blog extension? And why you need it?
Please explain your problem in more detail so I can help you solve this problem in the shortest time.

Have a nice day!

**Comment by Farmaa** [comment]
Hello,
I'd like to put a script like this in the <head> tag of the article page:
< script type = 'application/ld+json' class = 'yoast-schema-graph' > {
	"@context": "https://schema.org",
	"@graph": {
		"@context": "https://schema.org",
		"@graph": [{
				"@type": "FAQPage",
				"mainEntityOfPage": {
					"@id": "http://associazionecfs.it/insonnia-rimedi/#article"
				},
				"name": "Insonnia rimedi naturali",
				"mainEntity": [{
						"@type": "Question",
						"name": "La melatonina \u00e8 efficace contro l'insonnia?",
						"answerCount": 1,
						"acceptedAnswer": {
							"@type": "Answer",
							"text": "Gli integratori di melatonina migliorano la qualit\u00e0 del sonno. Pare che siano particolarmente efficaci se si soffre di jet lag o si lavora come turnisti.  "
						}
					}, {
						"@type": "Question",
						"name": "La valeriana \u00e8 efficace contro l'insonnia? ",
						"answerCount": 1,
						"acceptedAnswer": {
							"@type": "Answer",
							"text": "La radice di valeriana \u00e8 un integratore comune che pu\u00f2 migliorare la qualit\u00e0 del sonno, quantomeno in alcune persone. Sono necessari ulteriori studi sulla sua sicurezza nell'utilizzo a lungo termine.  "
						}
					}
				]
			}
		]
	}
}
<  / script >

but maybe reading this post I can put it also in the body of the page:
https://stackoverflow.com/questions/28687653/schema-org-json-ld-where-to-place

what do you think?

Thank you for your answer,
Davide

**Comment by Bang512** [comment]
Hi @Farmaa,

To add that script on the head tag, please download and replace the attached file:
 - app/code/Mageplaza/Blog/view/frontend/templates/post/list.phtml

[list.zip](https://github.com/mageplaza/magento-2-blog/files/3904230/list.zip)
Then, please clear the cache and let me know the result.

Thanks!

**Comment by Bang512** [comment]
Closed due no response within 7 days.

**Comment by Farmaa** [comment]
Hi,

just checked the code, I believe this will add the json+ld script at the end of each article, the main issue I am concerned about is that this will include always the same script for each article while it is important to have always different script for each article as this information is specific to the post.

I believe that including the script at the article content will have the same effect and allow me to customize the content every time.

Regards,
Davide
