### ISSUE TITLE
How to Display recent blog post on Home page 

### ISSUE THREAD

**Issue by pramod-mishra** [mageplaza/magento-2-blog#235]
i have recently installed mageplaza extension for blog but i dont know how to display recent blog on the home page from the bakend

**Comment by Bang512** [comment]
Hi @pramod-mishra,

You can display the recent blog on the home page by insert Mageplaza_Blog widget on home page created in the backend.

You can follow this guide to know how to create Mageplaza_Blog widget:
http://docs.mageplaza.com/blog-m2/?_ga=2.53151528.1083249751.1575962451-962164589.1556161290#ix-create-new-widget

Please let me know if you have any questions or problems.
Thanks!
