### ISSUE TITLE
Something went wrong while saving the Author.

### ISSUE THREAD

**Issue by Farmaa** [mageplaza/magento-2-blog#237]
### Preconditions

1. Magento:  2.2.5
2. PHP:  7.0.33

### Steps to reproduce

1.  edit any Author information pages at this page mpblog/author/edit/key/dae4dc5dc3e80645279241aa7ff0fa4a2de99596eec34417ea5714199f3cd325/back/edit/active_tab/author/
2. try to save

### Expected result

1. Author information are updated.

### Actual result

1.  Red error message Something went wrong while saving the Author.
![author error](https://user-images.githubusercontent.com/56177937/70903464-3e443380-1fff-11ea-88da-0dd20222530e.JPG)

Another generic question is if the module can manage multiple author, I see no places on the back office front end to add multiple authors but on the database I have three entries:
![author db](https://user-images.githubusercontent.com/56177937/70903643-9713cc00-1fff-11ea-8c6b-044296c191b8.JPG)

**Comment by Bang512** [comment]
Hi @Farmaa,

Thanks for contacting us.
About the first problem, "can not save the author information", please try to download and replace the attached file:
 - \Mageplaza\Blog\Controller\Adminhtml\Author\Save.php
[Save.zip](https://github.com/mageplaza/magento-2-blog/files/3972041/Save.zip)

About the second problem, we are developing this function and will show it in the future, so please look for this.

I hope my answers can satisfy you. 
Please feel free to contact us if we can be of further assistance.
Thank you!

**Comment by Farmaa** [comment]
Hi,
I found the file here :
public_html/vendor/mageplaza/magento-2-blog-extension/Controller/Adminhtml/Author

is this the correct path?
I compared the current save.php and the one you provided and looked similar, I then overwrote it with your version. (attached both versions)
[Save_bothversions.zip](https://github.com/mageplaza/magento-2-blog/files/3995367/Save_bothversions.zip)

Unfortunately, after clearing the cache and trying to save on the author page, I receive the exact same error.

Thank you for any further assistance.

Regards,
Davide

**Comment by Farmaa** [comment]
Can this issue be due to my URL that is:

https://<domain>/<admin-bo>/mpblog/author/edit/key/<token>/back/edit/active_tab/author/

while save.php expects setPath('mageplaza_blog/*/edit' ?

Regards,
Davide

**Comment by Bang512** [comment]
Hi @Farmaa,

Yes, that is the correct path.
I have two solutions to this problem.
Solution 1: Please try to download and replace the attached file:
 - \Mageplaza\Blog\Controller\Adminhtml\Author\Save.php (in your case it will be public_html/vendor/mageplaza/magento-2-blog-extension/Controller/Adminhtml/Author/Save.php)
[Save.zip](https://github.com/mageplaza/magento-2-blog/files/4001675/Save.zip)

Solution 2: If solution 1 doesn't work, please try to download and replace the attached file:
 - \Mageplaza\Core\Helper\Media.php (in your case, it can be public_html/vendor/mageplaza/module-core/Helper/Media.php)
[Media.zip](https://github.com/mageplaza/magento-2-blog/files/4001681/Media.zip)

Then, please clear the cache and let me know the result after you try to save the author's information again.
Thanks!

**Comment by Farmaa** [comment]
Hello,

I tried to overwrite the version 2 of the save.php with no luck.

I have seen the change in the Media.php, I am a little afraid to make this change as it will have an impact on all the mageplaza modules in my site. 

I am noticinf that you are focus all the edit on the image modue but I also have problema saving with a description:

![image](https://user-images.githubusercontent.com/56177937/71514657-ff846800-289f-11ea-92b7-ccd3a36c6fd8.png)


Regards,
Davide

**Comment by Bang512** [comment]
Hi @Farmaa,

You can download and replace the attached file:
 - \Mageplaza\Blog\Helper\Image.php
[Image.zip](https://github.com/mageplaza/magento-2-blog/files/4009376/Image.zip)

Then, please try to edit the author's information again and let me know the result.
Thanks

**Comment by Bang512** [comment]
Closed due no response within 7 days.

**Comment by Farmaa** [comment]
Excuse for my delay, is only the last \Mageplaza\Blog\Helper\Image.php that I have to overwrite or also all the previous files you uploaded in previous posts?

Regards,
Davide
