### ISSUE TITLE
Single Blog Post gets Uncaught TypeError.

### ISSUE THREAD

**Issue by rexwreyes** [mageplaza/magento-2-blog#239]
The list page for the blog is fine, but the single post pages all appear with no header/footer and an error at the bottom.  Is there a conflict with the Magento Page Builder?  

`Fatal error: Uncaught TypeError: Argument 2 passed to Magento\PageBuilder\Plugin\Filter\TemplatePlugin::afterFilter() must be of the type string, null given, called in /var/www/html/vendor/magento/framework/Interception/Interceptor.php on line 146 and defined in /var/www/html/vendor/magento/module-page-builder/Plugin/Filter/TemplatePlugin.php:65 Stack trace: #0 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\PageBuilder\Plugin\Filter\TemplatePlugin->afterFilter(Object(Magento\Widget\Model\Template\Filter\Interceptor), NULL, NULL) #1 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Widget\Model\Template\Filter\Interceptor->Magento\Framework\Interception\{closure}(NULL) #2 /var/www/html/generated/code/Magento/Widget/Model/Template/Filter/Interceptor.php(403): Magento\Widget\Model\Template\Filter\Interceptor->___callPlugins('filter', Array, Array) #3 /var/www/html/vendor/mageplaza/magento-2-blog-extension/Block/Frontend.php(114): Magento\Widget\Model\Template in /var/www/html/vendor/magento/module-page-builder/Plugin/Filter/TemplatePlugin.php on line 65`

I did see the pull request here https://github.com/mageplaza/magento-2-blog/pull/186/files and made that change, but it didnt seem to help.

1. Magento: 2.3.2
2. PHP: 7.1
3. MySQL: 5.7

**Comment by NgoDuVietHung97** [comment]
Hi @rexwreyes,

Thanks for contacting us.
To solve this problem, please try to download and replace the attached file:
 - \Mageplaza\Blog\Block\Frontend
[Frontend.zip](https://github.com/mageplaza/magento-2-blog/files/3987493/Frontend.zip)

Then, please try to access a post detail page again and let me know the result.
Thanks!

**Comment by rexwreyes** [comment]
Thanks! It does work.  I had made the change but it was not getting pushed to my docker container.
