### ISSUE TITLE
Magento 2 Blog: Migration from Magento 1 mageplaza_betterblog 

### ISSUE THREAD

**Issue by k3746** [mageplaza/magento-2-blog#240]
### Preconditions

1. Magento: 
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by Bang512** [comment]
Hi @k3746,

Thanks for contacting us.
I'm not sure I can understand your problem. So could you please explain your problem in more detail and send me some screenshots?
With it, I can understand your problem and help you in the shortest time.

Thank you in advance!

**Comment by k3746** [comment]
Hi @Bang512 ,

Thanks for reply.

I want to export blogs from this Magento 1 module (https://github.com/mageplaza/magento-blog)

And import them in your this Magento 2 Extension.

**Comment by Bang512** [comment]
Hi @k3746,

Thanks for your response.

Unfortunately, we haven't provided any features like that at the moment. I'm so sorry about that. 
However, I will surely note your concerns to our developers. And we will consider developing the option in the future. 
  
Once again, thank you very much for your valuable feedback and significant contribution.
If you have any further questions/issues, please feel welcome to reach back out as we would be more than happy to assist. 

I wish you a great day!

**Comment by Bang512** [comment]
Closed due no response within 7 days.
