### ISSUE TITLE
Admin Area Blog Categories Page

### ISSUE THREAD

**Issue by korbax** [mageplaza/magento-2-blog#241]
### Preconditions

1. Magento: 2.3.0 cloud
2. PHP: 7.2.22

### Steps to reproduce
1. Go to admin area
2. Open Content -> Better Blog -> Categories

### Expected result
1. Open page with blog categories

### Actual result
1. page with error below

`Fatal error: Uncaught Error: Call to a member function getId() on null in /app/vendor/magento/framework/Data/Tree/Dbp.php:380 Stack trace: #0 /app/vendor/magento/module-catalog/Block/Adminhtml/Category/AbstractCategory.php(145): Magento\Framework\Data\Tree\Dbp->loadEnsuredNodes(Object(Mageplaza\Blog\Model\Category), NULL) #1 /app/vendor/magento/module-catalog/view/adminhtml/templates/catalog/category/tree.phtml(12): Magento\Catalog\Block\Adminhtml\Category\AbstractCategory->getRoot() #2 /app/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/app/vendor/mag...') #3 /app/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Mageplaza\Blog\Block\Adminhtml\Category\Tree), '/app/vendor/mag...', Array) #4 /app/vendor/magento/framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template->fetchView('/app/vendor/mag...') #5 /app/vendor/magento/module-backend/Block/Template.php(129): Magento\Framework\View\Element\Template->_toHtml() #6 in /app/vendor/magento/framework/Data/Tree/Dbp.php on line 380`

**Comment by Bang512** [comment]
Hi @korbax,

Thanks for contacting us.
Sorry, but I can not reproduce your problem on my local environment. Which version of the Blog extension are you using?
Please update your version to the latest version of Blog extension (v3.1.0).
If you have already use the latest version, please try to uninstall and reinstall our extension again.

Thanks!

**Comment by Bang512** [comment]
Closed due no response within 7 days.

**Comment by ManishaVasani** [comment]
Hi @Bang512,
I am facing same issue in Mageplaza_Blog version : 3.1.3
Magento Version: Magento ver. 2.3.5-p1

Steps to reproduce
Go to admin area
Open Content -> Better Blog -> Categories 

Error :
Fatal error: Uncaught Error: Call to a member function getId() on null in /var/www/html/nuttydelights/vendor/magento/framework/Data/Tree/Dbp.php:380
