### ISSUE TITLE
How to export blog post and import them into a new site

### ISSUE THREAD

**Issue by lysgets** [mageplaza/magento-2-blog#244]
Haven't seen a setting in Mageplaza better blog to export blog post/categories/tags. So that I can import them into another site. 
I have 100+ posts, so manual creation is not an option.
Please suggest.

**Comment by Bang512** [comment]
Hi @lysgets,

Thanks for contacting us!
Unfortunately, we haven't provided any features like that at the moment. I'm so sorry about that. 
However, I will surely note your concerns to our developers. And we will consider developing the option in the future. 
  
Once again, thank you very much for your valuable feedback and significant contribution.
If you have any further questions/issues, please feel welcome to reach back out as we would be more than happy to assist. 

I wish you a great day!

**Comment by Bang512** [comment]
Closed due no response within 7 days.

**Comment by zenerva** [comment]
The provided information is so helpful to me. Thank you so much for sharing your thoughts. Consumption of psyllium(Isabgol) will be very helpful to be physically fit. for more information you can visit the website http://gayatripsyllium.com/, You will definitely find the solution. Thank you
--
