### ISSUE TITLE
Mageplaza blog Sql syntax error

### ISSUE THREAD

**Issue by baljinderimpinge** [mageplaza/magento-2-blog#245]
Hello,

In any product page, I'm have a SQL syntax error:
### Preconditions

1. Magento: Magento ver. 2.2.6
2. PHP: 7.1
3. MySQL: 5.5
4. 

### Steps to reproduce

1. https://magento2.shisha-koenig.ch/insmoke-liquid-watermelon-swiss-made.html
2. 
3. 

### Expected result

1. In any product page, I'm have a SQL syntax error:

### Actual result

1. [Screenshot, logs]

**Comment by Bang512** [comment]
Hi @baljinderimpinge,

Thanks for contacting us.
Have you solved this issue? Because when I try to access the link you send, I can not see any problem.
If no, could you please send me some screenshots of this problem.

Thank you in advance!

**Comment by Bang512** [comment]
Closed due no response within 7 days.
