### ISSUE TITLE
When we try to remove the image from the post or the author it does not work correctly. 

### ISSUE THREAD

**Issue by carlosmbatista2009** [mageplaza/magento-2-blog#246]
### Preconditions

1. Magento: 2.3.3
2. PHP: 7.3

### Steps to reproduce

1. When we try to remove the image from the post or the author it does not work correctly. 

### Solution - Suggestion
The problem can be corrected by modifying the class `Mageplaza\Blog\Block\Adminhtml\Renderer\Image` ,  file `Mageplaza\Block/Adminhtml/Renderer /Image.php`, specifically

```
$ html. = '<input style="margin: auto;" type="checkbox" '.
     'name="'.
     $this->getName().
     '[delete] "value =" 1 "class ="checkbox"'.
....
```

It should look like this:
```
...
$ html. = '<input style="margin: auto;" type="checkbox" '.
     'name="'.strstr($this->getHtmlId(), '_', true).'['.
     $this->getName().
     '][delete]" value="1" class="checkbox"'.
...
```

The idea is that the name of the input is incorrect, it must be `post[image][delete]` or `author[image][delete]`...

**Comment by Bang512** [comment]
Hi @carlosmbatista2009,

Thanks for contacting us.
I can not reproduce your problem on my local environment.
Could you please tell me your version of the Blog extension? Please update the Blog extension to the latest version (v3.1.0)

I hope my answers can satisfy you. 
Please feel free to contact us if we can be of further assistance.

**Comment by Bang512** [comment]
Closed due no response within 7 days.
