### ISSUE TITLE
Fatal error after install and try to enter

### ISSUE THREAD

**Issue by mvaisberg** [mageplaza/magento-2-blog#249]
### Preconditions

1. Magento: 2.3.3
2. PHP: 7.2
3. MySQL: 5.7

### Steps to reproduce

1. Install via composer the blog extension
2. Enable it and try to enter to /blog.html (default url)

### Expected result

1. Should i see the blog page without anything ( i did not loaded any post )

### Actual result

1. [Screenshot, logs]

Seems that "$node" is null in vendor/mageplaza/magento-2-blog-extension/Block/Adminhtml/Category/Tree.php

Line 159

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getStoreIds() on null in /home/martin/Documents/Mext/landi/vendor/mageplaza/magento-2-blog-extension/Block/Adminhtml/Category/Tree.php:159\nStack trace:\n#0 /home/martin/Documents/Mext/landi/vendor/magento/module-catalog/Block/Adminhtml/Category/Tree.php(301): Mageplaza\\Blog\\Block\\Adminhtml\\Category\\Tree->_getNodeJson(NULL)\n#1 /home/martin/Documents/Mext/landi/vendor/mageplaza/magento-2-blog-extension/Block/Adminhtml/Category/Tree.php(139): Magento\\Catalog\\Block\\Adminhtml\\Category\\Tree->getTree(NULL)\n#2 /home/martin/Documents/Mext/landi/vendor/mageplaza/magento-2-blog-extension/Block/Category/Widget.php(44): Mageplaza\\Blog\\Block\\Adminhtml\\Category\\Tree->getTree(NULL, '1')\n#3 /home/martin/Documents/Mext/landi/vendor/mageplaza/magento-2-blog-extension/view/frontend/templates/category/widget.phtml(22): Mageplaza\\Blog\\Block\\Category\\Widget->getTree()\n#4 /home/martin/Documents/Mext/landi/vendor/magento/framework/View/TemplateEngine/Php.php(...\n'

**Comment by mvaisberg** [comment]
Seems that the installdata that create the root category did not run for some reason. I re runned and it was fixed

**Comment by ko1eda** [comment]
Just ran into this issue and can confirm @mvaisberg solution worked for me. I manually added the data into the table via phpmyadmin and it is now working. Don't know why the installdata wasn't being run in the first place though
