### ISSUE TITLE
Error whilst upgrading from 3.0.6 to 3.1.1

### ISSUE THREAD

**Issue by Asitis** [mageplaza/magento-2-blog#250]
I just tried updating the module from 3.0.6 to 3.1.1 via composer (`composer update`);

`Updating mageplaza/magento-2-blog-extension (3.0.6 => 3.1.1): Downloading (100%)`

This went fine, but then I ran the `setup:upgrade` command and this error showed:

> `SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'MAGEPLAZA_BLOG_AUTHOR_USER_ID', query was: ALTER TABLE `mageplaza_blog_author` MODIFY COLUMN `user_id` int(10) UNSIGNED NOT NULL  AUTO_INCREMENT COMMENT "Author ID", MODIFY COLUMN `name` varchar(255) NULL  COMMENT "Author Name", MODIFY COLUMN `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "Author Updated At", MODIFY COLUMN `short_description` mediumtext NULL COMMENT "Author Short Description", ADD COLUMN `customer_id` int(10) UNSIGNED NULL DEFAULT 0  COMMENT "Customer ID", ADD COLUMN `type` int(10) UNSIGNED NULL DEFAULT 0  COMMENT "Author Type", ADD COLUMN `status` int(10) UNSIGNED NULL DEFAULT 0  COMMENT "Author Status", ADD INDEX `MAGEPLAZA_BLOG_AUTHOR_USER_ID` (`user_id`), COMMENT='Mageplaza Blog Author Table'`

And it broke my store because it halted the upgrade. So I disabled the blog module to re-run all commands to get the store back online. Then I re-enabled the module and ran the setup again, but strangely without any error message this time, the module was enabled fine.
When I check the module in the backend it shows correct with the latest version, but on the frontend the whole blog and all posts just shows a blank page without any errors or logs on the server.

This is on Magneto 2.3.3, php7.2,

**Comment by kernest** [comment]
Had the same issues.

I had to drop the tables to get it up running with on prod.

Then I imported content afterwards.

Also hit the issue here: https://github.com/mageplaza/magento-2-blog/issues/249, where there is no root category.

This was just a fix, to get stuff up again.

**Comment by Asitis** [comment]
I dropped the notion in `setup_module` and re-ran the commands which worked but (indeed) all blogs were gone; I re-added them manually from a backup (weren't so many anyway), but out of curiosity; how did you import the content afterwards @kernest ?
I did see the export button to csv/xml, and an import page, but those imports were only for other 3rd party systems, not their own exports?

**Comment by kernest** [comment]
Just by SQL import - there wasn't many blogs posts at the website. Im happy for that!

**Comment by Bang512** [comment]
Hi,

Thanks for contacting us.
To solve this problem, you don't need to drop the tables. Just need to download and replace the file follow the path:
 - \Mageplaza\Blog\etc\db_schema.xml
[db_schema.zip](https://github.com/mageplaza/magento-2-blog/files/4063723/db_schema.zip)

Then, please try to run the command line to upgrade your database again.
Thank you!

**Comment by pmzandbergen** [comment]
The included schema whitelist seems to be incorrect, please run:

bin/magento setup:db-declaration:generate-whitelist --module-name=Mageplaza_Blog

Which will generate a new whitelist in the following path:

- Composer installations: vendor/mageplaza/magento-2-blog-extension/etc/db_schema_whitelist.json
- Manual installations: app/code/Mageplaza/Blog/etc/db_schema_whitelist.json

**Comment by mattyl** [comment]
the last two comments helped me get over this, thank you!

**Comment by jas8522** [comment]
>       [db_schema.zip](https://github.com/mageplaza/magento-2-blog/files/4063723/db_schema.zip)

This file worked for me. With composer installed version, the XML file within the zip goes in vendor/mageplaza/magento-2-blog-extension/etc/ and replaces the file already in there. Then ran setup:upgrade again and it worked smoothly.

**Comment by mattyl** [comment]
with magento 2.3.4 out it would be nice to fix this properly, i've run into it now 6 times - yes thank you for the extension! But would be great not to have to keep coming back to this thread!

**Comment by Bang512** [comment]
Hi,

Thanks for your response. I'm glad to know it works.
Please let me know if you have any other questions or problems with our extension.
Thanks!

**Comment by Bang512** [comment]
Closed due no response within 7 days.

**Comment by arvin-narvaez** [comment]
@Bang512 i try your db_schema.zip but i got another error
`SQLSTATE[23000]: Integrity constraint violation: 1022 Can't write; duplicate key in table '#sql-481_eb5a', query was: ALTER TABLE `mageplaza_blog_comment` MODIFY COLUMN `post_id` int(10) UNSIGNED NULL   COMMENT "Post ID", MODIFY COLUMN `entity_id` int(10) UNSIGNED NULL   COMMENT "User ID", MODIFY COLUMN `has_reply` int(5) UNSIGNED NULL   COMMENT "Comment has reply", MODIFY COLUMN `is_reply` int(5) UNSIGNED NULL   COMMENT "Is reply comment", MODIFY COLUMN `reply_id` int(10) UNSIGNED NULL   COMMENT "Reply ID", MODIFY COLUMN `content` mediumtext NULL , MODIFY COLUMN `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP  , MODIFY COLUMN `status` int(5) UNSIGNED NOT NULL DEFAULT 3  COMMENT "Status", MODIFY COLUMN `store_ids` int(11)  NOT NULL DEFAULT 0  COMMENT "Store Id", MODIFY COLUMN `user_name` mediumtext NULL COMMENT "User Name", MODIFY COLUMN `user_email` mediumtext NULL COMMENT "User Email", MODIFY COLUMN `import_source` mediumtext NULL COMMENT "Import Source", ADD CONSTRAINT `MAGEPLAZA_BLOG_COMMENT_POST_ID_MAGEPLAZA_BLOG_POST_POST_ID` FOREIGN KEY (`post_id`) REFERENCES `mageplaza_blog_post` (`post_id`)  ON DELETE CASCADE, COMMENT='Mageplaza Blog Comment Table'`

**Comment by Bang512** [comment]
Hi @arvin-narvaez,

Please try this instead:
- app/code/Mageplaza/Blog/etc/db_schema.xml
- app/code/Mageplaza/Blog/etc/db_schema_whitelist.json

[mageplaza.zip](https://github.com/mageplaza/magento-2-blog/files/4478877/mageplaza.zip)

Then, please clear all the cache and re-upgrade your store again.
Thank you!

**Comment by riconeitzel** [comment]
If you work with composer you can use https://github.com/cweagans/composer-patches and create a patch file which will be applied on the installation.
