### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by techbertu** [mageplaza/magento-2-blog#252]
I have been using Mageplaza Blog for a month or so.
I manage to install it without any problems and was working fine with it.

Now I noticed that could not browse the blog articles from the front end and I am getting an error

> Forbidden
> You don't have permission to access this resource.Server unable to read htaccess file, denying access to be safe
> 
> Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

I can't figure out what had happened, since I haven't changed anything.
Has anyone encountered this before?

### Preconditions
1. Magento: CE 2.2.2
2. PHP: 7.1
3. MySQL: 10.3.21-MariaDB
4. Mageplaza Blog: v3.0.6

**Comment by Bang512** [comment]
Hi @techbertu,

Thanks for contacting us.
Have you tried to provide all the permission for the Magento folder?
Please kindly try to provide all the permission for the Magento folder.

Thanks!

**Comment by techbertu** [comment]
Hi @Bang512 ,

The magento folder permission is set to 0755
then in the magento folder there is a folder named "blog.html" and the permission on this folder is 0750. when I set the permission on this folder to 0755 too, and tried to browse the blog, I didn't get the error but browsed the folder content (http://prntscr.com/qoxv1z)

What permission should I set and to what?

**Comment by Bang512** [comment]
Hi @techbertu,

I'm not sure I can understand what you mean.
In my case, I don't have the folder named "blog.html" and permission on the Magento folder is 777 (or 0777). 
You can try to remove folder "blog.html" and set the permission of the Magento folder again.
Please let me know if you have any other questions or problems.

Thanks!

**Comment by techbertu** [comment]
Hi @Bang512 

thanks for your help, I have deleted blog.html folder and worked fine. I don't understand from where that folder have come, but it really drove me crazy since I was not sure what has happened.

thanks again all for your help, could not have solved this without your help.

**Comment by Bang512** [comment]
Hi @techbertu,

I'm glad to know it works.  Since there is no issue left, I am going to close this issue now. 
Please don't hesitate to contact us if you have any questions or problems with our extension.

Thanks!
