### ISSUE TITLE
After update have an error: Undefined offset: 0

### ISSUE THREAD

**Issue by SerBab** [mageplaza/magento-2-blog#253]
After updating to version 3.1.0 have an error on fronend
1 exception(s): Exception #0 (Exception): Notice: Undefined offset: 0 in /var/www/html/.../vendor/mageplaza/magento-2-blog-extension/Model/Post.php on line 452

What's problem?

### Preconditions

1. Magento: 2.3.3
2. PHP: 7.2.26-1+ubuntu18.04
3. MySQL: 5.6.33

**Comment by Bang512** [comment]
Hi @SerBab,

Thanks for contacting us.
To solve this problem, please follow these steps:

1. Remove file db_schema.xml (in the path: Mageplaza\Blog\etc\)
2. Download and replace the attached file:
- Mageplaza\Blog\Setup\UpgradeSchema.php
- Mageplaza\Blog\Setup\InstallSchema.php
[Github-issue-253-fix.zip](https://github.com/mageplaza/magento-2-blog/files/4084359/Github-issue-253-fix.zip)


Then, please run the command line `php bin/magento setup:upgrade` to upgrade your database and let me know the result.
Thanks!

**Comment by Bang512** [comment]
Closed due no response within 7 days.
