### ISSUE TITLE
Product search in post edit does not work

### ISSUE THREAD

**Issue by OvalMedia** [mageplaza/magento-2-blog#254]
When editing a post it is impossible to filter the products list. The last version that worked for me was 3.0.5 in another project. I tried to downgrade to 3.0.5 from 3.1.0 but that messed everything up.

I also tried the latest dev version which did not help.

### Preconditions

1. Magento: 2.2.9
2. PHP: 7.1
3. MySQL: 
4. 

### Steps to reproduce

1. add or edit a blog post
2. switch to "products" tab
3. try to reduce the product list by entering filter criteria (e.g. sku)

### Expected result

1. The list should be reduced to the products that match the filter criteria

### Actual result

1. The unfiltered list gets reloaded

**Comment by Bang512** [comment]
Hi @OvalMedia,

Thanks for contacting us and sorry for the late response.

I can not reproduce your problem on my local. Could you please tell me which version of the core-module you have used?
If possible, please send me video to describe your error.
Thank you in advance!

**Comment by OvalMedia** [comment]
Hi,

thank you. I found out my composer setup was messed up and the core module was untouched for a couple of versions. 

It is fixed.
