### ISSUE TITLE
CreateAuthor.php line 78 Error while checkout

### ISSUE THREAD

**Issue by k0nkupa** [mageplaza/magento-2-blog#255]
### Preconditions

1. Magento: 2.3.2
2. PHP: 7.2.24

### Steps to reproduce

1. A customer placed an order
2. Customer paid the order
3. The error shows up

### Expected result

1. Redirect to Order Summary

### Actual result

1. Uncaught Error: Call to a member function getRequest() on null in app/code/Mageplaza/Blog/Observer/CreateAuthor.php:78

**Comment by Bang512** [comment]
Hi @k0nkupa,

Thanks for contacting us.
I am checking your problem and I will keep you updated with any change.
Thanks!

**Comment by Bang512** [comment]
Hi @k0nkupa,

Sorry for the delay. I have just come back after the Lunar New Year Vacation.
To solve this problem, please download and replace the attached file:
 - <mageplaza_blog_path>/Observer/CreateAuthor.php
[CreateAuthor.zip](https://github.com/mageplaza/magento-2-blog/files/4169429/CreateAuthor.zip)

with <mageplaza_blog_path> is:
 - <magento_folder>/app/code/Mageplaza/Blog/ if you install the Blog module manually (copy and paste)
 - <magento_folder>/vendor/mageplaza/magento-2-blog-extension/ if you install Blog module via composer

Then, try these steps again and let me know the result. If you still have trouble, let me know.
I will help you solve this.

Thanks!

**Comment by Bang512** [comment]
Closed due no response within 7 days.
