### ISSUE TITLE
Wordpress import broken better blog 3.1.1

### ISSUE THREAD

**Issue by BezV8** [mageplaza/magento-2-blog#257]
Related to #162 and #217, importing posts from wordpress into the Better Blog extension still fail. I solved it using the same method as abg2knet and found that there was still a line in \Model\Import\WordPress.php that had
`'url_key' => $this->helperData->generateUrlKey($postModel->getResource(), $postModel, $post['post_name']`
replacing this with
`'url_key' => $post['post_name']`
solved the issues
### Preconditions

1. Magento: 2.3.4
2. PHP:  7.2
3. Better Blog: 3.1.1

**Comment by Bang512** [comment]
Hi @BezV8,

Thanks for your contribution.
We have to check and review this solution and we will update this issue on the next release version.
Please kindly understand!

**Comment by Bang512** [comment]
Closed due no response within 7 days.
