### ISSUE TITLE
Cannot add widget to blog post

### ISSUE THREAD

**Issue by svenakela** [mageplaza/magento-2-blog#258]
We use a video widget to add videos to products and CMS content. It seems there is no way to add widgets to blog posts.

### Preconditions
1. Magento: 2.2.9

### Steps to reproduce

1. In backend, go to the `Content->Widgets` page
2. Add new widget, set the widget type and theme. Click next

### Expected result

1. In the `Layout Updates` Section there should be settings to inject the widget to blog posts.

### Actual result

1. There are no options to set the widget in a blog post.

**Comment by Bang512** [comment]
Hi @svenakela,

Thanks for contacting us.
If you want to add widget to our blog post page, our can add them on the content of the post:
http://prntscr.com/r4cwu5
If you want to create a widget of Mageplaza_Blog module (add to another page), you can choose widget type is Mageplaza_Blog:
http://prntscr.com/r4cxap

I hope you satisfy with my answer. Don't hesitate to let me know if you have any questions or problems with our extension.
Thanks!

**Comment by svenakela** [comment]
Hi @Bang512 

Unfortunately your screenshots are from a newer version of Magento with the latest editor which is not present in 2.2.9. There is no Widget button in the old version as far as I can see.

![image](https://user-images.githubusercontent.com/1113187/74876416-ebbb2680-5363-11ea-8f96-9c38dbe5303b.png)

**Comment by Bang512** [comment]
Hi @svenakela,

I have installed the Magento version 2.2.9 and I still see the button "insert widget", It seems different with the same on the latest version, but you still can insert the widget through this button.

Please help me re-check:
![image](https://user-images.githubusercontent.com/49020344/74909894-d5f14400-53eb-11ea-800e-d35f3548119f.png)

![image](https://user-images.githubusercontent.com/49020344/74909922-e43f6000-53eb-11ea-842e-c23585f5fdd0.png)

Thanks!

**Comment by svenakela** [comment]
This is a 2.2.9 and the Widgets button is missing for blog posts.
In normal content (add new page for example) the Widget button do exist. When writing a new blog post, the Widget button is gone.

**Comment by svenakela** [comment]
![image](https://user-images.githubusercontent.com/1113187/75327257-5a284900-587c-11ea-8c9b-cd2f1def308a.png)

**Comment by Bang512** [comment]
Hi @svenakela,

Can you please tell me the version of your Blog extension and Core Module?
You should update the Blog extension and Core module to the latest version (Blog v3.1.1, Core v1.4.8).
After the update, please let me know if the problems still remain.
Thanks!

**Comment by Bang512** [comment]
Closed due no response within 7 days.
