### ISSUE TITLE
Custom post values/attributes

### ISSUE THREAD

**Issue by dbartelmus** [mageplaza/magento-2-blog#263]
Is it possible to create custom values like “preparing time” or “advance level“ for ex. Easy/medium etc?
Single or multiple choice.

Where to start and how to override module to not loose changes during update.

**Comment by Bang512** [comment]
Hi @dbartelmus,

Thanks for contacting us.
You can custom any value if you want.

You can start by creating a new column in the `mageplaza_blog_post` table.
Then, you can add a new field in the Edit post page and start using this value. 

Thanks!

**Comment by dbartelmus** [comment]
Sure, but is there a way in Magento 2 to override such field sets from original module to ex. in custom theme?

**Comment by Bang512** [comment]
Hi @dbartelmus,

Sorry for the delay.
Yes, you can override it in your custom theme. Please don't hesitate to let me know if you have any questions or problems.

Thanks!

**Comment by dbartelmus** [comment]
Thanks, I've managed to do it with a success!
Second challange is to provide the same custom fields for non administrative users to fulfil.
In "my account" there is "new post" popup, but I'm struggle to provide additional fields there - this form is a part of built in functionality "Allows customers to register as an author".
