### ISSUE TITLE
page layout stuck to 2columns design

### ISSUE THREAD

**Issue by riconeitzel** [mageplaza/magento-2-blog#265]
if you try to set a page layout other than 2columns-left or 2columns-right you'll end up frustrated. 

https://github.com/mageplaza/magento-2-blog/blob/626d061c2d24ac87d511609bea9d09844b75815a/Controller/Post/Index.php#L64-L73

It always resets the configured layout (xml!) in

https://github.com/mageplaza/magento-2-blog/blob/626d061c2d24ac87d511609bea9d09844b75815a/Helper/Data.php#L329-L346

… So … no chance to change it once it's set in the backend, because there's no "none" option

https://github.com/mageplaza/magento-2-blog/blob/626d061c2d24ac87d511609bea9d09844b75815a/Model/Config/Source/SideBarLR.php#L53-L64

**Comment by Bang512** [comment]
Hi @riconeitzel,

Thanks for contacting us.
Unfortunately, our extension just supports two layout for the Blog list page: `2columns-left` and `2columns-right`, so you can not choose another layout. I'm so sorry about that. 

However, I will surely note your concerns to our developers. And we will consider developing the option in the future. 
  
Once again, thank you very much for your valuable feedback and significant contribution.
If you have any further questions/issues, please feel welcome to reach back out as we would be more than happy to assist. 

I wish you a great day!

**Comment by riconeitzel** [comment]
that's a terrible move as I'm unable to work around this without hakcking a plugin to your controller file 🤨 why don't you just add an option: "keep configured layout"!?
