### ISSUE TITLE
Sidebar shows after footer

### ISSUE THREAD

**Issue by milena912** [mageplaza/magento-2-blog#267]
Sidebar shows after footer out of the container. So the layout is completely messed on blog page view.
I have updated module on the latest version. 
I think everything is configurated correctly.

![side-bar](https://user-images.githubusercontent.com/66135407/83294439-9c4f8680-a1ed-11ea-88da-b40187df52c3.png)

### Preconditions

1. Magento: 2.3.4

**Comment by Bang512** [comment]
Hi @milena912,

Thanks for contacting us.
Maybe the problem happen while installing our extension on your site. Have you tried to uninstall our extension and re-install again.

Please don't hesitate to contact me again if the problem still remains.
I am looking forward to hearing from you.

Thank you very much!

**Comment by milena912** [comment]
Hi @Bang512 ,

Thanks for your response. I try to re-install the extension but the problem still exists.
Any other solution?

Thank you

**Comment by tudro** [comment]
Hello,

Same problem for me. Also, the drop down menu does not display. Probably there is a conflict with the theme or some other module. Any help would be appreciated.

Thank you
