### ISSUE TITLE
Error while importing Posts from wordpress

### ISSUE THREAD

**Issue by indrajeet183** [mageplaza/magento-2-blog#268]
I'm currently facing few issues if I try to import Posts from wordpress, the connection is succesfull.
But I get following error

`Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`mageplaza_blog_post`, CONSTRAINT `MAGEPLAZA_BLOG_POST_AUTHOR_ID_MAGEPLAZA_BLOG_AUTHOR_USER_ID` FOREIGN KEY (`author_id`) REFERENCES `mageplaza_blog_author` (`user_id`) ON DELETE CAS), query was: UPDATE `mageplaza_blog_post` SET `author_id` = ? WHERE (post_id = 2)","1"`

But the strange thing is if I execute same query it works and don't give me any error, also the author exist at id 1.

I can see the posts are imported too even after getting error, but most of their post content is either NULL/empty or full texts or combination of text and html.

### Current Setup
1. Magento: 2.3.4 CC
2. PHP: PHP 7.3.18
3. MySQL: Server version: 10.3.22
4. Plugin Version : 3.1.2

**Comment by Bang512** [comment]
Hi @indrajeet183,

Thanks for contacting us.
I am checking your problem and I will reply to you soon.

Have a nice day!

**Comment by maurizio-iomart** [comment]
Hi there,
I'm having the same issue importing posts from Wordpress to mageplaza/magento-2-blog-extension version:4.0.0

Is there an update or a solution for this?

Thanks
