### ISSUE TITLE
error when create a page

### ISSUE THREAD

**Issue by EngPeterMaged** [mageplaza/magento-2-blog#271]
Fatal error: Uncaught Error: Call to a member function getStoreIds() on null in /opt/lampp/htdocs/magento/vendor/mageplaza/magento-2-blog-extension/Block/Adminhtml/Category/Tree.php:159 Stack trace: #0 /opt/lampp/htdocs/magento/vendor/magento/module-catalog/Block/Adminhtml/Category/Tree.php(301): Mageplaza\Blog\Block\Adminhtml\Category\Tree->_getNodeJson(NULL) #1 /opt/lampp/htdocs/magento/vendor/mageplaza/magento-2-blog-extension/Block/Adminhtml/Category/Tree.php(139): Magento\Catalog\Block\Adminhtml\Category\Tree->getTree(NULL) #2 /opt/lampp/htdocs/magento/vendor/mageplaza/magento-2-blog-extension/Block/Category/Widget.php(44): Mageplaza\Blog\Block\Adminhtml\Category\Tree->getTree(NULL, '1') #3 /opt/lampp/htdocs/magento/vendor/mageplaza/magento-2-blog-extension/view/frontend/templates/category/widget.phtml(22): Mageplaza\Blog\Block\Category\Widget->getTree() #4 /opt/lampp/htdocs/magento/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/opt/lampp/htdo...') #5 /opt/lampp/htdocs/magento/vendor/magento/fram in /opt/lampp/htdocs/magento/vendor/mageplaza/magento-2-blog-extension/Block/Adminhtml/Category/Tree.php on line 159
### Preconditions

1. Magento: 2.3.3
2. PHP: 7.3
3. MySQL: 5
4. 

### Steps to reproduce

1.  Create a page with posts
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

![image](https://user-images.githubusercontent.com/57891823/85224522-53918480-b3cb-11ea-97b3-2d687f533eb4.png)

**Comment by EngPeterMaged** [comment]
![image](https://user-images.githubusercontent.com/57891823/85224882-b421c100-b3cd-11ea-8768-4bd49ce1b547.png)

**Comment by Bang512** [comment]
Hi @EngPeterMaged,

Thanks for contacting us.
This problem occurred during our extension installation. The default data for the table `mageplaza_blog_category` was not installed. 

To solve this problem, you just need to add the default data for this table. Here is the default data for this table, you can add this directly on your database:
```
       $defaultData = [
            'path'           => '1',
            'position'       => 0,
            'children_count' => 0,
            'level'          => 0,
            'name'           => 'ROOT',
            'url_key'        => 'root'
        ];
```

Please try this solution and let me know the result.
I am looking forward to hearing from you.

Thank you!

**Comment by EngPeterMaged** [comment]
thanks for you interest but i need to copy data of registered customer to
another database
what's the name of event what i can use it for observer

thanks

**Comment by EngPeterMaged** [comment]
can you help me

**Comment by absarakram** [comment]
Based on the answer from @Bang512 , the following query will add the missing record in `mageplaza_blog_category` table and solve the issue.

`INSERT INTO mageplaza_blog_category (path,position, children_count, level,name,url_key) VALUES ('1',0,0,0,'ROOT','root');`
