### ISSUE TITLE
Wrong column type in db_schema.xml for store_ids

### ISSUE THREAD

**Issue by thomascharbit** [mageplaza/magento-2-blog#272]
Hi,

On Magento 2.3 with latest version, the `store_ids` column has `int` type.
https://github.com/mageplaza/magento-2-blog/blob/master/etc/db_schema.xml#L31

I guess it should be a `text` column to allow comma-separated multiple ids, like in https://github.com/mageplaza/magento-2-blog/blob/master/Setup/InstallSchema.php#L79

Currently it is not possible to assign a blog post to mutlple store views because of this.

### Preconditions
1. Magento: 2.3
2. PHP: 7.2.31
3. MySQL: 5.7.29

### Steps to reproduce
1. Go to _Add new post_ page in admin to create a new post
2. Add a random title and select multiple store views
3. Save post

### Expected result
1. Blog post should be assigned to multiple store views

### Actual result
1. Blog post is only assigned to the first store view

**Comment by Bang512** [comment]
Hi @thomascharbit,

Thanks for your contribution.
We have already updated the solution for this problem on the local dev environment and we will release the new version soon.

Please look forward to this.
Thanks!

**Comment by thomascharbit** [comment]
Hi, do you have an ETA for this fix? Thanks.
