### ISSUE TITLE
 Uncaught Error: Call to a member function getUrl() on null /mageplaza/magento-2-blog-extension/Block/Listpost.php:171

### ISSUE THREAD

**Issue by connect232** [mageplaza/magento-2-blog#279]
### Preconditions

1. Magento: 2.3.5
2. PHP: 7.2
3. MySQL: 5.7.29
4. 

### Steps to reproduce

1. Go to an individual blog post page
2. 
3. 

### Expected result

1. Blog post page should appear

### Actual result

1. An error is occurred, which has been added to the title of this issue.

**Comment by giaphn** [comment]
I'm Shox from Mageplaza.
We have already received your pull request to fix this problem.
So we will double-check it.
Thank you for your contribution!
