### ISSUE TITLE
Create/edit post blank page if more post contains same product

### ISSUE THREAD

**Issue by giacomopiva** [mageplaza/magento-2-blog#281]
If more posts contains the same related products, the admin crate/edit post is blank.

### Preconditions
1. Magento: 2.3.5-p1
2. PHP: 7.2
3. MySQL: 5.7

### Steps to reproduce
1. create a blog post with a related product
2. create a second blog post with the same related product
3. click on "Add New Post", the page don't load properly and you'll get the CRITICAL error on the sysyem.log

### Expected result
1. The new post page should load properly

### Actual result

1. in the system.log 
main.CRITICAL: Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "1" already exists. [] []

**Comment by simonrl** [comment]
Did you find a solution for this? We're facing the same problem.

**Comment by giacomopiva** [comment]
Nope, I'm waiting for a solution or a temporary workaround. 
I'll try the solution you posted as soon as I can.

For the moment a very big "thank you" :)

**Comment by simonrl** [comment]
@thaimageplaza can my fix be integrated in the next release please? Or are there side cases where it doesn't work?

**Comment by giacomopiva** [comment]
The code fixed the problem for me

**Comment by nkajic** [comment]
Hi @giacomopiva @simonrl 
I see that group by statement was removed in commit eaee6ccefb12630db3804fae121cd36ba53bd6e0 and bringing it back solves both above problems for me. This way I can open edit page and i do not have that grid.js error.  I also kept extended left join by @simonrl 

Above is PR so feel free to review. Hope it helps.

**Comment by Alainvdz99** [comment]
I would recommend to merge the above PR from @nkajic . This is still an issue which has a big impact on webshops with a lot of blog posts. the fix with adding `distinct(true)` (#307 ) isn't enough to fix the problem.

@phutx Would you please look at this issue and PR?

Thanks

**Comment by Alainvdz99** [comment]
Hi @phutx,

I did upgrade the module to version 3.2 and we are using Magento 2.3. It did fix some blog posts but there were still a lot of blog post that gave a blank page if there were more posts with the same related product. The PR from @nkajic did fix it for me
