### ISSUE TITLE
SQLSTATE[42000] error due to mageplaza_blog_post and mageplaza_blog_post_product

### ISSUE THREAD

**Issue by ssriganesh** [mageplaza/magento-2-blog#283]
### Preconditions

1. Magento: 2.3.0
2. PHP: 7.3.22
3. MySQL: 15.7.31
4. 

### Steps to reproduce

1. No exact steps. This happening suddenly and I see the System.log with full of these errors and it is consuming a lot of my SQL resources and due to which the site is down
2. 
3. 

### Expected result

1. The site should work correctly

### Actual result

1. My server mysql shoots to 100% and site thwows error "site can be reached"
2. [2020-09-25 12:10:18] main.CRITICAL: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1',' at line 2, query was: SELECT COUNT(*) FROM `mageplaza_blog_post` AS `main_table`
 INNER JOIN `mageplaza_blog_post_product` AS `related` ON related.post_id=main_table.post_id AND related.entity_id= WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1', `store_ids`)))) AND (`publish_date` <= '2020-09-25 12:10:18') [] []
3. Process screeshot attached
![image](https://user-images.githubusercontent.com/9319573/94268095-48b23700-ff5a-11ea-8846-22f891d9dc55.png)

**Comment by NathanDayFE** [comment]
I have also come across this issue today when upgrading to Magento 2.4.3, the Error message is slightly off as it does not include the full query, the full query that is generated is:

```
SELECT `main_table`.*, `related`.* FROM `mageplaza_blog_post` AS `main_table`
 INNER JOIN `mageplaza_blog_post_product` AS `related` ON related.post_id=main_table.post_id AND related.entity_id= WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1', `store_ids`)))) AND (`publish_date` <= '2021-12-14 15:09:14') LIMIT 10
 ```
 
 the problem is actually with `AND related.entity_id= ` when the module attempts to retrieve the current product ID from the registry there is no product assigned so the product ID is returned as null breaking the SQL query

**Comment by phutx** [comment]
Hello @ssriganesh,

Please replace the attached file 
[RelatedPost.zip](https://github.com/mageplaza/magento-2-blog/files/7716423/RelatedPost.zip)
 with the path:
- app/code/Mageplaza/Blog/Block/Post/RelatedPost.php
Or via composer:
- mageplaza/magento-2-blog-extension/Block/Post/RelatedPost.php

Thank you!
