### ISSUE TITLE
End of Line sequence coding standard

### ISSUE THREAD

**Issue by adri2k** [mageplaza/magento-2-blog#286]
I'm trying to create a patch with cweagans/composer-patches and I notice that some files have End of Line Sequence LF and other CRLF.  
Is not possibile to apply diff patch on CRLF files (without --binary option trick).
  
I suggest to use LF standard instead of the actual mixing. 

### Expected result

1. All file with LF

### Actual result

1. Some file have CRLF other LF (example Plugin/Catalog/AttributeSort.php CRLF , Plugin/InfortisTopmenu.php LF )

**Comment by phutx** [comment]
Hi @adri2k ,
Thanks for your contribution. We will have a check and consider putting it on our roadmap.
