### ISSUE TITLE
blog post not displaying in front-end of specific website.

### ISSUE THREAD

**Issue by santoshshrestha2** [mageplaza/magento-2-blog#288]
Dear sir, I have multiple website in the same magento 2 backend. blog post is showing in the front-end of one website but the post is not showing in another website's front-end. the blog post for the second website is hidden and not showing anymore.  why is it happening? Please see the screenshots.
I have checked all the settings. it is working in one website(store-view) but not working in another website(store view)

![1](https://user-images.githubusercontent.com/73119381/96460799-7a749180-11d8-11eb-9b1d-80d22d0e6fb8.png)
![2](https://user-images.githubusercontent.com/73119381/96460808-7cd6eb80-11d8-11eb-933a-84785ceb39d6.png)

**Comment by tarunnbansal** [comment]
Hi @santoshshrestha2, same is happening with me.

**Comment by phutx** [comment]
Hi,
Maybe you selected only one store view only during the process to create a post,
https://prnt.sc/v6zgje
If you choose All Store Views or both of two store views, the post will be shown in two stores.

**Comment by santoshshrestha2** [comment]
I selected all store view as well as specific store view but still not showing in corresponding store blog. any idea?

**Comment by BNK989** [comment]
Hey, I seem to have the same issue, it applies to all my posts - this happened before and got magically solved - now it's back. Any ideas? https://goodlife.co.il/Magazine/post/gifts-ideas-newyear
