### ISSUE TITLE
Error , file core not found

### ISSUE THREAD

**Issue by purushotam6619360** [mageplaza/magento-2-blog#29]
Class 'Mageplaza\Core\Helper\AbstractData' not found in /var/www/html/MagentoFile1/app/code/Mageplaza/Blog/Helper/Data.php on line 33

1. Magento:2.1.5 
2. PHP: 5.6

**Comment by Kenny1994** [comment]
Hi,
Please download from ours website https://www.mageplaza.com and copy all folder Core to app/code/Mageplaza and run the following commend : php bin/magento setup:upgrade. Thanks !
