### ISSUE TITLE
Adding Alt-text to images

### ISSUE THREAD

**Issue by Andrea-Ferrari** [mageplaza/magento-2-blog#297]
### Description (*)
Add a filed for Alt-text for images

### Expected behavior (*)
When I add a new image (both the cover image and the images added with the editor) I can write an Alt-text (the text that will be shown on the website when I go over the image with the mouse pointer)

### Benefits
Improve optimization for accessibility

**Comment by phutx** [comment]
Hi @Andrea-Ferrari,

Thanks for your kind contribution.
We will review and consider rolling it out in the future.
