### ISSUE TITLE
Creating a post into specific category using API

### ISSUE THREAD

**Issue by brunodimauro** [mageplaza/magento-2-blog#298]
Hi guys!

I'm doing a POST to "**rest/V1/mpblog/post/create**" method and I'm not getting a nice result when I try to create a post with a specific category on it.

This is my payload:
```
{
   "post":{
      "name":"Test 9",
      "author_id":"10",
      "short_description":"Short description of my 9th post",
      "post_content":"<p>Description of my 9th post<br/></p>",
      "store_ids":"0",
      "enabled":1,
      "allow_comment":1,
      "category_ids":[
         2,
         7
      ]
   }
}
```

I have already tried to use a single **category_id** into array even like new string (and integer) property.

When I check the post using Magento Admin, there is no category associated.

Could somebody help me?

**Comment by phutx** [comment]
hi @brunodimauro ,
Please help me download the file, unzip and replace the old one with it via the path below:
app/code/Mageplaza/Blog/Model/ResourceModel/Post.php
[https://drive.google.com/file/d/1xd4df1P6FNJCk2QLlYatLqsBFfhOXecE/view?usp=sharing](url)
After that, kindly run the query insert post as above. 
Thanks.
