### ISSUE TITLE
Plugin relies on getCurrentAuthor() to return object but can be null

### ISSUE THREAD

**Issue by OvalMedia** [mageplaza/magento-2-blog#301]
### Summary (*)
Inside the plugin LinkMenu::afterGetLinks the code relies on the function to return an author ($this->helper->getCurrentAuthor()). But that function can return null instead resulting the follwing code ($author->getId()) to fail.

### Examples (*)
see summary

### Proposed solution
Check if getCurrentAuthor returned a valid result before calling a member (getId()).

**Comment by giaphn** [comment]
Hi,
Thank you for your contribution.
To solve this issue, please download and replace this file:
- app\code\Mageplaza\Blog\Plugin\Customer\LinkMenu.php
- [LinkMenu.zip](https://github.com/mageplaza/magento-2-blog/files/6154156/LinkMenu.zip)

**Comment by giaphn** [comment]
Closed due no response within 7 days.
