### ISSUE TITLE
Blog List API to get store specific post 

### ISSUE THREAD

**Issue by ashujangra** [mageplaza/magento-2-blog#306]
### Preconditions (*)

1.2.4.0
2.

### Steps to reproduce (*)

1. Added Post in specific store
2. now using following api rest/V1/mpblog/post/list?searchCriteria[filter_groups][0][filters][0][field]=store_ids&searchCriteria[filter_groups][0][filters][0][value] =2&searchCriteria[filter_groups][0][filters][0][condition_type]=eq trying to get the posts

### Expected result (*)

1. It should return posts in the same store, however its blank
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.
<img width="881" alt="image" src="https://user-images.githubusercontent.com/47097234/108225113-9fb2e580-7161-11eb-838f-8ee1066d19b4.png">

**Comment by giaphn** [comment]
Hi,
I'm Shox from Mageplaza.
Thank you for your report.
To fix this problem, please download and replace these files:

- app\code\Mageplaza\Blog\Model\Api\BlogRepository.php 
[BlogRepository.zip](https://github.com/mageplaza/magento-2-blog/files/6154740/BlogRepository.zip)
- app\code\Mageplaza\Blog\Helper\Data.php
[Data.zip](https://github.com/mageplaza/magento-2-blog/files/6154744/Data.zip)

Then clear the cache and check it again.
Thank you very much

**Comment by giaphn** [comment]
Closed due no response within 7 days.
