### ISSUE TITLE
Author dropdown, when creating a new blog post, does not contain the already created authors.

### ISSUE THREAD

**Issue by julianmurillosd** [mageplaza/magento-2-blog#309]
### Preconditions (*)

1. Magento 2.4.2
2. PHP 7.4
3. mysql 8.0.19-10
4. Blog Extension v4.0.0

### Steps to reproduce (*)

1. Go to content -> Better Blog -> Manage posts -> Add New Post

### Expected result (*)

1. I can select the author but this would not be the case

### Actual result (*)

1. When clicking on Author, the dropdown does not work and it does not contain any of the already created authors.

**Comment by giaphn** [comment]
Hi,
I'm Shox from Mageplaza.
I can't reproduce your problem.
Please check your author status. If the status is not 'Approved', this author will not appear in the dropdown menu

**Comment by giaphn** [comment]
Closed due no response within 7 days.
