### ISSUE TITLE
It didn't show the WYSIWYG editor

### ISSUE THREAD

**Issue by Henry17888** [mageplaza/magento-2-blog#311]
Magento version: 2.4.2
Better Blog installed via composer
When I wanna add a new post, I can't find the WYSIWYG editor in the content area, and I click the "Show / Hide Editor" button, nothing changes.
I filled some words with patagraph in the content area backend, and all the content is in the same paragraph when I check it in the storefront.
I find it has a WYSIWYG editor in the video, so, please kindly help.

**Comment by phutx** [comment]
Hi @Henry17888,

I'm Onesh from Mageplaza Support Team.
Please let me know the versions of the Blog and Core modules you are using.

Thanks!

**Comment by Henry17888** [comment]
Magento version: 2.4.2
Blog version: 4.0

**Comment by Henry17888** [comment]
> 
> 
> Hi @Henry17888,
> 
> I'm Onesh from Mageplaza Support Team.
> Please let me know the versions of the Blog and Core modules you are using.
> 
> Thanks!

Magento version: 2.4.2
Blog version: 4.0

**Comment by phutx** [comment]
Hi @Henry17888,
I would love to know the version of the Mageplaza Core module on your site. The latest version currently is v1.4.10

**Comment by Henry17888** [comment]
@phutx
thanks for your prompt reply.
please kindly advise how to check the Mageplaza Core module version.
thanks again.

**Comment by Henry17888** [comment]
Hi @phutx 
I installed the mageplaza core, while the editor still didn't work.

"magento/composer-root-update-plugin": "~1.1",
        "magento/product-community-edition": "2.4.2",
        "mageplaza/magento-2-blog-extension": "^4.0",
        "mageplaza/module-core": "^1.4",
        "mageplaza/module-smtp": "^4.3"

**Comment by Henry17888** [comment]
Hi @phutx 
I checked the console, and get an error like below:
Uncaught ReferenceError: require is not defined
    at (index):443
file:admin_xxxx/mageplaza_blog/post/edit/id/1/key/9179895955b97f25dd8cba23204a3ba466feda1709b2caca6eefdca5e2b1b2e5
I m not sure whether it's useful, just hope it can help you.
thank you for your kindly support.

**Comment by phutx** [comment]
Hi @Henry17888,

Thank you for your information as it is very helpful for me. However, I cannot replicate the issue from my side.

To get further support, you should submit a ticket (https://www.mageplaza.com/contact.html). We are here and more than happy to assist you further.

**Comment by Henry17888** [comment]
Hi @phutx,
Thank you. I will check with it.

**Comment by Henry17888** [comment]
I have updated the extension when I upgrade the Magento from V2.42-P1 to V2.4.3, while the editor won't work again, so how could I repair it?

**Comment by Kleibert** [comment]
I have the same problem 

 "name": "mageplaza/magento-2-blog-extension",
  "description": "Magento 2 Blog extension",
  "require": {
    "mageplaza/module-core": "^1.4.5"
  },
  "type": "magento2-module",
  "version": "4.1.1",
  "license": "proprietary",
  
"name": "mageplaza/module-core",
  "description": "Mageplaza Core for Magento 2",
  "type": "magento2-module",
  "version": "1.4.10",
  "license": "proprietary",


![Screen Shot 2021-11-30 at 1 08 31 PM](https://user-images.githubusercontent.com/42814600/144131064-6af969b5-a0a4-4b69-8fd2-3de6ebfd6b70.png)
