### ISSUE TITLE
SQL syntax error on product page

### ISSUE THREAD

**Issue by Green2Matter** [mageplaza/magento-2-blog#314]
### Preconditions (*)

1. Magento CE 2.4.2-p1
2. Percona Mysql 8.0.23

### Steps to reproduce (*)

1. Open product page

### Expected result (*)

1. No errors

### Actual result (*)

1. In developer mode, header displays:
`2 exception(s): Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1',' at line 2, query was: SELECT COUNT(*) FROM `mageplaza_blog_post` AS `main_table` INNER JOIN `mageplaza_blog_post_product` AS `related` ON related.post_id=main_table.post_id AND related.entity_id= WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1', `store_ids`)))) AND (`publish_date` <= '2021-05-27 13:41:48') Exception #1 (PDOException): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1',' at line 2 Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1',' at line 2, query was: SELECT COUNT(*) FROM `mageplaza_blog_post` AS `main_table` INNER JOIN `mageplaza_blog_post_product` AS `related` ON related.post_id=main_table.post_id AND related.entity_id= WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1', `store_ids`)))) AND (`publish_date` <= '2021-05-27 13:41:48') Exception #1 (PDOException): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1',' at line 2`

**Comment by phutx** [comment]
Hi @Green2Matter,

Please access the file: app/code/Mageplaza/Blog/Block/Post/RelatedPost.php
After that, help me find the getRelatedPostList() function and change it by this code:
public function getRelatedPostList()
    {
        if ($this->_relatedPosts == null) {
            /** @var Collection $collection */
            $collection = $this->helperData->getPostList();
            $collection->getSelect()
                ->join(
                    [
                        'related' => $collection->getTable('mageplaza_blog_post_product')
                    ],
                    'related.post_id=main_table.post_id AND related.entity_id=' . (int)$this->getProductId()
                )
                ->limit($this->getLimitPosts());

            $this->_relatedPosts = $collection;
        }

        return $this->_relatedPosts;
    }

Thanks
