### ISSUE TITLE
add product name on related product 

### ISSUE THREAD

**Issue by arun-magento** [mageplaza/magento-2-blog#315]
### Description (*)
i try to add product name on related product, can you help me?

![image](https://user-images.githubusercontent.com/59384425/120492989-2ec5cf80-c3d8-11eb-804c-8ca38dc91244.png)

**Comment by phutx** [comment]
Hi @arun-magento,

Please find and follow the path: Blog/Block/Adminhtml/Post/Edit/Tab/Product.php
Then, help me add the code $collection->addFieldToSelect('*');
in the function _prepareCollection() as below:
```
protected function _prepareCollection()
    {
        /** @var Collection $collection */
        $collection = $this->productCollectionFactory->create();
        $collection->addFieldToSelect('*');
        $collection->clear();

        $collection->getSelect()->joinLeft(
            ['mp_p' => $collection->getTable('mageplaza_blog_post_product')],
            'e.entity_id = mp_p.entity_id',
            ['position']
        )->distinct(true);

        $this->setCollection($collection);

        return parent::_prepareCollection();
    }
```

Thanks

**Comment by arun-magento** [comment]
hi @phutx 

thanks for reply 
bot not show product name
![120492989-2ec5cf80-c3d8-11eb-804c-8ca38dc91244](https://user-images.githubusercontent.com/59384425/120882924-192ef080-c5f8-11eb-953b-636cf1c7af0a.png)
