### ISSUE TITLE
How do I get content editors to support PageBuilder for Magento 2 Enterprise?

### ISSUE THREAD

**Issue by jiachao-zhang** [mageplaza/magento-2-blog#317]
### Description (*)

How do I get content editors to support PageBuilder for Magento 2 Enterprise?

https://magento.stackexchange.com/questions/340759/magento-2-adminhtml-form-add-text-field-through-function-prepareform-and-how-to

### Expected behavior (*)

When editing the BLOG content, it is possible to use PageBuilder to achieve the content of the arrangement.

### Benefits

....

### Additional information

.....

**Comment by phutx** [comment]
Hi @jiachao-zhang,

At present, our module has not supported PageBuilder yet. I'm so sorry about that. 
However, I've passed that feedback along to our development team to suggest making it more readily available in the future.

Thanks!
