### ISSUE TITLE
Mageplaza Blog wrong childrens path on category move

### ISSUE THREAD

**Issue by Funfelek** [mageplaza/magento-2-blog#321]
### Preconditions (*)

1. create 2 categories 'cat1' and 'cat2' (with some childrens)

### Steps to reproduce (*)
1. move by drag and drop 'cat1' into 'cat2'

### Expected result (*)

1. 'cat1' with its childrens is moved into 'cat2'

### Actual result (*)

1. 'cat1' is moved to 'cat2' - but 'cat1' childrens due to wrong sql query have wrong path set
2. they have path values like "REPLACE(`path`,'1/4/', '1/4/')"

to fix it:
in class Model\ResourceModel\Category
when calling $adapter->update() when binding expressions they should be passed as 'new '\Zend_Db_Expr(...)' not as strings

**Comment by phutx** [comment]
Hi @Funfelek,

We are thankful for your interest in our module. Also, I've passed your feedback along to our development team to suggest making it more readily available in the future.
Once again, thank you very much for your valuable feedback and significant contribution.
If you have any further questions/issues, please feel welcome to reach back out as we would be more than happy to assist.  I wish you a great day!
