### ISSUE TITLE
update suggestion of category select js in post edit

### ISSUE THREAD

**Issue by clion007** [mageplaza/magento-2-blog#323]
### Description (*)

In edit post page of admin, when we add a category for the post that has parents, only the category be checked, and have to click the parents categories of the added category one by one. Categories should be auto checked when their children or children's children be selected to checked. Thus is more friendly right?
### Expected behavior (*)

Categories should be auto checked when their children or children's children be selected to checked. 

### Benefits

It's more friendly in use, and no need to click  to check every parent category to be selected one by one in boring.

**Comment by phutx** [comment]
Hi @clion007,

We are thankful for your interest in our module. Also, I've passed your feedback along to our development team to suggest making it more readily available in the future.
Once again, thank you very much for your valuable feedback and significant contribution.
If you have any further questions/issues, please feel welcome to reach back out as we would be more than happy to assist.  I wish you a great day!
