### ISSUE TITLE
Installation gives error  Impossible to process constructor argument Parameter #0 [ <required> Mageplaza\Blog\Helper\Data $helperData ] of Mageplaza\Blog\Setup\InstallSchema class

### ISSUE THREAD

**Issue by vishalsanwar** [mageplaza/magento-2-blog#324]
### Preconditions (*)

1. Magento 2.4.2 Version
2. Error : Impossible to process constructor argument Parameter #0 [ <required> Mageplaza\Blog\Helper\Data $helperData ] of Mageplaza\Blog\Setup\InstallSchema class

### Steps to reproduce (*)

1. Download the module zip
2. install it
3. the got this error in console. 
Impossible to process constructor argument Parameter #0 [ <required> Mageplaza\Blog\Helper\Data $helperData ] of Mageplaza\Blog\Setup\InstallSchema class

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. Helper should not be assign into __construct in InstallSchema
2.

**Comment by ngvantuong** [comment]
What version of Blog module are you using? I just installed the Blog module v4.1.1, everything works fine.

**Comment by Shinichi69** [comment]
Closed due to no response within 7 days.
