### ISSUE TITLE
Related posts from different store_view show up even when the post doesn't exist in the different store_view.

### ISSUE THREAD

**Issue by MikeD-J** [mageplaza/magento-2-blog#326]
### Preconditions (*)
1. Magento ver. 2.4.2-p2
2. Module version 4.1

### Steps to reproduce (*)
1. Enable module
2. Make 2 blog posts (blog post A and blog post B)
3. Blog post A is created once for store_view 1 and 2 together.
4. Blog post B is created once for store_view 2.
5. Also some topics are created, topic 1 (which is created for store_view 1) and topic 2 (which is created for store_view 2).
6. Blog post A has topic 1 and topic 2 and blog post B has topic 2.
7. Go to blog post A in store_view 2, blog post B is visible here as related (working correct).
8. Go to blog post A in store_view 1, blog post B is also visible here as related (not intended, when clicking on blog post B, a 404 error appears.).
9. The 404 error is correct because blog post B simply doesn't exist in store_view 1, the problem is that blog post B should't be visible in store_view 1.

### Expected result (*)
1. Blog post B shouldn't be visible as related post in store_view 1 because it doesn't exist in store_view 1.

### Actual result (*)
1. Blog post B is visible and clickable on store_view 1 as related post, when clicked gives 404 error as expected.

### Fix (*)
Currently I have fixed it locally by adding a plugin to the getRelatedPostsCollection() function.
Afterwards addFieldToFilter in order to incorporate current store_view and all store_views (store_view 0).

**Comment by giaphn** [comment]
I have checked and confirmed this issue. We will work hard on it to release a patch soon. 
Once again, thank you very much for your valuable feedback and significant contribution.  If you have any further questions/issues, please feel welcome to reach back out as we would be more than happy to assist.  
I wish you a great day!

**Comment by giaphn** [comment]
Closed due to no response in 7 days
