### ISSUE TITLE
WYSIWYG editor in the content area didn't work

### ISSUE THREAD

**Issue by Kleibert** [mageplaza/magento-2-blog#329]
Better Blog installed via composer
When I wanna add a new post, I can't find the WYSIWYG editor in the content area, and I click the "Show / Hide Editor" button, nothing changes.

Magento 2.4.2 Enterprise Edition 

"name": "mageplaza/magento-2-blog-extension",
"description": "Magento 2 Blog extension",
"require": {
"mageplaza/module-core": "^1.4.5"
},
"type": "magento2-module",
"version": "4.1.1",
"license": "proprietary",

"name": "mageplaza/module-core",
"description": "Mageplaza Core for Magento 2",
"type": "magento2-module",
"version": "1.4.10",
"license": "proprietary",

![Screen Shot 2021-11-30 at 1 08 31 PM](https://user-images.githubusercontent.com/42814600/144267291-6ee7a993-4878-4a09-b97c-80f594ce0d10.png)

**Comment by popo888** [comment]
I have the same problem. Does anyone know how to deal with it

**Comment by Kleibert** [comment]
> I have the same problem. Does anyone know how to deal with it

Hi, 
We found the problem , 
in Mageplaza module they use /** @var \Magento\Backend\Model\View\Result\Page|Page $resultPage */ 
in mageplaza/magento-2-blog-extension/Controller/Adminhtml/Post/Edit.php

and the page  use vendor/magento/framework/Data/Form/Element/Editor.php  to return the function getInLineJs for render it on phtml. 
The problem is because we use a DNS cloudFlare, the page load faster after the require.js are loaded, so we got undefined.

you can create a module like 

app/code/<Vendor>/Blog/etc/di.xml
`<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Framework\Data\Form\Element\Editor" type="<Vendor>\Blog\Block\Element\Editor" />
</config>`


app/code/<Vendor>/Blog/Block/Element/Editor.php
`<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

namespace <Vendor>\Blog\Block\Element;

/**
 * Form editor element
 *
 * @author      Magento Core Team <core@magentocommerce.com>
 */
class Editor extends \Magento\Framework\Data\Form\Element\Editor
{

    /**
     * @param string $jsSetupObject
     * @param string $forceLoad
     *
     * @return string
     */
    protected function getInlineJs($jsSetupObject, $forceLoad)
    {
        $objectManager  = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
        $secureRenderer = $objectManager->get(\Magento\Framework\View\Helper\SecureHtmlRenderer::class);
        $serializer     = $objectManager->get(\Magento\Framework\Serialize\Serializer\Json::class);
        $jsString       = '
                //<![CDATA[
                window.tinyMCE_GZ = window.tinyMCE_GZ || {};
                window.tinyMCE_GZ.loaded = true;
                window.onload = function() {require([
                "jquery",
                "mage/translate",
                "mage/adminhtml/events",
                "mage/adminhtml/wysiwyg/tiny_mce/setup",
                "mage/adminhtml/wysiwyg/widget"
                ], function(jQuery){' .
            "\n" .
            '  (function($) {$.mage.translate.add(' .
            $serializer->serialize(
                $this->getButtonTranslations()
            ) .
            ')})(jQuery);' .
            "\n" .
            $jsSetupObject .
            ' = new wysiwygSetup("' .
            $this->getHtmlId() .
            '", ' .
            $this->getJsonConfig() .
            ');' .
            $forceLoad .
            '
                    editorFormValidationHandler = ' .
            $jsSetupObject .
            '.onFormValidation.bind(' .
            $jsSetupObject .
            ');
                    Event.observe("toggle' .
            $this->getHtmlId() .
            '", "click", ' .
            $jsSetupObject .
            '.toggle.bind(' .
            $jsSetupObject .
            '));
                    varienGlobalEvents.attachEventHandler("formSubmit", editorFormValidationHandler);
                //]]>
                })};';

        return $secureRenderer->renderTag('script', ['type' => 'text/javascript'], $jsString, false);
    }
}`

**Comment by Kleibert** [comment]
> I have the same problem. Does anyone know how to deal with it

**Comment by popo888** [comment]
Thank you very much. That solves my problem perfectly

>
