### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getId() 

### ISSUE THREAD

**Issue by abhisekhranjan** [mageplaza/magento-2-blog#330]
Fatal error: Uncaught Error: Call to a member function getId() on integer in /var/www/html/app/code/Mageplaza/RewardPoints/Model/Action.php:79 Stack trace: #0 /var/www/html/app/code/Mageplaza/RewardPoints/Model/Action/Earning/Order.php(55): Mageplaza\RewardPoints\Model\Action->prepareTransaction() #1 /var/www/html/app/code/Mageplaza/RewardPoints/Model/Transaction.php(154): Mageplaza\RewardPoints\Model\Action\Earning\Order->prepareTransaction() #2 /var/www/html/app/code/Mageplaza/RewardPoints/Helper/Data.php(507): Mageplaza\RewardPoints\Model\Transaction->createTransaction('earning_order', 3512, Object(Magento\Framework\DataObject)) #3 /var/www/html/app/code/Mageplaza/RewardPoints/Observer/SalesOrderInvoiceSaveAfter.php(63): Mageplaza\RewardPoints\Helper\Data->addTransaction('earning_order', 3512, 1090, Object(Magento\Sales\Model\Order\Interceptor)) #4 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Mageplaza\RewardPoints\Observer\SalesOrderInvoiceSaveAfter->execute(Object(Magento\Framework\Eve in /var/www/html/app/code/Mageplaza/RewardPoints/Model/Action.php on line 79

**Comment by ngvantuong** [comment]
Hello,
I am Raymond from Mageplaza Support Team.
Because this is the issue of the Reward Points module, please submit a ticket to get better support. You can contact us here: https://www.mageplaza.com/contact.html
As this issue does not relate to the Blog module, kindly allow me to close this.
Thanks for your understanding.

**Comment by giaphn** [comment]
Close due to no related to Blog extension.
