### ISSUE TITLE
Shortcode doesn't render correctly

### ISSUE THREAD

**Issue by AndreaTunda** [mageplaza/magento-2-blog#34]
Hi, i'm trying to add some shortcode, like images, in my posts, but seems the code doesn't render correctly.

I'm adding this code, using the "Insert image.." function, like this:
`<img src="{{media url="wysiwyg/home/ff-mobile-homepage-map.png"}}" alt="" />`

And the code in front-end is rendered like this:
`<img src="{{media url=" wysiwyg="" home="" ff-mobile-homepage-map.png"}}"="" alt="">`

Anyone noticed or resolved this bug?

Thankyou

**Comment by Kenny1994** [comment]
Hi AndreaTunda, we have fixed that issue, please check it again !

**Comment by AndreaTunda** [comment]
Thankyou for the reply, we update the latest version of the module but we have the same problem.

![schermata 2017-05-03 alle 09 02 08](https://cloud.githubusercontent.com/assets/10672351/25651177/dd14622a-2fe1-11e7-82e9-4a24844198ec.png)

**Comment by Kenny1994** [comment]
Hi, Andrea
Did you download from ours website or github?. At the moment, we are moving all free extensions to github, so you just pull the lastest version and re-install that module. 
In the lastest version from github, you can normaly add image OR widget to post content.
![untitled](https://cloud.githubusercontent.com/assets/26645811/25656620/1bd147ac-3024-11e7-85ba-7b37387a4ce6.png)

**Comment by AndreaTunda** [comment]
Tested now, it works very well. 

Thankyou very much 👍
