### ISSUE TITLE
Magento 2.4.5 support

### ISSUE THREAD

**Issue by muuk-isaac** [mageplaza/magento-2-blog#347]
Add magento 2.4.5 support

**Comment by zaietsv** [comment]
@muuk-isaac  I was trying the Blog module at magento 2.4.5-p1. It looks fine.

**Comment by KhietNguyen83** [comment]
Hi @muuk-isaac ,
I'm Justin from Mageplaza.
Please help me to download the latest extension version.
Thank you!
