### ISSUE TITLE
Cant edit categories or posts 

### ISSUE THREAD

**Issue by Tonop** [mageplaza/magento-2-blog#46]
### Preconditions

Magento: 2.1.6
PHP: 5.6.26
MySQL: 14.14 Distrib 5.7.15
Module version 2.2.2

### Steps to reproduce

1. Select created category 
2.  
3. 

### Expected result

1. User can edit category
### Actual result

1.  System redirects to a home admin page

In version from https://www.mageplaza.com/magento-2-blog-extension/ there was no issues, it worked correctly. But then I uninstalled it and installed version from github I got these errors.
Also on frontend blog page system do not show any categories and post but in admin they are shown.

**Comment by Kenny1994** [comment]
Hi, the version from github is a developing version so you just use the version from ours website. Ours core team still working for the newest version and we will release it as soon as possible. Thanks!

**Comment by Tonop** [comment]
Hi,

I see. How to install the right version from github?
If I use a package, it is installed in app/code folder. But if I pull from github, it is installed in vendor folder.  And both installation can cause conflicts.

**Comment by Kenny1994** [comment]
Hi
Here is the right version for you, of course it is a temporary vesion 
Take the following step : 
-Uninstall your old module
-Delete all folder Mageplaza/Blog
-Download this version as Zip and replace the old one
You must sure that you have deleted all folder completely

https://github.com/mageplaza/magento-2-blog/tree/7b6ad046e4d284942ee77f76093e8a398ab659e7
