### ISSUE TITLE
Post View throws exception when query parameters are added to the GET request

### ISSUE THREAD

**Issue by jbitshine** [mageplaza/magento-2-blog#49]
### Preconditions

1. Magento: 2.1.4
2. PHP: 7.0
3. MySQL: 5.6

### Steps to reproduce

1. Install the plugin
2. Write a post (i.e. https://www.example.com/news/my-post.html)
3. Access the post page and add a get query (i.e. https://www.example.com/news/my-post.html?test=abc)

### Expected result

1. The page loads correctly ignoring the query

### Actual result

1. getParams loads an array with multiple arguments, causing the query to fail:

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[21000]: Cardinality violation: 1241 Operand should contain 1 column(s), query was: SELECT `mageplaza_blog_post_traffic`.* FROM `mageplaza_blog_post_traffic` WHERE (`mageplaza_blog_post_traffic`.`post_id`='23', 'abc')
Exception #1 (PDOException): SQLSTATE[000]: Cardinality violation: 1241 Operand should contain 1 column(s)

I think that the problem resides at Mageplaza\Blog\Controller\Post\View.php:81-83 as the variable $id content is not checked and it is passed to the function directly if it exists.

It may be something caused by the rest of the Magento environment but it is worth investigation. I patched my code by ignoring the $id field when count($id) > 1. However, another (better) solution could be re-create the array by reading the $this->getRequest()->getParams() array and extracting only id.

**Comment by Kenny1994** [comment]
Hi jbitshine, We have fixed that issue .Please try download the lastest version on github, tell me if have any problems. Thanks!
