### ISSUE TITLE
Blog post associate with a product

### ISSUE THREAD

**Issue by imsamthomas** [mageplaza/magento-2-blog#52]
Admin want to associate blog post with a product

So that on a product page you can display related blog posts

**Comment by imsamthomas** [comment]
@Kenny1994 check this feature

**Comment by Kenny1994** [comment]
Sound good !. I will check this new feature and it will be released for the next update .

**Comment by Kenny1994** [comment]
https://github.com/mageplaza/magento-2-blog/commit/a0d7b27992ace08f2de02fee5faf85c8951f39e4
