### ISSUE TITLE
RSS url not working 

### ISSUE THREAD

**Issue by farazahmadkhan** [mageplaza/magento-2-blog#54]
Hi,

When i click on the rss icon (i.e. {baseUrl}/blog/post/rss/) on the blog page, its throwing an exception. Please guide me to resolve this issue.
![rss](https://cloud.githubusercontent.com/assets/25032418/26067523/2da14d40-39b8-11e7-8fee-6a3f3023e20d.png)

```
1 exception(s):
Exception #0 (Exception): Warning: DOMDocument::createElement(): unterminated entity reference       u-3.html/ in /var/www/magento/vendor/magento/zendframework1/library/Zend/Feed/Rss.php on line 409

Exception #0 (Exception): Warning: DOMDocument::createElement(): unterminated entity reference       u-3.html/ in /var/www/magento/vendor/magento/zendframework1/library/Zend/Feed/Rss.php on line 409
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'DOMDocument::cr...', '/var/www/magent...', 409, Array)
#1 /var/www/magento/vendor/magento/zendframework1/library/Zend/Feed/Rss.php(409): DOMDocument->createElement('link', 'http://192.168....')...
```

**Comment by Kenny1994** [comment]
Hi,
It is working normally on my site. Please try download the lastest version on github.
Tell me if you have any problems. Thanks you !
![untitled](https://cloud.githubusercontent.com/assets/26645811/26086745/c0093df6-3a16-11e7-8995-b33aa5aae424.png)

**Comment by farazahmadkhan** [comment]
Thank you very much!
Now its working for me, the problem was with the post url name.
