### ISSUE TITLE
Call to undefined method Magento\Framework\Stdlib\DateTime::timestamp()

### ISSUE THREAD

**Issue by Omi0** [mageplaza/magento-2-blog#57]
Fatal error: Uncaught Error: Call to undefined method Magento\Framework\Stdlib\DateTime::timestamp() in /public_html/app/code/Mageplaza/Blog/Helper/Data.php:696 
Stack trace: 
#0 /public_html/app/code/Mageplaza/Blog/Helper/Data.php(708): Mageplaza\Blog\Helper\Data->getDateArray() 
#1 /public_html/app/code/Mageplaza/Blog/Block/MonthlyArchive/Widget.php(30): Mageplaza\Blog\Helper\Data->getDateArrayCount() 
#2 /public_html/app/code/Mageplaza/Blog/view/frontend/templates/monthly/widget.phtml(23): Mageplaza\Blog\Block\MonthlyArchive\Widget->getDateArrayCount() 
#3 /public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/...') 
#4 /public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Mageplaza\Blog\Block\MonthlyArchive\Widget), '/...', Array) 
#5 /public_html/vendor/magento/framework/View/Element/Template.php(279): in /public_html/app/code/Mageplaza/Blog/Helper/Data.php on line 696

### Preconditions
Magento: 2.1.5
PHP: Version 7.0.19
MySQL: 5.5.32

### Steps to reproduce
1. Install module
2. Publish a post
3. Visit posts front-end

### Expected result
See posts

### Actual result
Error message

**Comment by Omi0** [comment]
The way to fix it is by changing the name of the function to low format datetime in /public_html/app/code/Mageplaza/Blog/Helper/Data.php on line 696 from:
$dateArray[] = date("F Y",$this->dateTime->timestamp($postDate));
to
$dateArray[] = date("F Y",$this->datetime->timestamp($postDate));

**Comment by Kenny1994** [comment]
Hi,
The issue has been fixed. Thank for your response!
Tell me if you have any further problems.

**Comment by Omi0** [comment]
Awesome. Thanks a lot
