### ISSUE TITLE
[UX] Simplify post-tags association

### ISSUE THREAD

**Issue by Koc** [mageplaza/magento-2-blog#62]
### Preconditions

1. Magento: 2.1.7
2. PHP:  7.0
3. MySQL: 5.7

### Steps to reproduce

1.  Open create new post form
2. Select tags tab
3. 

### Expected result

1. Simple association like categories with new tag button

### Actual result

1. unusable grid with filters

Please simplify tags association management like categories management. Same can be applyed for topics also.

**Comment by Kenny1994** [comment]
Hi, I will note this for the next update patch
Thank for your suggestion

**Comment by imsamthomas** [comment]
@Kenny1994 
`Categories, Tags, Topics` should be moved from `Tabs` to under `Content` section
