### ISSUE TITLE
Blog posts not showing

### ISSUE THREAD

**Issue by hedv2** [mageplaza/magento-2-blog#66]
We have followed the instructions during installation of the blog extension and everythings seems to work, but somehow the blogposts aren't showing. We can open Loveish.nl/blog, but if we open a blog post, we only see the title. How can we fix this?

We installed via composer.

**Comment by Kenny1994** [comment]
Hi,
For the technical issues, please submit your ticket to https://mageplaza.freshdesk.com
Our support team will look into this as soon as possible.
