### ISSUE TITLE
Add block name on top level blocks

### ISSUE THREAD

**Issue by michael-tourneur** [mageplaza/magento-2-blog#67]
Would be great to add block name on top level blocks like for `<block class="Mageplaza\Blog\Block\Post\Listpost" template="Mageplaza_Blog::post/index.phtml">`
it will give app developer the possibility to modify things on it

**Comment by Kenny1994** [comment]
Hi,
I will add in the next update patch. Thank for the suggestion

**Comment by michael-tourneur** [comment]
@Kenny1994 great thanks, do you know when will be the next update patch?
