### ISSUE TITLE
Blog category robots

### ISSUE THREAD

**Issue by victorchiriac89** [mageplaza/magento-2-blog#69]
When you want to save the category and the meta_robots, the meta robots values of the select are:
        const INDEXFOLLOW = 'INDEX,FOLLOW';
	const NOINDEXNOFOLLOW = 'NOINDEX,NOFOLLOW';
	const NOINDEXFOLLOW = 'NOINDEX,FOLLOW';
	const INDEXNOFOLLOW = 'INDEX,NOFOLLOW';
And in the database: 

meta_robots | int(11)
-- | --

The value of the meta robots never gets stored.

### Preconditions

1. Magento: 2.1.7
2. PHP: 7.0.18
3. MySQL: 5.7
4. module name="Mageplaza_Blog" setup_version="2.4.2"

### Steps to reproduce

1. Create new category or edit available
2. Set a value for Meta Robots
3. Save

### Expected result

1. It should store the new value for the Meta Robots

### Actual result

1. [Screenshot, logs]

**Comment by Kenny1994** [comment]
Hi,
I fixed that issue in the older commit, please see: https://github.com/mageplaza/magento-2-blog/commit/483cd87004785c643abb8c00fea143c55cbe4549 for the details. ( upgrade schema file )
Tell me if you have any further problems
