### ISSUE TITLE
Problems with resizeImage function

### ISSUE THREAD

**Issue by Tyrianad** [mageplaza/magento-2-blog#70]
Magento: 2.1.7 | PHP: 7.0.21 | MySQL: 5.7.18

Various blog pages where giving a blank page on our DEV server while on the local installation i had  errors regarding GD library. After various tests i found out the problem is related to the $block->resizeImage() function in various template files. As of now i changed the function to $block->getImageUrl($post->getImage()).

On the local installation i installed the module via drag and drop, on dev i installed it via composer.

**Comment by Kenny1994** [comment]
Hi,
I have fixed problem related to resizeImage function in this commit :https://github.com/mageplaza/magento-2-blog/commit/103c75585064467cb0be607bc037e939fdcb9ee2 , please pull the latest version from dev branch 
Tell me if you have any further problems.
