### ISSUE TITLE
Installation failed on clean database

### ISSUE THREAD

**Issue by alinalexandru** [mageplaza/magento-2-blog#76]
Commenting line 42 from vendor/mageplaza/magento-2-blog-extension/Setup/InstallData.php has solved the problem.
I saw that this line was added in this commit https://github.com/mageplaza/magento-2-blog/commit/b591768bb2add35f84ff6085ad6172e241861a5b
Maybe @Kenny1994 know better why that was needed. 

### Preconditions

1. Magento:  2.1.6 (but it should be reproduced on every version)
2. PHP: 7
3. MySQL: 5.6 
4. Clean database

### Steps to reproduce

1.  composer require mageplaza/magento-2-blog-extension:^2.4
2. php -f bin/magento -- setup:install -vvv ....

### Expected result

1. Installation should succeed

### Actual result

1. ..... 
[Progress: 396 / 569]
Module 'Mageplaza_Blog':

                                                    
  [Magento\Framework\Exception\LocalizedException]  
  Area code is already set                          
                                                    

Exception trace:
() at /builds/magento/site/vendor/magento/framework/App/State.php:122
 Magento\Framework\App\State->setAreaCode() at /builds/magento/site/vendor/mageplaza/magento-2-blog-extension/Setup/InstallData.php:41
 Mageplaza\Blog\Setup\InstallData->__construct() at /builds/magento/site/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93
 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() at /builds/magento/site/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:89
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /builds/magento/site/vendor/magento/framework/ObjectManager/ObjectManager.php:57
 Magento\Framework\ObjectManager\ObjectManager->create() at /builds/magento/site/setup/src/Magento/Setup/Model/Installer.php:931
 Magento\Setup\Model\Installer->createSchemaDataHandler() at /builds/magento/site/setup/src/Magento/Setup/Model/Installer.php:1245
 Magento\Setup\Model\Installer->getSchemaDataHandler() at /builds/magento/site/setup/src/Magento/Setup/Model/Installer.php:841
 Magento\Setup\Model\Installer->handleDBSchemaData() at /builds/magento/site/setup/src/Magento/Setup/Model/Installer.php:796
 Magento\Setup\Model\Installer->installDataFixtures() at n/a:n/a
 call_user_func_array() at /builds/magento/site/setup/src/Magento/Setup/Model/Installer.php:344
 Magento\Setup\Model\Installer->install() at /builds/magento/site/setup/src/Magento/Setup/Console/Command/InstallCommand.php:125
 Magento\Setup\Console\Command\InstallCommand->execute() at /builds/magento/site/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /builds/magento/site/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /builds/magento/site/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /builds/magento/site/vendor/magento/framework/Console/Cli.php:96
 Magento\Framework\Console\Cli->doRun() at /builds/magento/site/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /builds/magento/site/bin/magento:23

**Comment by imsamthomas** [comment]
Hi Alexandru,

Can you check and remove folder: app/code/Mageplaza/Blog

Then run the command again.

**Comment by alinalexandru** [comment]
I don't have the extension in the app/code folder. Only in vendor.

**Comment by sky-hub** [comment]
@imsamthomas, first of all I do not really see the point on setting 'frontend' area code when running a data installer, maybe you can provide an explanation for it as I could not find one.

Second, if you want to run **magento:install** when you already have all modules already downloaded, including your module, it breaks the install.

If you have a look at Magento/Setup/Console/Command/InstallCommand->execute() you will notice that it calls Magento/Setup/Model/Installer->install() which is already setting an area code when calling installUserConfig(). This does not happen when running **setup:upgrade** because no area code is set while running this command.

**Comment by alinalexandru** [comment]
Can you do also a new release?

**Comment by imsamthomas** [comment]
Thanks for your contribution.
We have released v2.4.3

**Comment by alinalexandru** [comment]
Do you know why is not updated in packagist?

**Comment by imsamthomas** [comment]
Thanks for your report @alinalexandru .
Packagist does not update automatically, this is rarely case. I have updated it manually. See https://packagist.org/packages/mageplaza/magento-2-blog-extension#2.4.3

**Comment by roura356a** [comment]
Great, now it fails when running `bin/magento setup:upgrade` after installing Blog in Magento 2.1.7. Un-commenting the lines `38` and `41` it works again.

**Comment by alinalexandru** [comment]
What error do you receive?
Run setup:upgrade -vvv for more debug informations
