### ISSUE TITLE
Compatible with YourStore Theme

### ISSUE THREAD

**Issue by imsamthomas** [mageplaza/magento-2-blog#79]
Our customers want to make this blog module compatible with [YourStore Theme](https://themeforest.net/item/yourstore-premium-multipurpose-magento-theme/17782705).
Please help.

**Comment by Kenny1994** [comment]
compatible with [YourStore Theme](https://themeforest.net/item/yourstore-premium-multipurpose-magento-theme/17782705) commit : https://github.com/mageplaza/magento-2-blog/commit/4b5215a9eebe7d38f5ccd9764b4db9bcd56fc2f6
