### ISSUE TITLE
setup:upgrade - Area code not set: Area code must be set before starting a session.

### ISSUE THREAD

**Issue by Alex-James17** [mageplaza/magento-2-blog#80]
Following a composor update, running setup:upgrade produces the following error with Magento 2.2.0 whilst installing the data components of the module:

Installing data... Area code not set: Area code must be set before starting a session.

To resolve I added the following dependancy injection to the constructor of the Mageplaza\Blog\Setup\InstallData class:

\Magento\Framework\App\State $state

followed by this code within the constructor method:

 $state->setAreaCode('frontend');

Then I removed the "Mageplaza_Blog" entry from the setup_module table and re run setup:upgrade

**Comment by Kenny1994** [comment]
Hi,
Thank for your suggestion, I have added the following code to solve the problem.

**Comment by Alex-James17** [comment]
Thank you

**Comment by rahulthakral38** [comment]
Hi

Can you guys please update what changes need to do, which files are associated? I am facing the same issue.

Thanks
Rahul
