### ISSUE TITLE
Error during composer installation

### ISSUE THREAD

**Issue by valentinmanthei** [mageplaza/magento-2-blog#81]
### Preconditions

1. Magento: 2.1.5
2. PHP: 5.6.29
3. MySQL: 
4. 

### Steps to reproduce

1. composer require mageplaza/magento-2-blog-extension
2. php bin/magento setup:upgrade 

### Expected result

1. Upgrade should succeed

### Actual result

1. [Screenshot, logs]

Module 'Mageplaza_Blog':
Installing data...

  [Magento\Framework\Exception\SessionException]
  Area code not set: Area code must be set before starting a session.

  [Magento\Framework\Exception\LocalizedException]
  Area code is not set

**Comment by imsamthomas** [comment]
We fixed this issue on https://github.com/mageplaza/magento-2-blog/releases/tag/v2.4.4

Thanks

**Comment by valentinmanthei** [comment]
Thank you for the fast fix, I appreciate it!

Would you be so kind to sync the new release to Packagist as well?

Thank you!
