### ISSUE TITLE
Packagist version out of date

### ISSUE THREAD

**Issue by valentinmanthei** [mageplaza/magento-2-blog#83]
Hey everybody,

could you please so kind to push version 2.4.4 to Packagist? Only 2.4.3 is available there.
Maybe it would be helpful for you if you would setup the automatic Packagist publish hook as soon as a new tag has been created.

Thank you!

**Comment by haitv282** [comment]
Hi,

Thank you for noticing us. It has been updated on Packagist. Please check it again.
