### ISSUE TITLE
Error when saving edited post

### ISSUE THREAD

**Issue by valentinmanthei** [mageplaza/magento-2-blog#86]
magento-2-blog version: 2.4.4

Creating a post works fine, but when you try to edit and save it the following exception occurs.
I suppose it's due to the German locale I am using in Magento. You should probably rather use DateTime::createFromFormat() and apply the Magento locale. Thank you.

a:4:{i:0;s:114:"DateTime::__construct():` Failed to parse time string (17.08.17 15:49) at position 9 (1): Double time specification";i:1;s:4938:"#0 /var/www/magento2/vendor/mageplaza/magento-2-blog-extension/Controller/Adminhtml/Post/Save.php(240): DateTime->__construct('17.08.17 15:49', Object(DateTimeZone))
#1 /var/www/magento2/vendor/mageplaza/magento-2-blog-extension/Controller/Adminhtml/Post/Save.php(116): Mageplaza\Blog\Controller\Adminhtml\Post\Save->converToTz('17.08.17 15:49', 'UTC', 'Europe/Berlin')
#2 /var/www/magento2/var/generation/Mageplaza/Blog/Controller/Adminhtml/Post/Save/Interceptor.php(24): Mageplaza\Blog\Controller\Adminhtml\Post\Save->execute()
#3 /var/www/magento2/vendor/magento/framework/App/Action/Action.php(102): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->execute()
#4 /var/www/magento2/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callParent('dispatch', Array)
#7 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Mageplaza\\Blog\\...', 'dispatch', Object(Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor), Array, 'adminAuthentica...')
#8 /var/www/magento2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#9 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Mageplaza\\Blog\\...', 'dispatch', Object(Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor), Array, 'adminMassaction...')
#11 /var/www/magento2/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /var/www/magento2/var/generation/Mageplaza/Blog/Controller/Adminhtml/Post/Save/Interceptor.php(52): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callPlugins('dispatch', Array, Array)
#14 /var/www/magento2/vendor/magento/framework/App/FrontController.php(55): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#16 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#17 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#18 /var/www/magento2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#19 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#20 /var/www/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#21 /var/www/magento2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#23 /var/www/magento2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#24 {main}";s:3:"url";s:124:"/admin_1i673w/mageplaza_blog/post/save/key/56911aaedabce05fa14410f9705abc13a09be505494251f0ab7313aeb115a39e/active_tab/post/";s:11:"script_name";s:10:"/index.php";}

**Comment by Kenny1994** [comment]
Hi,
I didn't find out the issue on my test site.
Could you grant me the video or some pictures so that I can see where is the issue come from?
Thank!

**Comment by valentinmanthei** [comment]
Did you change the locale of your Magento installation? Alternatively you need to put in the post date in a different format, e.g. "17.08.17 15:49".

Thank you,
Valentin

**Comment by andparsons** [comment]
I'm having the same issue, it'll only occur if the day of the post has been set to a number greater than 12, indicating the process is trying to read the day as the month.
Choosing the date from the date-picker gives the field 13/12/2016 for example, which causes the error.
12/12/2016 works fine.
Entering 12/13/2016 manually works, and after the entry reloads, the date is shown as 13/12/2016 in the field, thus re-saving the entry causes the error.

**Comment by Kenny1994** [comment]
Hi,
Thank for the reported issue. The problem comes from publish date time format, it is incorrect 
Here is the fix, please check it again: https://github.com/mageplaza/magento-2-blog/commit/9ae3d9edc0f9ec6bcff105c17af205adc3e1d58e.

**Comment by valentinmanthei** [comment]
I had a look at the commit, it does seem to address andparsons issue, but it's not internationalized.
`date_create_from_format('d/m/Y H:i',$dateTime,new \DateTimeZone($fromTz))`

You need to pull the Magento date formatting (because the date format differs based on the locale of the shop) instead of hardcoding 'd/m/Y H:i' in this place.

Thank you.

**Comment by Kenny1994** [comment]
Hi,
I think that it doesn't affect too much if you change the locale of each place. Since the publish date field is always in dd/mm/yyyy format, you can see the image : 
![selection_014](https://user-images.githubusercontent.com/26645811/29648938-45ed7458-88bb-11e7-8c6f-758e439abc7f.png)
I tried to get the Magento date format : $this->_objectManager->get('Magento\Framework\Stdlib\DateTime\TimezoneInterface')->getDateTimeFormat(\IntlDateFormatter::SHORT) and replace into 'm/m/Y H:i'
However, it incorrectly reports the format and $date returns false. I am very grateful if you have any better idea on this problem, as I see this is the most reasonable and international way.
