### ISSUE TITLE
500 Internal server error on blog posts.

### ISSUE THREAD

**Issue by cdhalwatura** [mageplaza/magento-2-blog#87]
I would like to report following issue

When I access blog posts, I can see 500 internal server error. Following error log I managed to trace from our server.

2017/08/21 09:30:41 [error] 23399#23399: *379474 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Mageplaza\Blog\Block\Post\Relatedproduct::__construct() must be an instance of Magento\Catalog\Block\Product\Context, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /var/www/vhosts/m2.x.com/htdocs/xx/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /var/www/vhosts/m2.x.com/htdocs/xx/app/code/Mageplaza/Blog/Block/Post/RelatedProduct.php:44
Stack trace:

Is there any fix for this issue?

**Comment by Kenny1994** [comment]
Hi,
I have tested on my local and didn't see the issue that you mentioned. Please grant me several pictures for the detail so that I can fix it.
Thank you!

**Comment by kriby** [comment]
Hi!
I experience the same issue.
It is reproducible only in Production mode.
The problem here is that class name does not correspond to filename. Relatedproduct class should be renamed to RelatedProduct.

**Comment by admaduranga** [comment]
Hi!
I experienced the same issue in Production mode.

@kriby is correct problem was in the file
vendor/mageplaza/magento-2-blog-extension/Block/Post/RelatedProduct.php:22 

Noticed this problem is fixed with the commit **mageplaza/magento-2-blog-extension:2.4.6 (tag v2.4.6)**
Thank you all!

**Comment by jer23jk** [comment]
Hello,

I have installed latest version 2.5.0 magento-2-blog-extension
After getting error 500 I fixed with the commit mageplaza/magento-2-blog-extension:2.4.6 

Thanks admaduranga!

**Comment by admaduranga** [comment]
Always welcome!
