### ISSUE TITLE
post image is missing after the post is exited

### ISSUE THREAD

**Issue by govindarajprevaj** [mageplaza/magento-2-blog#9]
After edit the post already create the post image is missing.

But if the image is replace with another image when we edit the post the the image display correctly.

**Comment by digitalredefned** [comment]
Also experiencing this issue

**Comment by imsamthomas** [comment]
We have noted your request and update this soon

**Comment by AndreaTunda** [comment]
Any update fort this problem? I have the same too. 

Thankyou

**Comment by AndreaTunda** [comment]
The problem is solved, thankyou very much 👍
