### ISSUE TITLE
Code Compilation Stuck Up! - Incompatible argument type...

### ISSUE THREAD

**Issue by shinesoftware** [mageplaza/magento-2-blog#90]
### Preconditions

I have downloaded your Git version of the Magento 2 Blog but when I try to compile it I get 3 errors. Look below for more details.

1. Magento: 2.2
2. PHP: 7.0.22
3. MySQL: 14.14

### Steps to reproduce
Move your Magento store in production mode

### Expected result
A good compilation of the code

### Actual result
No compilation

    Interception cache generation... 6/7 [========================>---]  85% 34 secs 288.0 MiBErrors during compilation:
		Mageplaza\Blog\Model\ResourceModel\Post\Grid\Collection
			Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \Mageplaza\Blog\Model\ResourceModel\Post\Grid\connection; File:
	/var/www/html2/magento.local/app/code/Mageplaza/Blog/Model/ResourceModel/Post/Grid/Collection.php

		Mageplaza\Blog\Model\ResourceModel\Topic\Grid\Collection
			Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \Mageplaza\Blog\Model\ResourceModel\Topic\Grid\connection; File:
	/var/www/html2/magento.local/app/code/Mageplaza/Blog/Model/ResourceModel/Topic/Grid/Collection.php

		Mageplaza\Blog\Model\ResourceModel\Tag\Grid\Collection
			Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \Mageplaza\Blog\Model\ResourceModel\Tag\Grid\connection; File:
	/var/www/html2/magento.local/app/code/Mageplaza/Blog/Model/ResourceModel/Tag/Grid/Collection.php

	Total Errors Count: 3

	  [Magento\Framework\Validator\Exception]
	  Error during compilation

**Comment by Kenny1994** [comment]
Hi, 
Thank for your suggestion
I have tried run command compile at my local and it is working normally
![selection_024](https://user-images.githubusercontent.com/26645811/29697239-2f8f72fc-8978-11e7-8187-cc53949aee3d.png)

**Comment by Kenny1994** [comment]
Hi,
Thanks for the suggestion, the fixing patch has been added to the develop branch: https://github.com/mageplaza/magento-2-blog/commit/d0b7eea3b7ac33c88967600bde0b3f26e568a480
If there are any further problems, feel free to contact us.
