### ISSUE TITLE
Error when a post is saved

### ISSUE THREAD

**Issue by shinesoftware** [mageplaza/magento-2-blog#92]
Preconditions

I have downloaded your Git version of the Magento 2 Blog but when I try to save a post I get this error:

    DateTime::__construct(): Failed to parse time string (25/08/17 16:25) at position 0 (2): Unexpected character

Magento: 2.2
PHP: 7.0.22
MySQL: 14.14
Steps to reproduce

Move your Magento store in production mode

Expected result
Saving the post record

Actual result
Error on screen

**Comment by Kenny1994** [comment]
Hi,
We have fixed this problem already, please check this solution https://github.com/mageplaza/magento-2-blog/issues/86. I think It will help you to resolve the problem.
Thanks!

**Comment by comdvas** [comment]
Same problem here. Version 2.4.6, Magento 2.1.9
I discover, that if I will change field "Publication date" from this "24.06.10 9:23" to this "24.06.2010 9:23" it will saved successfully.
Maybe some locale problems? My locale is Russian and date format in Blog settings is "d/m/Y H:i (31/10/2017 17:00)"

**Comment by haitv282** [comment]
Hi there,

We are so sorry for late response.
The "publication date" problem has been noted, and it will be checked carefully and solved in the next version. Please wait for our new update.
Thank you very much.
