### ISSUE TITLE
Enhancement: Add category lvl as css class to menu-categories li

### ISSUE THREAD

**Issue by carloricci84** [mageplaza/magento-2-blog#94]
Subcategories are at the same level as categories in the blog sidebar

### Preconditions
Create a category with subcategories

### Expected result
Subcategories should be visually different from parent categories

### Actual result
![screen shot 2017-09-14 at 10 35 54 am](https://user-images.githubusercontent.com/6392435/30435768-97addc1e-9938-11e7-99ac-8d6df0561bfe.png)

### Proposed solution
Add a css class level-x on the  li class="category-item" so the users can style it as they want in the file view/frontend/templates/category/widget.phtml
```html
<?php foreach ($categories as $category): ?>
    <li class="category-item level-<?php echo $category->getLevel()" >
        <a class="list-categories" href="<?php echo $block->getCategoryUrl($category) ?>">
             <i class="fa fa-folder-open-o">&nbsp;&nbsp;</i><?php echo ucfirst($category->getName())?></a>
    </li>
<?php endforeach; ?>
```

**Comment by Kenny1994** [comment]
Hi,
Thanks for the suggestion, I will check this improvement for our next patch update.

**Comment by Kenny1994** [comment]
Hi,
Here is the improvement of category tree design:https://github.com/mageplaza/magento-2-blog/commit/4d96a8df8c7d4b0e194a8b40aee3161f507c5a4e
If there are any further problems, feel free to contact us.
Thanks
