### ISSUE TITLE
Magento 2.2 CE setup:di:compile error

### ISSUE THREAD

**Issue by rbur0425** [mageplaza/magento-2-blog#96]
### Preconditions
1. Magento: 2.2 CE
2. PHP:  7.0.23
3. MySQL: 5.7
Mageplaza Magento 2 Blog 2.4.6

### Steps to reproduce
1. Install Magento 2.2
2. Install mageplaza magento-2-blog by composer
3. run php bin/magento setup:di:compile

### Expected result
1. Compiles successfully

### Actual result
Errors during compilation:
	Mageplaza\Blog\Model\ResourceModel\Post\Grid\Collection
		Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \Mageplaza\Blog\Model\ResourceModel\Post\Grid\connection; File:
/vendor/mageplaza/magento-2-blog-extension/Model/ResourceModel/Post/Grid/Collection.php

	Mageplaza\Blog\Model\ResourceModel\Tag\Grid\Collection
		Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \Mageplaza\Blog\Model\ResourceModel\Tag\Grid\connection; File:
/vendor/mageplaza/magento-2-blog-extension/Model/ResourceModel/Tag/Grid/Collection.php

	Mageplaza\Blog\Model\ResourceModel\Topic\Grid\Collection
		Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \Mageplaza\Blog\Model\ResourceModel\Topic\Grid\connection; File:
/vendor/mageplaza/magento-2-blog-extension/Model/ResourceModel/Topic/Grid/Collection.php

Total Errors Count: 3

  [Magento\Framework\Validator\Exception]
  Error during compilation

**Comment by Kenny1994** [comment]
Hi,
The problem occurs only when you upgrade to Magento 2.2.
$connection need to be an instance of \Magento\Framework\DB\Adapter\AdapterInterface.
Here is the fixing patch: https://github.com/mageplaza/magento-2-blog/commit/d0b7eea3b7ac33c88967600bde0b3f26e568a480
If there is any further problem, feel free to contact us.
Thanks!

**Comment by rbur0425** [comment]
Thanks I have applied the fixes and it compiles correctly.
