### ISSUE TITLE
Unicode characters for "Route Name" in config

### ISSUE THREAD

**Issue by Mehran91z** [mageplaza/magento-2-blog#97]
### Preconditions

1. Magento: 2.1.8
2. PHP: 7.0.22
3. MySQL: 5.0.12

### Steps to reproduce

You should 
![better_blog_route_name_unicode_chars_problem](https://user-images.githubusercontent.com/17524536/31047734-e31cb17a-a61c-11e7-9c77-ed7928ac15b7.jpg)
Write UNICODE characters (Like characters in Persian language:  وبلاگ) for `Route Name` in configuration page.

### Expected result

It should change the route of blog url to `/وبلاگ` and users can open blog using this url.

### Actual result

It does not work and return an `404 Not Found` error.

**Comment by Kenny1994** [comment]
Hi,
The fixing patch here: https://github.com/mageplaza/magento-2-blog/commit/26f29b6ec5b1f619d08cdcde89824227b2a9d7f6
If there are any further issues, feel free to contact me.
Thanks
