### ISSUE TITLE
 Class 'Mageplaza\Core\Helper\AbstractData' not found

### ISSUE THREAD

**Issue by Krupaly2k** [mageplaza/magento-2-blog#98]
### Preconditions

1. Magento:  2.1.7
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1.  At the time of php magento setup:upgrade command you will see this error
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by Kenny1994** [comment]
Hi,
Regarding your problem, you must install Core extension side by side with the Blog.
Here is the GitHub address where you can download the Core extension:https://github.com/mageplaza/module-core
If there are any further questions, feel free to contact us.
Thanks!

**Comment by Krupaly2k** [comment]
Hi,
Thanks for the response. What is the use of core extension?
Thanks!

**Comment by Kenny1994** [comment]
Hi,
All of Mageplaza extension is inheriting the Mageplaza-Core extension, you must install Core extension to use.

**Comment by Krupaly2k** [comment]
Ok, Thanks. It works!

**Comment by soundararajanm1990** [comment]
Hi,
Still i'm also getting same error

**Comment by ChienNguyenVP** [comment]
Hi,
You need to install the Mageplaza-Core extension first, All of Mageplaza extension is inheriting this:
https://github.com/mageplaza/module-core
If you have any question, please contact us.
Thanks!

**Comment by soundararajanm1990** [comment]
Ok thanks chienNguyenVp, its working fine

**Comment by ChienNguyenVP** [comment]
Thank you for using our extension.

**Comment by thahseerali** [comment]
I tried to install a banner slider in magento 2 xamp server. After completing the installation i cannot open my webpage, showing the error : **Fatal error: Class 'Mageplaza\Core\Helper\AbstractData' not found in C:\**
As i am a beginner can you explain how to install the Mageplaza-Core extension to fix this issue?

**Comment by phplead4** [comment]
Hello Support team,
While enabling the extension it's giving the error PHP Fatal error:  Class 'Mageplaza\Core\Helper\AbstractData' not found in /var/www/live.aloegarve.com/html/app/code/Mageplaza/Smtp/Helper/Data.php, there is error in the extension, please see the screenshot: https://www.awesomescreenshot.com/image/30798579?key=628ec665e5d1eafa9c10d69917229e91
