### ISSUE TITLE
Notice: Undefined offset: 0

### ISSUE THREAD

**Issue by Krupaly2k** [mageplaza/magento-2-blog#99]
### Preconditions

1. Magento: 2.1.7
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. I have setup blog in my site and on click of read more of post or on click of right sidebar category it shows below issue
Notice: Undefined offset: 0 in /app/code/Mageplaza/Blog/Block/Frontend.php on line 427
2.  Also, How can I remove Mageplaxa image on right side
3. 

### Expected result

1.  Please help me to resolve this as soon as possible

### Actual result

1. [Screenshot, logs]

**Comment by haitv282** [comment]
Hi there,

We are so sorry for this late reply.
The problem which you mentions has been solved in the latest version. Please upgrade the extension and check it again.
Thank you very much.
